# Generated by Django 2.2 on 2020-04-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20200419_1603'),
        ('users', '0002_auto_20190601_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(related_name='users', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usersActiveCompany', to='companies.Company'),
        ),
        migrations.DeleteModel(
            name='Access',
        ),
    ]
