# Generated by Django 2.2 on 2020-07-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200719_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.city', 'مشاهده شهر'), ('create.city', 'تعریف شهر'), ('update.city', 'ویرایش شهر'), ('delete.city', 'حذف شهر'))},
        ),
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'default_permissions': (), 'get_latest_by': 'id', 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.role', 'مشاهده نقش'), ('create.role', 'تعریف نقش'), ('update.role', 'ویرایش نقش'), ('delete.role', 'حذف نقش'))},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': (('get.user', 'مشاهده کاربر'), ('getOwn.user', 'مشاهده کاربران خود'), ('create.user', 'تعریف کاربر'), ('update.user', 'ویرایش کاربر'), ('delete.user', 'حذف کاربر'), ('changePassword.user', 'تغییر کلمه عبور کاربران')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
