# Generated by Django 2.2 on 2020-04-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200419_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companies',
        ),
    ]
