# Generated by Django 2.2 on 2020-06-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200609_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'permissions': (('get.city', 'مشاهده شهر'), ('create.city', 'تعریف شهر'), ('update.city', 'ویرایش شهر'), ('delete.city', 'حذف شهر')),
                'default_permissions': (),
            },
        ),
    ]
