# Generated by Django 2.2 on 2020-07-20 05:13

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200719_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.role', 'مشاهده نقش'), ('getOwn.role', 'مشاهده نقش های خود'), ('create.role', 'تعریف نقش'), ('update.role', 'ویرایش نقش'), ('delete.role', 'حذف نقش'))},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
    ]
