# Generated by Django 2.2 on 2020-07-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200720_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.role', 'مشاهده نقش'), ('create.role', 'تعریف نقش'), ('update.role', 'ویرایش نقش'), ('delete.role', 'حذف نقش'), ('getOwn.role', 'مشاهده نقش خود'), ('updateOwn.role', 'ویرایش نقش خود'), ('deleteOwn.role', 'حذف نقش خود'))},
        ),
    ]
