# Generated by Django 2.2 on 2020-04-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20200419_1603'),
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0005_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.Company')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='auth.Permission')),
            ],
        ),
    ]
