# Generated by Django 2.2 on 2020-07-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200720_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': (('get.user', 'مشاهده کاربر'), ('create.user', 'تعریف کاربر'), ('update.user', 'ویرایش کاربر'), ('delete.user', 'حذف کاربر'), ('changePassword.user', 'تغییر کلمه عبور کاربران'), ('getOwn.user', 'مشاهده کاربران خود'), ('updateOwn.user', 'ویرایش کاربران خود'), ('deleteOwn.user', 'حذف کاربران خود'), ('changePasswordOwn.user', 'تغییر کلمه عبور کاربران خود')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
