# Generated by Django 2.2 on 2020-08-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200726_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usersActiveCompany', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='companies.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
