# Generated by Django 2.2 on 2020-09-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usersActiveCompany', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='companies.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='superuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
