# Generated by Django 2.2 on 2020-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201001_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.city', 'مشاهده شهر'), ('create.city', 'تعریف شهر'), ('update.city', 'ویرایش شهر'), ('delete.city', 'حذف شهر'))},
        ),
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'default_permissions': (), 'get_latest_by': 'id', 'ordering': ['-pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.role', 'مشاهده نقش'), ('create.role', 'تعریف نقش'), ('update.role', 'ویرایش نقش'), ('delete.role', 'حذف نقش'), ('getOwn.role', 'مشاهده نقش خود'), ('updateOwn.role', 'ویرایش نقش خود'), ('deleteOwn.role', 'حذف نقش خود'))},
        ),
    ]
