# Generated by Django 2.2 on 2021-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201107_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.city', 'مشاهده شهر'), ('create.city', 'تعریف شهر'), ('update.city', 'ویرایش شهر'), ('delete.city', 'حذف شهر'))},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.role', 'مشاهده نقش'), ('create.role', 'تعریف نقش'), ('update.role', 'ویرایش نقش'), ('delete.role', 'حذف نقش'), ('getOwn.role', 'مشاهده نقش خود'), ('updateOwn.role', 'ویرایش نقش خود'), ('deleteOwn.role', 'حذف نقش خود'))},
        ),
    ]
