# Generated by Django 2.2 on 2021-06-13 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('send_notification', models.BooleanField()),
                ('notification_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_explanation', models.TextField(blank=True, null=True)),
                ('notification_link', models.CharField(blank=True, max_length=255, null=True)),
                ('send_sms', models.BooleanField()),
                ('sms_text', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('p', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('r', 'خوانده شده')], max_length=2)),
                ('notification_status', models.CharField(choices=[('p', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('r', 'خوانده شده')], max_length=2)),
                ('sms_status', models.CharField(choices=[('p', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('r', 'خوانده شده')], max_length=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
