# Generated by Django 2.2 on 2021-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210613_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_status',
            field=models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('r', 'خوانده شده')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('r', 'خوانده شده')], max_length=2, null=True),
        ),
    ]
