# Generated by Django 2.2 on 2021-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210613_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_status',
            field=models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='status',
            field=models.CharField(choices=[('p', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2),
        ),
    ]
