# Generated by Django 2.2 on 2021-06-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210613_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show_pop_up',
            field=models.BooleanField(default=False),
        ),
    ]
