# Generated by Django 2.2 on 2021-06-23 05:55

from django.conf import settings
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_notification_show_pop_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('sendToOther.notification', 'ارسال اعلان به سایر کاربران شرکت'),)},
        ),
        migrations.AddField(
            model_name='notification',
            name='has_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_status',
            field=models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='status',
            field=models.CharField(choices=[('p', 'در انتظار ارسال'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2),
        ),
    ]
