# Generated by Django 2.2 on 2021-06-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210623_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('send.notification', 'ارسال اعلان به سایر کاربران شرکت'),)},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': ()},
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('su', 'ارسال شده توسط کاربر'), ('sr', 'یاداور'), ('ss', 'ارسال شده توسط سامانه'), ('sa', 'ارسال شده توسط ادمین')], default='ss', max_length=2),
            preserve_default=False,
        ),
    ]
