# Generated by Django 2.2 on 2022-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210711_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
