# Generated by Django 2.0.5 on 2019-03-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_financial_year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='companies.FinancialYear'),
        ),
    ]
