# Generated by Django 2.0.5 on 2019-03-16 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user_management', '0002_auto_20190316_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='companies.Company')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='access',
            unique_together={('permission', 'company', 'user')},
        ),
    ]
