# Generated by Django 2.2 on 2021-12-27 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0029_auto_20210918_1228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0028_auto_20210918_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('province', models.CharField(max_length=50)),
                ('classification', models.CharField(choices=[('w', 'کالا'), ('spl', 'خدمات با فهرست بها'), ('npl', 'خدمات بدون فهرست بها'), ('c', 'مشاوره'), ('o', 'سایر')], default='o', max_length=3)),
                ('bidder', models.CharField(max_length=100)),
                ('bidder_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bidder_postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول کد پستی باید 10 رقم باشد', regex='^.{10}$')])),
                ('received_deadline', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('send_offer_deadline', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('opening_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('offer_expiration', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='transactions.Transaction')),
            ],
            options={
                'verbose_name': 'مناقصه',
                'ordering': ['-pk'],
                'permissions': (('get.tender', 'مشاهده مناقصه'), ('create.tender', 'تعریف مناقصه'), ('update.tender', 'ویرایش مناقصه'), ('delete.tender', 'حذف مناقصه'), ('getOwn.tender', 'مشاهده مناقصه خود'), ('updateOwn.tender', 'ویرایش مناقصه خود'), ('deleteOwn.tender', 'حذف مناقصه خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('contract_code', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('inception', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('discharge', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('max_change_amount', models.CharField(max_length=50)),
                ('submit_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('from_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('to_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('doing_job_well', models.IntegerField(blank=True, null=True)),
                ('insurance_payment', models.IntegerField(blank=True, null=True)),
                ('other', models.IntegerField(blank=True, null=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.Account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracting.Tender')),
                ('transAction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='transactions.Transaction')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'ordering': ['-pk'],
                'permissions': (('get.contract', 'مشاهده قرارداد'), ('create.contract', 'تعریف قرارداد'), ('update.contract', 'ویرایش قرارداد'), ('delete.contract', 'حذف قرارداد'), ('getOwn.contract', 'مشاهده قرارداد های خود'), ('updateOwn.contract', 'ویرایش قرارداد های خود'), ('deleteOwn.contract', 'حذف قرارداد های خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
