# Generated by Django 2.2 on 2021-12-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracting', '0003_auto_20211228_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
                ('type', models.CharField(choices=[('n', 'معمولی'), ('a', 'تعدیل'), ('td', 'تحویل موقت'), ('dd', 'تحویل قطعی')], default='n', max_length=3)),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('previous_statement_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('number', models.IntegerField()),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('present_statement_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement', to='contracting.Contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statement',
                'ordering': ['-pk'],
                'permissions': (('get.statement', 'مشاهده صورت وضعیت'), ('create.statement', 'تعریف صورت وضعیت'), ('update.statement', 'ویرایش صورت وضعیت'), ('delete.statement', 'حذف صورت وضعیت'), ('getOwn.statement', 'مشاهده صورت وضعیت های خود'), ('updateOwn.statement', 'ویرایش صورت وضعیت های خود'), ('deleteOwn.statement', 'حذف صورت وضعیت های خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
