# Generated by Django 2.2 on 2022-01-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0004_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='contract',
            name='max_change_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
