# Generated by Django 2.2 on 2022-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0005_auto_20220101_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
