# Generated by Django 2.2 on 2022-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0007_auto_20220102_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
