# Generated by Django 2.2 on 2022-01-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0008_tender_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='discharge',
            new_name='registration',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='submit_date',
        ),
    ]
