# Generated by Django 2.2 on 2022-01-08 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracting', '0009_auto_20220104_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('new_conteract_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('increase', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('code', models.IntegerField()),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplement', to='contracting.Contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplement',
                'ordering': ['-pk'],
                'permissions': (('get.supplement', 'مشاهده الحاقیه'), ('create.supplement', 'تعریف الحاقیه'), ('update.supplement', 'ویرایش الحاقیه'), ('delete.supplement', 'حذف الحاقیه'), ('getOwn.supplement', 'مشاهده الحاقیه های خود'), ('updateOwn.supplement', 'ویرایش الحاقیه های خود'), ('deleteOwn.supplement', 'حذف الحاقیه های خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
