# Generated by Django 2.2 on 2022-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0010_supplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='increase',
            field=models.BooleanField(default=True),
        ),
    ]
