# Generated by Django 2.2 on 2022-01-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0011_auto_20220110_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='contracting.Contract'),
        ),
    ]
