# Generated by Django 2.2 on 2022-01-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0012_auto_20220110_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='number',
            new_name='serial',
        ),
    ]
