# Generated by Django 2.2 on 2022-04-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0013_auto_20220110_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplement',
            old_name='new_conteract_date',
            new_name='new_contract_date',
        ),
    ]
