# Generated by Django 2.2 on 2022-04-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_auto_20210918_1233'),
        ('contracting', '0014_auto_20220407_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='transAction',
        ),
        migrations.AddField(
            model_name='contract',
            name='guarantee_document_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract2', to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='contract',
            name='received_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract1', to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='tender',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
