# Generated by Django 2.2 on 2022-04-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0015_auto_20220413_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='contracting.Contract'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='present_statement_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='previous_statement_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
    ]
