# Generated by Django 2.2 on 2022-07-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0022_tender_code2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='code2',
        ),
    ]
