# Generated by Django 2.2 on 2021-02-22 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0018_auto_20210104_1053'),
        ('accounts', '0021_auto_20210210_0948'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('from_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('to_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('percent', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_commissionrange', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('create.commissionRange', 'تعریف بازه تخفیف'), ('get.commissionRange', 'مشاهده بازه تخفیف'), ('update.commissionRange', 'ویرایش بازه تخفیف'), ('delete.commissionRange', 'حذف بازه تخفیف'), ('getOwn.commissionRange', 'مشاهده بازه های تخفیف خود'), ('updateOwn.commissionRange', 'ویرایش بازه های تخفیف خود'), ('deleteOwn.commissionRange', 'حذف بازه های تخفیف خود')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CommissionRangeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('from_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('to_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('percent', models.IntegerField()),
                ('commissionRange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='distributions.CommissionRange')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_commissionrangeitem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('level', models.IntegerField()),
                ('code', models.CharField(max_length=12, verbose_name='کد حساب')),
                ('explanation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('commission_percent', models.IntegerField()),
                ('fixed_commission', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Account')),
                ('commissionRange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='distributions.CommissionRange')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_visitor', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='distributions.Visitor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
                'permissions': (('create.visitor', 'تعریف ویزیتور'), ('get.visitor', 'مشاهده ویزیتور'), ('update.visitor', 'ویرایش ویزیتور'), ('delete.visitor', 'حذف ویزیتور'), ('getOwn.visitor', 'مشاهده ویزیتور های خود'), ('updateOwn.visitor', 'ویرایش ویزیتور های خود'), ('deleteOwn.visitor', 'حذف ویزیتور های خود')),
                'abstract': False,
                'default_permissions': (),
                'unique_together': {('financial_year', 'user', 'level')},
            },
        ),
    ]
