# Generated by Django 2.2 on 2021-02-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_auto_20210222_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionrange',
            name='from_value',
        ),
        migrations.RemoveField(
            model_name='commissionrange',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='commissionrange',
            name='to_value',
        ),
    ]
