# Generated by Django 2.2 on 2021-02-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0003_auto_20210222_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='commissionRange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='distributions.CommissionRange'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='commission_percent',
            field=models.IntegerField(default=0),
        ),
    ]
