# Generated by Django 2.2 on 2021-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0006_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='paths', to='distributions.Visitor'),
        ),
    ]
