# Generated by Django 2.2 on 2021-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0008_auto_20210226_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='path',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (('get.path', 'مشاهده مسیر ها'), ('create.path0', 'تعریف استان'), ('update.path0', 'ویرایش استان'), ('delete.path0', 'حذف استان'), ('create.path1', 'تعریف شهر'), ('update.path1', 'ویرایش شهر'), ('delete.path1', 'حذف شهر'), ('create.path2', 'تعریف منطقه'), ('update.path2', 'ویرایش منطقه'), ('delete.path2', 'حذف منطقه'), ('create.path3', 'تعریف محله'), ('update.path3', 'ویرایش محله'), ('delete.path3', 'حذف محله'), ('create.path4', 'تعریف خیابان'), ('update.path4', 'ویرایش خیابان'), ('delete.path4', 'حذف خیابان'), ('getOwn.path', 'مشاهده مسیر ها خود'), ('updateOwn.path0', 'ویرایش استان خود'), ('deleteOwn.path0', 'حذف استان خود'), ('updateOwn.path1', 'ویرایش شهر خود'), ('deleteOwn.path1', 'حذف شهر خود'), ('updateOwn.path2', 'ویرایش منطقه خود'), ('deleteOwn.path2', 'حذف منطقه خود'), ('updateOwn.path3', 'ویرایش محله خود'), ('deleteOwn.path3', 'حذف محله خود'), ('updateOwn.path4', 'ویرایش خیابان خود'), ('deleteOwn.path4', 'حذف خیابان خود'))},
        ),
        migrations.AlterField(
            model_name='visitor',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
