# Generated by Django 2.2 on 2021-02-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210227_1102'),
        ('distributions', '0009_auto_20210227_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionrange',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('create.commissionRange', 'تعریف بازه تخفیف'), ('get.commissionRange', 'مشاهده بازه تخفیف'), ('update.commissionRange', 'ویرایش بازه تخفیف'), ('delete.commissionRange', 'حذف بازه تخفیف'), ('getOwn.commissionRange', 'مشاهده بازه های تخفیف خود'), ('updateOwn.commissionRange', 'ویرایش بازه های تخفیف خود'), ('deleteOwn.commissionRange', 'حذف بازه های تخفیف خود'))},
        ),
        migrations.AlterModelOptions(
            name='commissionrangeitem',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='path',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['code'], 'permissions': (('get.path', 'مشاهده مسیر ها'), ('create.path0', 'تعریف استان'), ('update.path0', 'ویرایش استان'), ('delete.path0', 'حذف استان'), ('create.path1', 'تعریف شهر'), ('update.path1', 'ویرایش شهر'), ('delete.path1', 'حذف شهر'), ('create.path2', 'تعریف منطقه'), ('update.path2', 'ویرایش منطقه'), ('delete.path2', 'حذف منطقه'), ('create.path3', 'تعریف محله'), ('update.path3', 'ویرایش محله'), ('delete.path3', 'حذف محله'), ('create.path4', 'تعریف خیابان'), ('update.path4', 'ویرایش خیابان'), ('delete.path4', 'حذف خیابان'), ('getOwn.path', 'مشاهده مسیر ها خود'), ('updateOwn.path0', 'ویرایش استان خود'), ('deleteOwn.path0', 'حذف استان خود'), ('updateOwn.path1', 'ویرایش شهر خود'), ('deleteOwn.path1', 'حذف شهر خود'), ('updateOwn.path2', 'ویرایش منطقه خود'), ('deleteOwn.path2', 'حذف منطقه خود'), ('updateOwn.path3', 'ویرایش محله خود'), ('deleteOwn.path3', 'حذف محله خود'), ('updateOwn.path4', 'ویرایش خیابان خود'), ('deleteOwn.path4', 'حذف خیابان خود'))},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['code'], 'permissions': (('create.visitor', 'تعریف ویزیتور'), ('get.visitor', 'مشاهده ویزیتور'), ('update.visitor', 'ویرایش ویزیتور'), ('delete.visitor', 'حذف ویزیتور'), ('getOwn.visitor', 'مشاهده ویزیتور های خود'), ('updateOwn.visitor', 'ویرایش ویزیتور های خود'), ('deleteOwn.visitor', 'حذف ویزیتور های خود'))},
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='account',
        ),
        migrations.AddField(
            model_name='visitor',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.FloatAccount'),
        ),
    ]
