# Generated by Django 2.2 on 2021-02-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0010_auto_20210227_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='floatAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.FloatAccount'),
            preserve_default=False,
        ),
    ]
