# Generated by Django 2.2 on 2021-03-01 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20210301_1140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions', '0011_auto_20210227_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('car_number', models.CharField(max_length=11)),
                ('explanation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.car', 'مشاهده ماشین ها'), ('create.car', 'تعریف ماشین '), ('update.car', 'ویرایش ماشین '), ('delete.car', 'حذف ماشین ')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='commissionrange',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionrangeitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='path',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.driver', 'مشاهده راننده ها'), ('create.driver', 'تعریف راننده '), ('update.driver', 'ویرایش راننده '), ('delete.driver', 'حذف راننده ')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.distributor', 'مشاهده موزع ها'), ('create.distributor', 'تعریف موزع'), ('update.distributor', 'ویرایش موزع'), ('delete.distributor', 'حذف موزع')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('date', django_jalali.db.models.jDateField()),
                ('time', models.TimeField()),
                ('explanation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='distributions.Car')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='distributions.Distributor')),
                ('driver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='distributions.Driver')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.distribution', 'مشاهده توزیع ها'), ('create.distribution', 'تعریف توزیع '), ('update.distribution', 'ویرایش توزیع '), ('delete.distribution', 'حذف توزیع ')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='car',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='distributions.Distributor'),
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='distributions.Driver'),
        ),
        migrations.AddField(
            model_name='car',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear'),
        ),
    ]
