# Generated by Django 2.2 on 2021-03-01 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0020_auto_20210301_1140'),
        ('distributions', '0012_auto_20210301_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributor',
            unique_together={('financial_year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('financial_year', 'user')},
        ),
    ]
