# Generated by Django 2.2 on 2021-03-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0013_auto_20210301_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
