# Generated by Django 2.2 on 2021-03-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0014_distribution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='local_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
