# Generated by Django 2.2 on 2021-03-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0015_distribution_local_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('create.car', 'تعریف ماشین '), ('get.car', 'مشاهده ماشین ها'), ('update.car', 'ویرایش ماشین '), ('delete.car', 'حذف ماشین '), ('getOwn.car', 'مشاهده ماشین های خود'), ('updateOwn.car', 'ویرایش ماشین های خود'), ('deleteOwn.car', 'حذف ماشین های خود'))},
        ),
    ]
