# Generated by Django 2.2 on 2021-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210301_1140'),
        ('distributions', '0016_auto_20210310_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='defaultAccounts',
            field=models.ManyToManyField(related_name='visitors', to='accounts.DefaultAccount'),
        ),
    ]
