# Generated by Django 2.2 on 2021-04-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20210301_1140'),
        ('distributions', '0018_auto_20210316_1341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='path',
            unique_together={('financial_year', 'code')},
        ),
    ]
