# Generated by Django 2.2 on 2021-04-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0019_auto_20210413_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='distributions.Path'),
        ),
    ]
