# Generated by Django 2.2 on 2021-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sobhan_admin', '0002_auto_20201107_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': ()},
        ),
    ]
