# Generated by Django 2.2 on 2021-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobhan_admin', '0004_auto_20210301_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
