# Generated by Django 2.0.5 on 2019-03-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام حساب')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد حساب')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('bed', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('bes', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('max_bed', models.IntegerField(blank=True, null=True)),
                ('max_bes', models.IntegerField(blank=True, null=True)),
                ('max_bed_with_sanad', models.IntegerField(blank=True, null=True)),
                ('max_bes_with_sanad', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('level', models.IntegerField(choices=[(0, 'group'), (1, 'kol'), (2, 'moein'), (3, 'tafzili')])),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب ها',
                'ordering': ['code'],
                'permissions': (('create_account', 'تعریف حساب'), ('retrieve_account', 'مشاهده حساب'), ('update_account', 'ویرایش حساب'), ('delete_account', 'حذف حساب')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('programingName', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nature', models.CharField(choices=[('bed', 'بدهکار'), ('bes', 'بستانکار'), ('non', 'خنثی')], max_length=3)),
                ('usage', models.CharField(blank=True, choices=[('incomeStatement', 'سود و زیان'), ('balanceSheet', 'ترازنامه'), ('none', 'هیچ کدام')], max_length=30)),
            ],
            options={
                'verbose_name': 'نوع حساب',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'مرکز هزینه',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CostCenterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'گروه مرکز هزینه',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DefaultAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('usage', models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), (('factor',), 'فاکتور'), ('none', 'هیچ کدام')], max_length=20)),
                ('programingName', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'حساب پیشفرض',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FloatAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('max_bed', models.CharField(blank=True, max_length=20, null=True)),
                ('max_bes', models.CharField(blank=True, max_length=20, null=True)),
                ('max_bed_with_sanad', models.CharField(blank=True, max_length=20, null=True)),
                ('max_bes_with_sanad', models.CharField(blank=True, max_length=20, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'حساب شناور',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FloatAccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'گروه حساب شناور',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IndependentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'حساب مستقل',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bank', serialize=False, to='accounts.Account')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('branchCode', models.CharField(blank=True, max_length=20, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('sheba', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'حساب بانک',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to='accounts.Account')),
                ('personType', models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], max_length=5)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('meli_code', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('accountNumber1', models.CharField(blank=True, max_length=50, null=True)),
                ('accountNumber2', models.CharField(blank=True, max_length=50, null=True)),
                ('eghtesadiCode', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'حساب اشخاص',
                'verbose_name_plural': 'حساب های اشخاص',
                'permissions': (('create_buyer', 'تعریف حساب خریدار'), ('retrieve_buyer', 'مشاهده حساب خریدار'), ('update_buyer', 'ویرایش حساب خریدار'), ('delete_buyer', 'حذف حساب خریدار')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='floataccount',
            name='floatAccountGroups',
            field=models.ManyToManyField(related_name='floatAccounts', to='accounts.FloatAccountGroup'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defaultAccount', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costCenters', to='accounts.CostCenterGroup'),
        ),
        migrations.AddField(
            model_name='account',
            name='costCenterGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.CostCenterGroup'),
        ),
        migrations.AddField(
            model_name='account',
            name='floatAccountGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.FloatAccountGroup'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.AccountType'),
        ),
    ]
