# Generated by Django 2.2 on 2020-07-19 12:42

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models
import helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('p', 'اشخاص'), ('b', 'بانک'), ('o', 'دیگر')], default='o', max_length=2)),
                ('name', models.CharField(max_length=150, verbose_name='نام حساب')),
                ('code', models.CharField(max_length=50, verbose_name='کد حساب')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('max_bed', models.IntegerField(blank=True, null=True)),
                ('max_bes', models.IntegerField(blank=True, null=True)),
                ('max_bed_with_sanad', models.IntegerField(blank=True, null=True)),
                ('max_bes_with_sanad', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('level', models.IntegerField(choices=[(0, 'group'), (1, 'kol'), (2, 'moein'), (3, 'tafsili')])),
                ('is_real', models.BooleanField(default=True)),
                ('person_type', models.CharField(blank='true', choices=[('b', 'خریدار'), ('s', 'فروشنده')], default='', max_length=10)),
                ('phone_1', models.CharField(blank=True, default='', max_length=20)),
                ('phone_2', models.CharField(blank=True, default='', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول شماره موبایل باید 11 رقم باشد', regex='^.{11}$')])),
                ('melli_code', models.CharField(blank=True, max_length=10, null=True, validators=[helpers.models.is_valid_melli_code])),
                ('website', models.URLField(blank=True, default='')),
                ('fax', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('province', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول کد پستی باید 10 رقم باشد', regex='^.{10}$')])),
                ('account_number_1', models.CharField(blank=True, default='', max_length=50)),
                ('account_number_2', models.CharField(blank=True, default='', max_length=50)),
                ('eghtesadi_code', models.CharField(blank=True, default='', max_length=50)),
                ('branch_name', models.CharField(blank=True, default='', max_length=100)),
                ('branch_code', models.CharField(blank=True, default='', max_length=20)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('sheba', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'ordering': ['code'],
                'permissions': (('get.account', 'مشاهده حساب ها'), ('create.account0', 'تعریف گروه'), ('update.account0', 'ویرایش گروه'), ('delete.account0', 'حذف گروه'), ('create.account1', 'تعریف کل'), ('update.account1', 'ویرایش کل'), ('delete.account1', 'حذف کل'), ('create.account2', 'تعریف معین'), ('update.account2', 'ویرایش معین'), ('delete.account2', 'حذف معین'), ('create.account3', 'تعریف تفصیلی'), ('update.account3', 'ویرایش تفصیلی'), ('delete.account3', 'حذف تفصیلی')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('bed', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('bes', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nature', models.CharField(choices=[('bed', 'بدهکار'), ('bes', 'بستانکار'), ('non', 'خنثی')], max_length=3)),
                ('usage', models.CharField(blank=True, choices=[('incomeStatement', 'سود و زیان'), ('balanceSheet', 'ترازنامه'), ('none', 'هیچ کدام')], max_length=30)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DefaultAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('account_level', models.IntegerField(choices=[(0, 'group'), (1, 'kol'), (2, 'moein'), (3, 'tafsili')], default=3)),
                ('usage', models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), ('factor', 'فاکتور'), ('closeAccounts', 'بستن حساب ها'), ('imprest', 'تنخواه'), ('other', 'دیگر')], max_length=20)),
                ('codename', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.defaultAccount', 'مشاهده حساب های پیشفرض'), ('create.defaultAccount', 'تعریف حساب پیشفرض'), ('update.defaultAccount', 'ویرایش حساب پیشفرض'), ('delete.defaultAccount', 'حذف حساب پیشفرض')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FloatAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_cost_center', models.BooleanField(default=False)),
                ('max_bed', models.CharField(blank=True, max_length=20, null=True)),
                ('max_bes', models.CharField(blank=True, max_length=20, null=True)),
                ('max_bed_with_sanad', models.CharField(blank=True, max_length=20, null=True)),
                ('max_bes_with_sanad', models.CharField(blank=True, max_length=20, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.floatAccount', 'مشاهده حساب های شناور'), ('create.floatAccount', 'تعریف حساب شناور'), ('update.floatAccount', 'ویرایش حساب شناور'), ('delete.floatAccount', 'حذف حساب شناور')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FloatAccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_cost_center', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه'), ('create.floatAccountGroup', 'تعریف گروه حساب شناور / مرکز هزینه'), ('update.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه'), ('delete.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FloatAccountRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
