# Generated by Django 2.0.5 on 2018-06-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.CharField(choices=[('0', 'group'), ('1', 'kol'), ('2', 'moein'), ('3', 'tafzili')], max_length=8),
        ),
    ]
