# Generated by Django 2.0.5 on 2019-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bes',
        ),
        migrations.AlterField(
            model_name='defaultaccount',
            name='usage',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), ('factor', 'فاکتور'), ('none', 'هیچ کدام')], max_length=20),
        ),
    ]
