# Generated by Django 2.0.5 on 2018-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='account',
            name='bes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
    ]
