# Generated by Django 2.0.5 on 2018-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180911_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='explanation',
            new_name='programingName',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='type',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='nature',
            field=models.CharField(choices=[('BED', 'بدهکار'), ('BES', 'بستانکار')], default='ha', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد حساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام حساب'),
        ),
    ]
