# Generated by Django 2.2 on 2020-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200424_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccount',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
