# Generated by Django 2.0.5 on 2019-04-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_financialyear_is_active'),
        ('accounts', '0002_auto_20190321_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floataccount',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='float_accounts', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floataccountgroup',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='float_account_groups', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='independentaccount',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='independent_accounts', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
