# Generated by Django 2.0.5 on 2019-04-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_financialyear_is_active'),
        ('accounts', '0003_auto_20190404_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costcentergroup',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost_center_groups', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
