# Generated by Django 2.0.5 on 2018-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180922_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='nature',
            field=models.CharField(choices=[('bed', 'بدهکار'), ('bes', 'بستانکار')], max_length=3),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='programingName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
