# Generated by Django 2.2 on 2020-07-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200719_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floataccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.floatAccount', 'مشاهده حساب های شناور'), ('getOwn.floatAccount', 'مشاهده حساب های شناور خود'), ('create.floatAccount', 'تعریف حساب شناور'), ('update.floatAccount', 'ویرایش حساب شناور'), ('delete.floatAccount', 'حذف حساب شناور'))},
        ),
        migrations.AlterModelOptions(
            name='floataccountgroup',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه'), ('getOwn.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه خود'), ('create.floatAccountGroup', 'تعریف گروه حساب شناور / مرکز هزینه'), ('update.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه'), ('delete.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه'))},
        ),
    ]
