# Generated by Django 2.2 on 2020-06-14 09:57

import django.core.validators
from django.db import migrations, models
import helpers.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200530_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='melli_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[helpers.models.is_valid_melli_code]),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول شماره موبایل باید 11 رقم باشد', regex='^.{11}$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول کد پستی باید 10 رقم باشد', regex='^.{10}$')]),
        ),
    ]
