# Generated by Django 2.0.5 on 2018-06-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180615_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.AccountType'),
        ),
    ]
