# Generated by Django 2.0.5 on 2019-04-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_financialyear_is_active'),
        ('accounts', '0004_auto_20190404_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultaccount',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_accounts', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
