# Generated by Django 2.2 on 2020-07-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200720_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (('get.account', 'مشاهده حساب ها'), ('create.account0', 'تعریف گروه'), ('update.account0', 'ویرایش گروه'), ('delete.account0', 'حذف گروه'), ('create.account1', 'تعریف کل'), ('update.account1', 'ویرایش کل'), ('delete.account1', 'حذف کل'), ('create.account2', 'تعریف معین'), ('update.account2', 'ویرایش معین'), ('delete.account2', 'حذف معین'), ('create.account3', 'تعریف تفصیلی'), ('update.account3', 'ویرایش تفصیلی'), ('delete.account3', 'حذف تفصیلی'), ('getOwn.account', 'مشاهده حساب ها خود'), ('updateOwn.account0', 'ویرایش گروه خود'), ('deleteOwn.account0', 'حذف گروه خود'), ('updateOwn.account1', 'ویرایش کل خود'), ('deleteOwn.account1', 'حذف کل خود'), ('updateOwn.account2', 'ویرایش معین خود'), ('deleteOwn.account2', 'حذف معین خود'), ('updateOwn.account3', 'ویرایش تفصیلی خود'), ('deleteOwn.account3', 'حذف تفصیلی خود'))},
        ),
        migrations.AlterModelOptions(
            name='defaultaccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.defaultAccount', 'مشاهده حساب های پیشفرض'), ('create.defaultAccount', 'تعریف حساب پیشفرض'), ('update.defaultAccount', 'ویرایش حساب پیشفرض'), ('delete.defaultAccount', 'حذف حساب پیشفرض'), ('getOwn.defaultAccount', 'مشاهده حساب های پیشفرض خود'), ('updateOwn.defaultAccount', 'ویرایش حساب پیشفرض خود'), ('deleteOwn.defaultAccount', 'حذف حساب پیشفرض خود'))},
        ),
        migrations.AlterModelOptions(
            name='floataccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.floatAccount', 'مشاهده حساب های شناور'), ('create.floatAccount', 'تعریف حساب شناور'), ('update.floatAccount', 'ویرایش حساب شناور'), ('delete.floatAccount', 'حذف حساب شناور'), ('getOwn.floatAccount', 'مشاهده حساب های شناور خود'), ('updateOwn.floatAccount', 'ویرایش حساب شناور خود'), ('deleteOwn.floatAccount', 'حذف حساب شناور خود'))},
        ),
        migrations.AlterModelOptions(
            name='floataccountgroup',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه'), ('create.floatAccountGroup', 'تعریف گروه حساب شناور / مرکز هزینه'), ('update.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه'), ('delete.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه'), ('getOwn.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه خود'), ('updateOwn.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه خود'), ('deleteOwn.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه خود'))},
        ),
    ]
