# Generated by Django 2.2 on 2020-06-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200614_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultaccount',
            name='account_level',
            field=models.IntegerField(choices=[(0, 'group'), (1, 'kol'), (2, 'moein'), (3, 'tafsili')], default=3),
        ),
        migrations.AlterField(
            model_name='defaultaccount',
            name='usage',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), ('factor', 'فاکتور'), ('closeAccounts', 'بستن حساب ها'), ('none', 'دیگر')], max_length=20),
        ),
    ]
