# Generated by Django 2.0.5 on 2019-04-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_defaultaccount_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccount',
            name='usage',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), ('factor', 'فاکتور'), ('closeAccounts', 'بستن حساب ها'), ('none', 'هیچ کدام')], max_length=20),
        ),
    ]
