# Generated by Django 2.0.5 on 2018-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180615_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='floataccount',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
