# Generated by Django 2.2 on 2020-07-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200721_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='floataccount',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='floataccountgroup',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='floataccountrelation',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
    ]
