# Generated by Django 2.0.5 on 2018-09-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180923_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountType',
            new_name='type',
        ),
    ]
