# Generated by Django 2.2 on 2020-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200618_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='programingName',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='defaultaccount',
            old_name='programingName',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='defaultaccount',
            name='usage',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), ('factor', 'فاکتور'), ('closeAccounts', 'بستن حساب ها'), ('other', 'دیگر')], max_length=20),
        ),
    ]
