# Generated by Django 2.2 on 2020-07-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200618_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='nickname',
            new_name='codename',
        ),
        migrations.RenameField(
            model_name='defaultaccount',
            old_name='nickname',
            new_name='codename',
        ),
    ]
