# Generated by Django 2.0.5 on 2018-06-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180616_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floataccount',
            old_name='group',
            new_name='floatAccountGroup',
        ),
    ]
