# Generated by Django 2.0.5 on 2018-09-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180923_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='usage',
            field=models.CharField(blank=True, choices=[('incomeStatement', 'سود و زیان'), ('balanceSheet', 'ترازنامه')], max_length=30),
        ),
    ]
