# Generated by Django 2.0.5 on 2019-04-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_financialyear_is_active'),
        ('accounts', '0007_auto_20190409_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد حساب'),
        ),
        migrations.AlterField(
            model_name='floataccountgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('financial_year', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='floataccountgroup',
            unique_together={('financial_year', 'name')},
        ),
    ]
