# Generated by Django 2.2 on 2020-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200726_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_real',
        ),
        migrations.AddField(
            model_name='account',
            name='buyer_or_seller',
            field=models.CharField(blank=True, choices=[('b', 'خریدار'), ('s', 'فروشنده')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='person_type',
            field=models.CharField(blank=True, choices=[('r', 'حقیقی'), ('l', 'حقوقی'), ('c', 'پیمانکاران'), ('o', 'دیگر')], default='', max_length=10),
        ),
    ]
