# Generated by Django 2.0.5 on 2018-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accounttype_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personType',
            field=models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], default='real', max_length=5),
            preserve_default=False,
        ),
    ]
