# Generated by Django 2.0.5 on 2018-07-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_independentaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.CostCenter'),
        ),
        migrations.AlterField(
            model_name='account',
            name='floatAccountGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.FloatAccountGroup'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.AccountType'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costCenters', to='accounts.CostCenterGroup'),
        ),
        migrations.AlterField(
            model_name='floataccount',
            name='floatAccountGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floatAccounts', to='accounts.FloatAccountGroup'),
        ),
    ]
