# Generated by Django 2.0.5 on 2019-02-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_person_meli_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floataccount',
            name='floatAccountGroup',
        ),
        migrations.AddField(
            model_name='floataccount',
            name='floatAccountGroups',
            field=models.ManyToManyField(related_name='floatAccounts', to='accounts.FloatAccountGroup'),
        ),
    ]
