# Generated by Django 2.0.5 on 2019-04-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190409_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultaccount',
            name='financial_year',
        ),
    ]
