# Generated by Django 2.2 on 2020-08-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200809_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccount',
            name='usage',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), ('factor', 'فاکتور'), ('closeAccounts', 'بستن حساب ها'), ('imprest', 'تنخواه'), ('other', 'دیگر'), ('dashtbashi', 'دشتبشی')], max_length=20),
        ),
    ]
