# Generated by Django 2.0.5 on 2018-07-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180714_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='costCenter',
        ),
        migrations.AddField(
            model_name='account',
            name='costCenterGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.CostCenterGroup'),
        ),
    ]
