# Generated by Django 2.0.5 on 2018-07-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180716_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=20)),
                ('accountNumber1', models.CharField(max_length=50)),
                ('accountNumber2', models.CharField(max_length=50)),
                ('eghtesadiCode', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='accounts.Account')),
            ],
        ),
    ]
