# Generated by Django 2.2 on 2020-08-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200811_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floataccountgroup',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه و درآمد'), ('create.floatAccountGroup', 'تعریف گروه حساب شناور / مرکز هزینه و درآمد'), ('update.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه و درآمد'), ('delete.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه و درآمد'), ('getOwn.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه و درآمد خود'), ('updateOwn.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه و درآمد خود'), ('deleteOwn.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه و درآمد خود'))},
        ),
    ]
