# Generated by Django 2.0.5 on 2019-04-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_defaultaccount_financial_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatAccountRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='costcentergroup',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='defaultaccount',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='floataccount',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='floataccountgroup',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='independentaccount',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='floataccount',
            name='floatAccountGroups',
        ),
        migrations.AddField(
            model_name='floataccount',
            name='teams',
            field=models.ManyToManyField(related_name='floatAccounts', through='accounts.FloatAccountRelation', to='accounts.FloatAccountGroup'),
        ),
        migrations.AddField(
            model_name='floataccountrelation',
            name='floatAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.FloatAccountGroup'),
        ),
        migrations.AddField(
            model_name='floataccountrelation',
            name='floatAccountGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.FloatAccount'),
        ),
    ]
