# Generated by Django 2.0.5 on 2019-03-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190227_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='nature',
            field=models.CharField(choices=[('bed', 'بدهکار'), ('bes', 'بستانکار'), ('non', 'هیچ کدام')], max_length=3),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='usage',
            field=models.CharField(blank=True, choices=[('incomeStatement', 'سود و زیان'), ('balanceSheet', 'ترازنامه'), ('none', 'هیچ کدام')], max_length=30),
        ),
    ]
