# Generated by Django 2.0.5 on 2019-04-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190410_1641'),
    ]

    operations = []
