# Generated by Django 2.2 on 2020-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_superuser'),
        ('accounts', '0012_auto_20200901_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccount',
            name='codename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='defaultaccount',
            unique_together={('financial_year', 'codename')},
        ),
    ]
