# Generated by Django 2.0.5 on 2018-07-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180718_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person', to='accounts.Person'),
        ),
    ]
