# Generated by Django 2.0.5 on 2019-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_floataccount_floataccountgroups'),
    ]

    operations = []
