# Generated by Django 2.2 on 2019-04-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_floataccount_floataccountgroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floataccount',
            old_name='teams',
            new_name='floatAccountGroups',
        ),
        migrations.AlterField(
            model_name='floataccountrelation',
            name='floatAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='accounts.FloatAccountGroup'),
        ),
        migrations.AlterField(
            model_name='floataccountrelation',
            name='floatAccountGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='accounts.FloatAccount'),
        ),
    ]
