# Generated by Django 2.0.5 on 2018-07-18 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180718_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='person', to='accounts.Account'),
            preserve_default=False,
        ),
    ]
