# Generated by Django 2.2 on 2020-09-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200919_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='financial_year',
        ),
    ]
