# Generated by Django 2.0.5 on 2018-07-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180718_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='exp',
        ),
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], default='seller', max_length=10),
            preserve_default=False,
        ),
    ]
