# Generated by Django 2.2 on 2020-02-02 11:01

from django.db import migrations
from django.core.management import call_command


def loaddata():
    call_command('loaddata', 'fixtures/accounts.json', verbosity=0)
    call_command('loaddata', 'fixtures/companies.json', verbosity=0)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0015_auto_20190720_1703'),
    ]

    operations = [
    ]
