# Generated by Django 2.2 on 2020-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201001_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='defaultaccount',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.defaultAccount', 'مشاهده حساب های پیشفرض'), ('create.defaultAccount', 'تعریف حساب پیشفرض'), ('update.defaultAccount', 'ویرایش حساب پیشفرض'), ('delete.defaultAccount', 'حذف حساب پیشفرض'), ('getOwn.defaultAccount', 'مشاهده حساب های پیشفرض خود'), ('updateOwn.defaultAccount', 'ویرایش حساب پیشفرض خود'), ('deleteOwn.defaultAccount', 'حذف حساب پیشفرض خود'))},
        ),
        migrations.AlterModelOptions(
            name='floataccount',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.floatAccount', 'مشاهده حساب های شناور'), ('create.floatAccount', 'تعریف حساب شناور'), ('update.floatAccount', 'ویرایش حساب شناور'), ('delete.floatAccount', 'حذف حساب شناور'), ('getOwn.floatAccount', 'مشاهده حساب های شناور خود'), ('updateOwn.floatAccount', 'ویرایش حساب شناور خود'), ('deleteOwn.floatAccount', 'حذف حساب شناور خود'))},
        ),
        migrations.AlterModelOptions(
            name='floataccountgroup',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه و درآمد'), ('create.floatAccountGroup', 'تعریف گروه حساب شناور / مرکز هزینه و درآمد'), ('update.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه و درآمد'), ('delete.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه و درآمد'), ('getOwn.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه و درآمد خود'), ('updateOwn.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه و درآمد خود'), ('deleteOwn.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه و درآمد خود'))},
        ),
        migrations.AlterModelOptions(
            name='floataccountrelation',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': ()},
        ),
    ]
