# Generated by Django 2.2 on 2020-12-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201107_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='accounts.Account'),
        ),
    ]
