# Generated by Django 2.0.5 on 2018-07-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180725_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bank', serialize=False, to='accounts.Account')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('branchCode', models.CharField(blank=True, max_length=20, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('sheba', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
