# Generated by Django 2.0.5 on 2018-08-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('usage', models.CharField(choices=[('receive', 'receive'), ('payment', 'payment'), ('both', 'both')], max_length=20)),
                ('programingName', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defaultAccount', to='accounts.Account')),
            ],
        ),
    ]
