# Generated by Django 2.2 on 2020-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200215_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='account',
            name='bes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
    ]
