# Generated by Django 2.0.5 on 2018-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_defaultaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccount',
            name='usage',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), ('factor', 'فاکتور')], max_length=20),
        ),
    ]
