# Generated by Django 2.2 on 2020-03-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200225_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'default_permissions': (), 'ordering': ['pk'], 'verbose_name': 'نوع حساب'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'default_permissions': (), 'ordering': ['pk'], 'verbose_name': 'حساب بانک'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'default_permissions': (), 'ordering': ['pk'], 'verbose_name': 'مرکز هزینه'},
        ),
        migrations.AlterModelOptions(
            name='costcentergroup',
            options={'default_permissions': (), 'ordering': ['pk'], 'verbose_name': 'گروه مرکز هزینه'},
        ),
        migrations.AlterModelOptions(
            name='defaultaccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'verbose_name': 'حساب پیشفرض'},
        ),
        migrations.AlterModelOptions(
            name='floataccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'verbose_name': 'حساب شناور'},
        ),
        migrations.AlterModelOptions(
            name='floataccountgroup',
            options={'default_permissions': (), 'ordering': ['pk'], 'verbose_name': 'گروه حساب شناور'},
        ),
        migrations.AlterModelOptions(
            name='floataccountrelation',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='independentaccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'verbose_name': 'حساب مستقل'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('create_buyer', 'تعریف حساب خریدار'), ('retrieve_buyer', 'مشاهده حساب خریدار'), ('update_buyer', 'ویرایش حساب خریدار'), ('delete_buyer', 'حذف حساب خریدار')), 'verbose_name': 'حساب اشخاص', 'verbose_name_plural': 'حساب های اشخاص'},
        ),
    ]
