# Generated by Django 2.2 on 2021-02-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210207_0926'),
        ('accounts', '0019_account_defaultsalepricetype'),
    ]

    operations = [
    ]
