# Generated by Django 2.2 on 2020-03-07 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200307_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultaccount',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defaultAccounts', to='accounts.FloatAccount'),
        ),
    ]
