# Generated by Django 2.2 on 2020-03-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_defaultaccount_floataccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floataccountrelation',
            name='floatAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='accounts.FloatAccount'),
        ),
        migrations.AlterField(
            model_name='floataccountrelation',
            name='floatAccountGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='accounts.FloatAccountGroup'),
        ),
    ]
