# Generated by Django 2.2 on 2021-02-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0006_path'),
        ('accounts', '0021_auto_20210210_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='distributions.Path'),
        ),
    ]
