# Generated by Django 2.2 on 2020-03-09 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20200309_0739'),
        ('sanads', '0011_auto_20200309_0739'),
        ('accounts', '0021_auto_20200307_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='group',
        ),
        migrations.DeleteModel(
            name='IndependentAccount',
        ),
        migrations.RemoveField(
            model_name='person',
            name='account',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='floataccount',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='floataccountgroup',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='account_number_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='account_number_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('p', 'اشخاص'), ('b', 'بانک'), ('o', 'دیگر')], default='o', max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='branchCode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='eghtesadi_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='is_real',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='melli_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='person_type',
            field=models.CharField(choices=[('buyer', 'b'), ('seller', 's')], default='b', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='sheba',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='floataccount',
            name='is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='floataccountgroup',
            name='is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='costCenterGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsAsCostCenter', to='accounts.FloatAccountGroup'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='CostCenter',
        ),
        migrations.DeleteModel(
            name='CostCenterGroup',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
