# Generated by Django 2.2 on 2020-03-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200309_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floataccount',
            old_name='is_independent',
            new_name='is_cost_center',
        ),
        migrations.RenameField(
            model_name='floataccountgroup',
            old_name='is_independent',
            new_name='is_cost_center',
        ),
    ]
