# Generated by Django 2.2 on 2021-03-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210227_1110'),
        ('accounts', '0023_auto_20210227_1102'),
    ]

    operations = [
    ]
