# Generated by Django 2.2 on 2020-03-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200309_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountNumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='branchCode',
            new_name='branch_code',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='branch',
            new_name='branch_name',
        ),
    ]
