# Generated by Django 2.2 on 2020-03-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200309_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='address2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='phone1',
            new_name='phone_1',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='phone2',
            new_name='phone_2',
        ),
    ]
