# Generated by Django 2.2 on 2021-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210404_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccount',
            name='usage',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('receiveAndPayment', 'دریافت و پرداخت'), ('factor', 'فاکتور'), ('closeAccounts', 'بستن حساب ها'), ('imprest', 'تنخواه'), ('other', 'دیگر'), ('dashtbashi', 'دشتبشی'), ('costAccounting', 'بهای تمام شده')], max_length=20),
        ),
    ]
