# Generated by Django 2.2 on 2020-03-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200309_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='person_type',
            field=models.CharField(blank='true', choices=[('b', 'خریدار'), ('s', 'فروشنده')], default='', max_length=10),
        ),
    ]
