# Generated by Django 2.2 on 2021-09-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210601_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccount',
            name='usage',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('guarantee', 'اسناد ضمانتی'), ('factor', 'فاکتور'), ('closeAccounts', 'بستن حساب ها'), ('imprest', 'تنخواه'), ('other', 'دیگر'), ('dashtbashi', 'دشتبشی'), ('costAccounting', 'بهای تمام شده')], max_length=20),
        ),
    ]
