# Generated by Django 2.2 on 2020-03-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_account_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultaccount',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defaultAccountsAsCostCenter', to='accounts.FloatAccount'),
        ),
    ]
