# Generated by Django 2.2 on 2020-03-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_defaultaccount_costcenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bes',
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('bes', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance', to='accounts.Account')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balanceAsCostCenter', to='accounts.FloatAccount')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='accounts.FloatAccount')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
