# Generated by Django 2.2 on 2020-03-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_auto_20200316_1336'),
        ('accounts', '0031_auto_20200314_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultaccount',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='financialYear', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
