# Generated by Django 2.2 on 2020-04-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200422_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (('get.account', 'مشاهده حساب ها'), ('create.account', 'تعریف حساب'), ('update.account', 'ویرایش حساب'), ('delete.account', 'حذف حساب'))},
        ),
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='defaultaccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (), 'verbose_name': 'حساب پیشفرض'},
        ),
        migrations.AlterModelOptions(
            name='floataccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.floatAccount', 'مشاهده حساب های شناور'), ('create.floatAccount', 'تعریف حساب شناور'), ('update.floatAccount', 'ویرایش حساب شناور'), ('delete.floatAccount', 'حذف حساب شناور'))},
        ),
        migrations.AlterModelOptions(
            name='floataccountgroup',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.floatAccountGroup', 'مشاهده گروه های حساب شناور / مرکز هزینه'), ('create.floatAccountGroup', 'تعریف گروه حساب شناور / مرکز هزینه'), ('update.floatAccountGroup', 'ویرایش گروه حساب شناور / مرکز هزینه'), ('delete.floatAccountGroup', 'حذف گروه حساب شناور / مرکز هزینه'))},
        ),
        migrations.AlterModelOptions(
            name='floataccountrelation',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
    ]
