# Generated by Django 2.2 on 2020-04-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200422_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (('get.account', 'مشاهده حساب ها'), ('create.account0', 'تعریف گروه'), ('update.account0', 'ویرایش گروه'), ('delete.account0', 'حذف گروه'), ('create.account1', 'تعریف کل'), ('update.account1', 'ویرایش کل'), ('delete.account1', 'حذف کل'), ('create.account2', 'تعریف معین'), ('update.account2', 'ویرایش معین'), ('delete.account2', 'حذف معین'), ('create.account3', 'تعریف تفصیلی'), ('update.account3', 'ویرایش تفصیلی'), ('delete.account3', 'حذف تفصیلی'))},
        ),
        migrations.AlterModelOptions(
            name='defaultaccount',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.defaultAccount', 'مشاهده حساب های پیشفرض'), ('create.defaultAccount', 'تعریف حساب پیشفرض'), ('update.defaultAccount', 'ویرایش حساب پیشفرض'), ('delete.defaultAccount', 'حذف حساب پیشفرض'))},
        ),
    ]
