# Generated by Django 2.2 on 2020-07-19 12:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_jalali.db.models
import factors.models
from helpers.db import get_empty_array


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش')], max_length=10)),
                ('explanation', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.expense', 'مشاهده هزینه فاکتور'), ('create.expense', 'تعریف هزینه  فاکتور'), ('update.expense', 'ویرایش هزینه فاکتور'), ('delete.expense', 'حذف هزینه فاکتور')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش'), ('backFromBuy', 'بازگشت از خرید'), ('backFromSale', 'بازگشت از فروش'), ('fpi', 'موجودی اول دوره'), ('it', 'وارده از انتقال'), ('ot', 'صادره با انتقال')], max_length=15)),
                ('paidValue', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('bijak', models.IntegerField(blank=True, null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('time', models.TimeField()),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('discountValue', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True)),
                ('discountPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('taxValue', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True)),
                ('taxPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('is_definite', models.BooleanField(default=0)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.buyFactor', 'مشاهده فاکتور خرید'), ('create.buyFactor', 'تعریف فاکتور خرید'), ('update.buyFactor', 'ویرایش فاکتور خرید'), ('delete.buyFactor', 'حذف فاکتور خرید'), ('definite.buyFactor', 'قطعی کردن خرید'), ('get.saleFactor', 'مشاهده فاکتور فروش'), ('create.saleFactor', 'تعریف فاکتور فروش'), ('update.saleFactor', 'ویرایش فاکتور فروش'), ('delete.saleFactor', 'حذف فاکتور فروش'), ('definite.saleFactor', 'قطعی کردن فروش'), ('get.backFromSaleFactor', 'مشاهده فاکتور برگشت از فروش'), ('create.backFromSaleFactor', 'تعریف فاکتور برگشت از فروش'), ('update.backFromSaleFactor', 'ویرایش فاکتور برگشت از فروش'), ('delete.backFromSaleFactor', 'حذف فاکتور برگشت از فروش'), ('definite.backFromSaleFactor', 'قطعی کردن برگشت از فروش'), ('get.backFromBuyFactor', 'مشاهده فاکتور برگشت از خرید'), ('create.backFromBuyFactor', 'تعریف فاکتور برگشت از خرید'), ('update.backFromBuyFactor', 'ویرایش فاکتور برگشت از خرید'), ('delete.backFromBuyFactor', 'حذف فاکتور برگشت از خرید'), ('definite.backFromBuyFactor', 'قطعی کردن برگشت از خرید'), ('get.notPaidFactor', 'مشاهده فاکتور های پرداخت نشده'), ('get.notReceivedFactor', 'مشاهده فاکتور های دریافت نشده'), ('get.firstPeriodInventory', 'مشاهده موجودی اول دوره'), ('update.firstPeriodInventory', 'ثبت موجودی اول دوره')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('value', models.DecimalField(decimal_places=0, max_digits=24)),
                ('explanation', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('count', models.DecimalField(decimal_places=6, max_digits=24)),
                ('fee', models.DecimalField(decimal_places=0, max_digits=24)),
                ('fees', django.contrib.postgres.fields.jsonb.JSONField(default=get_empty_array)),
                ('remain_fees', django.contrib.postgres.fields.jsonb.JSONField(default=get_empty_array)),
                ('discountValue', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True)),
                ('discountPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('calculated_output_value', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('value', models.DecimalField(decimal_places=0, max_digits=24)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date', django_jalali.db.models.jDateField()),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('explanation', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.transfer', 'مشاهده انتقال'), ('create.transfer', 'تعریف انتقال'), ('update.transfer', 'ویرایش انتقال'), ('delete.transfer', 'حذف انتقال')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
