# Generated by Django 2.0.5 on 2018-08-17 11:30

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wares', '0046_auto_20180817_1600'),
        ('accounts', '0017_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('date', django_jalali.db.models.jDateField()),
                ('time', models.TimeField(blank=True)),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('discountValue', models.IntegerField(blank=True, default=0, null=True)),
                ('discountPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('taxValue', models.IntegerField(blank=True, default=0, null=True)),
                ('taxPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='accounts.Account')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='accounts.FloatAccount')),
            ],
        ),
        migrations.CreateModel(
            name='FactorExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpense', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('discountValue', models.IntegerField(blank=True, default=0, null=True)),
                ('discountPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorItems', to='wares.Ware')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorItems', to='wares.Warehouse')),
            ],
        ),
    ]
