# Generated by Django 2.2 on 2020-04-24 08:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import factors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wares', '0001_initial'),
        ('sanads', '0001_initial'),
        ('companies', '0002_auto_20200424_1256'),
        ('transactions', '0001_initial'),
        ('accounts', '0002_auto_20200424_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش')], max_length=10)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpense', to='accounts.Account')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenseAsCostCenter', to='accounts.FloatAccount')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.FinancialYear')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpense', to='accounts.FloatAccount')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.expense', 'مشاهده هزینه فاکتور'), ('create.expense', 'تعریف هزینه  فاکتور'), ('update.expense', 'ویرایش هزینه فاکتور'), ('delete.expense', 'حذف هزینه فاکتور')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش'), ('backFromBuy', 'بازگشت از خرید'), ('backFromSale', 'بازگشت از فروش'), ('fpi', 'موجودی اول دوره'), ('it', 'وارده از انتقال'), ('ot', 'صادره با انتقال')], max_length=15)),
                ('paidValue', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('bijak', models.IntegerField(blank=True, null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('time', models.TimeField(auto_now=True)),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('discountValue', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True)),
                ('discountPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('taxValue', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True)),
                ('taxPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('is_definite', models.BooleanField(default=0)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='accounts.Account')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorsAsCostCenter', to='accounts.FloatAccount')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='companies.FinancialYear')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='accounts.FloatAccount')),
                ('sanad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='sanads.Sanad')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.buyFactor', 'مشاهده فاکتور خرید'), ('create.buyFactor', 'تعریف فاکتور خرید'), ('update.buyFactor', 'ویرایش فاکتور خرید'), ('delete.buyFactor', 'حذف فاکتور خرید'), ('definite.buyFactor', 'قطعی کردن خرید'), ('get.saleFactor', 'مشاهده فاکتور فروش'), ('create.saleFactor', 'تعریف فاکتور فروش'), ('update.saleFactor', 'ویرایش فاکتور فروش'), ('delete.saleFactor', 'حذف فاکتور فروش'), ('definite.saleFactor', 'قطعی کردن فروش'), ('get.backFromSaleFactor', 'مشاهده فاکتور برگشت از فروش'), ('create.backFromSaleFactor', 'تعریف فاکتور برگشت از فروش'), ('update.backFromSaleFactor', 'ویرایش فاکتور برگشت از فروش'), ('delete.backFromSaleFactor', 'حذف فاکتور برگشت از فروش'), ('definite.backFromSaleFactor', 'قطعی کردن برگشت از فروش'), ('get.backFromBuyFactor', 'مشاهده فاکتور برگشت از خرید'), ('create.backFromBuyFactor', 'تعریف فاکتور برگشت از خرید'), ('update.backFromBuyFactor', 'ویرایش فاکتور برگشت از خرید'), ('delete.backFromBuyFactor', 'حذف فاکتور برگشت از خرید'), ('definite.backFromBuyFactor', 'قطعی کردن برگشت از خرید'), ('get.notPaidFactor', 'مشاهده فاکتور های پرداخت نشده'), ('get.notReceivedFactor', 'مشاهده فاکتور های دریافت نشده'), ('get.firstPeriodInventory', 'مشاهده موجودی اول دوره'), ('update.firstPeriodInventory', 'ثبت موجودی اول دوره')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date', django_jalali.db.models.jDateField()),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='companies.FinancialYear')),
                ('input_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_transfer', to='factors.Factor')),
                ('output_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_transfer', to='factors.Factor')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.transfer', 'مشاهده انتقال'), ('create.transfer', 'تعریف انتقال'), ('update.transfer', 'ویرایش انتقال'), ('delete.transfer', 'حذف انتقال')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=6, max_digits=24)),
                ('fee', models.DecimalField(decimal_places=0, max_digits=24)),
                ('fees', django.contrib.postgres.fields.jsonb.JSONField(default=factors.models.get_empty_array)),
                ('remain_fees', django.contrib.postgres.fields.jsonb.JSONField(default=factors.models.get_empty_array)),
                ('discountValue', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True)),
                ('discountPercent', models.IntegerField(blank=True, default=0, null=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('calculated_output_value', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='factors.Factor')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_items', to='companies.FinancialYear')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorItems', to='wares.Ware')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorItems', to='wares.Warehouse')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=24)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='accounts.Account')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpensesAsCostCenter', to='accounts.FloatAccount')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='factors.Expense')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='factors.Factor')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_expenses', to='companies.FinancialYear')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='accounts.FloatAccount')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=24)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='factors.Factor')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_payments', to='companies.FinancialYear')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.Transaction')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
                'unique_together': {('factor', 'transaction')},
            },
        ),
    ]
