# Generated by Django 2.0.5 on 2019-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoritem',
            name='explanation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
