# Generated by Django 2.2 on 2020-07-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20200719_1712'),
        ('sanads', '0001_initial'),
        ('accounts', '0002_auto_20200719_1712'),
        ('wares', '0001_initial'),
        ('transactions', '0001_initial'),
        ('factors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='input_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_transfer', to='factors.Factor'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='output_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_transfer', to='factors.Factor'),
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='factors.Factor'),
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_payments', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='factors.Factor'),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_items', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorItems', to='wares.Ware'),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorItems', to='wares.Warehouse'),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpensesAsCostCenter', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='factors.Expense'),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='factors.Factor'),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_expenses', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='factor',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='factor',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorsAsCostCenter', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='factor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factor',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='factor',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='factor',
            name='sanad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='sanads.Sanad'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpense', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenseAsCostCenter', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='expense',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpense', to='accounts.FloatAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='factorpayment',
            unique_together={('factor', 'transaction')},
        ),
    ]
