# Generated by Django 2.0.5 on 2018-08-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_defaultaccount'),
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactorExpense',
            new_name='Expense',
        ),
    ]
