# Generated by Django 2.0.5 on 2019-04-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش'), ('backFromBuy', 'بازگشت از خرید'), ('backFromSale', 'بازگشت از فروش'), ('fpi', 'موجودی اول دوره')], max_length=15),
        ),
    ]
