# Generated by Django 2.0.5 on 2018-09-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0002_auto_20180922_1302'),
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=24)),
            ],
        ),
        migrations.AddField(
            model_name='factor',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='factors.Factor'),
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sanads.Transaction'),
        ),
    ]
