# Generated by Django 2.0.5 on 2018-08-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_defaultaccount'),
        ('factors', '0002_auto_20180818_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='accounts.Account')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش')], default='buy', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='factors.Expense'),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='factors.Factor'),
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpenses', to='accounts.FloatAccount'),
        ),
    ]
