# Generated by Django 2.0.5 on 2019-04-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_auto_20190404_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factorexpense',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factoritem',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='receiptitem',
            options={'default_permissions': ()},
        ),
    ]
