# Generated by Django 2.0.5 on 2018-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_auto_20180924_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='isPaid',
        ),
        migrations.AddField(
            model_name='factor',
            name='paidValue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
    ]
