# Generated by Django 2.2 on 2020-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_auto_20200609_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='time',
            field=models.TimeField(),
        ),
    ]
