# Generated by Django 2.0.5 on 2019-04-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_financialyear_is_active'),
        ('factors', '0003_auto_20190404_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='ware',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='warehouse',
        ),
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factorpayment',
            options={'default_permissions': ()},
        ),
        migrations.RemoveField(
            model_name='factor',
            name='receipt',
        ),
        migrations.AddField(
            model_name='expense',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factor',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factorexpense',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factor_expenses', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factoritem',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factor_items', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factorpayment',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factor_payments', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='factorexpense',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_expenses', to='factors.Factor'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptItem',
        ),
    ]
