# Generated by Django 2.0.5 on 2018-08-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0003_auto_20180820_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorexpense',
            name='explanation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
