# Generated by Django 2.0.5 on 2018-10-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0002_auto_20180922_1302'),
        ('factors', '0003_auto_20181004_0940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factorpayment',
            unique_together={('factor', 'transaction')},
        ),
    ]
