# Generated by Django 2.2 on 2020-07-25 05:40

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0004_auto_20200721_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True),
        ),
    ]
