# Generated by Django 2.0.5 on 2018-10-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0004_auto_20181007_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='sanad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='sanads.Sanad'),
        ),
    ]
