# Generated by Django 2.0.5 on 2018-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0004_factorexpense_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='discountValue',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='taxValue',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='factorexpense',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=24),
        ),
    ]
