# Generated by Django 2.0.5 on 2018-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0005_auto_20180821_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='discountValue',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='fee',
            field=models.DecimalField(decimal_places=0, max_digits=24),
        ),
    ]
