# Generated by Django 2.0.5 on 2018-08-21 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0018_auto_20180817_1647'),
        ('factors', '0006_auto_20180821_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='sanad',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='sanads.Sanad'),
            preserve_default=False,
        ),
    ]
