# Generated by Django 2.0.5 on 2019-04-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0006_auto_20190409_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='factorexpense',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='factoritem',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='factorpayment',
            name='source_id',
        ),
    ]
