# Generated by Django 2.2 on 2019-04-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0007_auto_20190410_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='is_definite',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='calculated_output_value',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='remain_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='remain_value',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True),
        ),
    ]
