# Generated by Django 2.0.5 on 2018-08-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0007_factor_sanad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='sanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='sanads.Sanad'),
        ),
    ]
