# Generated by Django 2.2 on 2019-04-23 06:28

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0008_auto_20190422_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='definition_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
