# Generated by Django 2.0.5 on 2018-08-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0008_auto_20180821_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='wareHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='wares.Warehouse'),
        ),
    ]
