# Generated by Django 2.2 on 2020-07-29 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factors', '0008_auto_20200726_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.buyFactor', 'مشاهده فاکتور خرید'), ('create.buyFactor', 'تعریف فاکتور خرید'), ('update.buyFactor', 'ویرایش فاکتور خرید'), ('delete.buyFactor', 'حذف فاکتور خرید'), ('definite.buyFactor', 'قطعی کردن خرید'), ('get.saleFactor', 'مشاهده فاکتور فروش'), ('create.saleFactor', 'تعریف فاکتور فروش'), ('update.saleFactor', 'ویرایش فاکتور فروش'), ('delete.saleFactor', 'حذف فاکتور فروش'), ('definite.saleFactor', 'قطعی کردن فروش'), ('get.backFromSaleFactor', 'مشاهده فاکتور برگشت از فروش'), ('create.backFromSaleFactor', 'تعریف فاکتور برگشت از فروش'), ('update.backFromSaleFactor', 'ویرایش فاکتور برگشت از فروش'), ('delete.backFromSaleFactor', 'حذف فاکتور برگشت از فروش'), ('definite.backFromSaleFactor', 'قطعی کردن برگشت از فروش'), ('get.backFromBuyFactor', 'مشاهده فاکتور برگشت از خرید'), ('create.backFromBuyFactor', 'تعریف فاکتور برگشت از خرید'), ('update.backFromBuyFactor', 'ویرایش فاکتور برگشت از خرید'), ('delete.backFromBuyFactor', 'حذف فاکتور برگشت از خرید'), ('definite.backFromBuyFactor', 'قطعی کردن برگشت از خرید'), ('get.notPaidFactor', 'مشاهده فاکتور های پرداخت نشده'), ('get.notReceivedFactor', 'مشاهده فاکتور های دریافت نشده'), ('getOwn.buyFactor', 'مشاهده فاکتور خرید خود'), ('updateOwn.buyFactor', 'ویرایش فاکتور های خرید خود'), ('deleteOwn.buyFactor', 'حذف فاکتور های خرید خود'), ('definiteOwn.buyFactor', 'قطعی کردن فاکتور های خرید خود'), ('getOwn.saleFactor', 'مشاهده فاکتور های فروش خود'), ('updateOwn.saleFactor', 'ویرایش فاکتور های فروش خود'), ('deleteOwn.saleFactor', 'حذف فاکتور های فروش خود'), ('definiteOwn.saleFactor', 'قطعی کردن فاکتور های فروش خود'), ('getOwn.backFromSaleFactor', 'مشاهده فاکتور های برگشت از فروش خود'), ('updateOwn.backFromSaleFactor', 'ویرایش فاکتور های برگشت از فروش خود'), ('deleteOwn.backFromSaleFactor', 'حذف فاکتور های برگشت از فروش خود'), ('definiteOwn.backFromSaleFactor', 'قطعی کردن فاکتور های برگشت از فروش خود'), ('getOwn.backFromBuyFactor', 'مشاهده فاکتور های برگشت از خرید خود'), ('updateOwn.backFromBuyFactor', 'ویرایش فاکتور های برگشت از خرید خود'), ('deleteOwn.backFromBuyFactor', 'حذف فاکتور های برگشت از خرید خود'), ('definiteOwn.backFromBuyFactor', 'قطعی کردن فاکتور های برگشت از خرید خود'), ('getOwn.notPaidFactor', 'مشاهده فاکتور های پرداخت نشده خود'), ('getOwn.notReceivedFactor', 'مشاهده فاکتور های دریافت نشده خود'), ('get.firstPeriodInventory', 'مشاهده موجودی اول دوره'), ('update.firstPeriodInventory', 'ثبت موجودی اول دوره'), ('firstConfirm.buyFactor', 'تایید اول فاکتور خرید '), ('secondConfirm.buyFactor', 'تایید دوم فاکتور خرید '), ('firstConfirmOwn.buyFactor', 'تایید اول فاکتور های خرید خود'), ('secondConfirmOwn.buyFactor', 'تایید دوم فاکتور های خرید خود'), ('firstConfirm.saleFactor', 'تایید اول فاکتور فروش '), ('secondConfirm.saleFactor', 'تایید دوم فاکتور فروش '), ('firstConfirmOwn.saleFactor', 'تایید اول فاکتور های فروش خود'), ('secondConfirmOwn.saleFactor', 'تایید دوم فاکتور های فروش خود'), ('firstConfirm.backFromBuyFactor', 'تایید اول فاکتور برگشت از خرید'), ('secondConfirm.backFromBuyFactor', 'تایید دوم فاکتور برگشت از خرید'), ('firstConfirmOwn.backFromBuyFactor', 'تایید اول فاکتور های برگشت از خرید خود'), ('secondConfirmOwn.backFromBuyFactor', 'تایید دوم فاکتور های برگشت از خرید خود'), ('firstConfirm.backFromSaleFromSaleFactor', 'تایید اول فاکتور برگشت از فروش '), ('secondConfirm.backFromSaleFromSaleFactor', 'تایید دوم فاکتور برگشت از فروش '), ('firstConfirmOwn.backFromSaleFromSaleFactor', 'تایید اول فاکتور های برگشت از فروش خود'), ('secondConfirmOwn.backFromSaleFromSaleFactor', 'تایید دوم فاکتور های برگشت از فروش خود'))},
        ),
        migrations.AddField(
            model_name='factor',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='first_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_factorConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factor',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='second_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_factorConfirmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
