# Generated by Django 2.2 on 2020-08-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0009_auto_20200729_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='has_tax',
            field=models.BooleanField(default=False),
        ),
    ]
