# Generated by Django 2.0.5 on 2018-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0010_auto_20180821_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='discountSum',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='taxSum',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=24, null=True),
        ),
    ]
