# Generated by Django 2.2 on 2019-04-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0010_factor_definite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='definite_code',
        ),
        migrations.AlterField(
            model_name='factor',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
