# Generated by Django 2.2 on 2020-08-31 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0012_auto_20200827_0941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0010_auto_20200816_1535'),
        ('factors', '0010_factor_has_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش'), ('backFromBuy', 'بازگشت از خرید'), ('backFromSale', 'بازگشت از فروش'), ('fpi', 'موجودی اول دوره'), ('it', 'وارده از انتقال'), ('ot', 'صادره با انتقال'), ('ia', 'رسید تعدیل انبار'), ('oa', 'حواله تعدیل انبار')], max_length=15),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
                ('date', django_jalali.db.models.jDateField()),
                ('type', models.CharField(choices=[('ia', 'رسید تعدیل انبار'), ('oa', 'حواله تعدیل انبار')], max_length=2)),
                ('explanation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='factors.Factor')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
                ('sanad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='sanads.Sanad')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.adjustment', 'مشاهده تعدیل '), ('create.adjustment', 'تعریف تعدیل '), ('update.adjustment', 'ویرایش تعدیل '), ('delete.adjustment', 'حذف تعدیل '), ('getOwn.adjustment', 'مشاهده تعدیل های خود'), ('updateOwn.adjustment', 'ویرایش تعدیل های خود'), ('deleteOwn.adjustment', 'حذف تعدیل های خود')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
