# Generated by Django 2.2 on 2020-09-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0011_auto_20200831_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factoritem',
            old_name='calculated_output_value',
            new_name='calculated_value',
        ),
    ]
