# Generated by Django 2.2 on 2019-04-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0011_auto_20190426_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='remain_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
