# Generated by Django 2.0.5 on 2018-08-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0011_auto_20180822_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='discountSum',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='taxSum',
        ),
    ]
