# Generated by Django 2.0.5 on 2018-08-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0012_auto_20180822_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش'), ('backFromBuy', 'بازگشت از خرید'), ('backFromSale', 'بازگشت از فروش')], default='sale', max_length=10),
            preserve_default=False,
        ),
    ]
