# Generated by Django 2.2 on 2019-04-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0013_auto_20190426_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoritem',
            name='is_editable',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='factor',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
