# Generated by Django 2.0.5 on 2018-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0013_factor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factor',
            name='type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sale', 'فروش'), ('backFromBuy', 'بازگشت از خرید'), ('backFromSale', 'بازگشت از فروش')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='factor',
            unique_together={('code', 'type')},
        ),
    ]
