# Generated by Django 2.0.5 on 2018-08-26 06:13

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0073_auto_20180826_1043'),
        ('factors', '0014_auto_20180823_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('type', models.CharField(choices=[('receipt', 'رسید'), ('remittance', 'حواله')], max_length=15)),
                ('date', django_jalali.db.models.jDateField()),
                ('time', models.TimeField(blank=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='factors.Receipt')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiptItems', to='wares.Ware')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiptItems', to='wares.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='factor',
            name='rar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='factors.Receipt'),
        ),
    ]
