# Generated by Django 2.2 on 2019-04-29 05:05

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0014_auto_20190428_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='definition_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
