# Generated by Django 2.0.5 on 2018-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0015_auto_20180826_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='createType',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], default='manual', max_length=20),
        ),
    ]
