# Generated by Django 2.2 on 2020-10-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0015_auto_20200929_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_adjustment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factorexpense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_factorexpense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_factoritem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factorpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_factorpayment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_transfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
