# Generated by Django 2.0.5 on 2018-08-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0016_receipt_createtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='rar',
            new_name='receipt',
        ),
    ]
