# Generated by Django 2.2 on 2019-05-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0017_factoritem_output_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoritem',
            name='output_count',
        ),
    ]
