# Generated by Django 2.2 on 2020-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0020_factoritem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
