# Generated by Django 2.2 on 2019-05-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0020_auto_20190523_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
