# Generated by Django 2.2 on 2020-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0021_auto_20201118_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='fee',
            field=models.DecimalField(decimal_places=6, max_digits=24),
        ),
    ]
