# Generated by Django 2.2 on 2019-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0021_auto_20190523_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
