# Generated by Django 2.2 on 2020-11-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0014_auto_20201107_1531'),
        ('wares', '0015_auto_20201118_1331'),
        ('factors', '0022_auto_20201121_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseHandling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('first_confirmed_at', django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True)),
                ('second_confirmed_at', django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('start_date', django_jalali.db.models.jDateField()),
                ('counting_date', django_jalali.db.models.jDateField()),
                ('submit_date', django_jalali.db.models.jDateField()),
                ('handler', models.CharField(max_length=200)),
                ('ware_status', models.CharField(max_length=20)),
                ('explanation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_warehousehandling', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseHandlings', to='companies.FinancialYear')),
                ('first_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_warehousehandlingConfirmer', to=settings.AUTH_USER_MODEL)),
                ('second_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_warehousehandlingConfirmer', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouseHandlings', to='wares.Warehouse')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.warehouseHandling', 'مشاهده انبار گردانی'), ('create.warehouseHandling', 'تعریف انبار گردانی'), ('update.warehouseHandling', 'ویرایش انبار گردانی'), ('delete.warehouseHandling', 'حذف انبار گردانی')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WarehouseHandlingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('first_confirmed_at', django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True)),
                ('second_confirmed_at', django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True)),
                ('warehouse_remain', models.DecimalField(decimal_places=6, default=0, max_digits=24, null=True)),
                ('system_remain', models.DecimalField(decimal_places=6, default=0, max_digits=24, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_warehousehandlingitem', to=settings.AUTH_USER_MODEL)),
                ('first_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_warehousehandlingitemConfirmer', to=settings.AUTH_USER_MODEL)),
                ('second_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_warehousehandlingitemConfirmer', to=settings.AUTH_USER_MODEL)),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouseHandlingItems', to='wares.Ware')),
                ('warehouseHandling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='factors.WarehouseHandling')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
