# Generated by Django 2.2 on 2020-11-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0023_warehousehandling_warehousehandlingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousehandlingitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
