# Generated by Django 2.2 on 2019-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0023_auto_20190601_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoritem',
            name='remain_count',
        ),
        migrations.AddField(
            model_name='factoritem',
            name='total_input_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='total_output_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='calculated_output_value',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='remain_value',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24),
        ),
    ]
