# Generated by Django 2.2 on 2020-02-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0025_factoritem_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='count',
            field=models.DecimalField(decimal_places=6, max_digits=24),
        ),
    ]
