# Generated by Django 2.2 on 2020-11-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20201107_1531'),
        ('factors', '0025_auto_20201122_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousehandlingitem',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouseHandlingItems', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
