# Generated by Django 2.2 on 2020-11-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0026_warehousehandlingitem_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousehandling',
            name='inputAdjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouseHandlingAsInput', to='factors.models.adjustment.Adjustment'),
        ),
        migrations.AddField(
            model_name='warehousehandling',
            name='is_definite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehousehandling',
            name='outputAdjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouseHandlingAsOutput', to='factors.models.adjustment.Adjustment'),
        ),
    ]
