# Generated by Django 2.2 on 2020-03-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0026_auto_20200215_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='factorexpense',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='factoritem',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='factorpayment',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorItems', to='wares.Warehouse'),
        ),
    ]
