# Generated by Django 2.2 on 2020-03-08 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200307_1256'),
        ('factors', '0027_auto_20200307_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorExpense', to='accounts.FloatAccount'),
        ),
    ]
