# Generated by Django 2.2 on 2020-11-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0027_auto_20201124_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousehandlingitem',
            name='warehouseHandling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='factors.WarehouseHandling'),
        ),
    ]
