# Generated by Django 2.2 on 2020-03-10 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_account_person_type'),
        ('factors', '0028_expense_floataccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factorsAsCostCenter', to='accounts.FloatAccount'),
        ),
    ]
