# Generated by Django 2.2 on 2020-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0028_auto_20201125_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousehandlingitem',
            name='system_remain',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='warehousehandlingitem',
            name='warehouse_remain',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=24, null=True),
        ),
    ]
