# Generated by Django 2.2 on 2020-12-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0029_auto_20201126_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='sanad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='sanads.Sanad'),
        ),
    ]
