# Generated by Django 2.2 on 2021-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0030_auto_20201221_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorexpense',
            name='value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='factorpayment',
            name='value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
