# Generated by Django 2.2 on 2020-03-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0030_auto_20200310_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoritem',
            name='is_editable',
        ),
    ]
