# Generated by Django 2.2 on 2021-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0031_auto_20210113_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='paidValue',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
