# Generated by Django 2.2 on 2020-03-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0031_remove_factoritem_is_editable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factor',
            unique_together=set(),
        ),
    ]
