# Generated by Django 2.2 on 2020-03-26 08:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import factors.models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0032_auto_20200326_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoritem',
            name='remain_value',
        ),
        migrations.RemoveField(
            model_name='factoritem',
            name='total_input_count',
        ),
        migrations.RemoveField(
            model_name='factoritem',
            name='total_output_count',
        ),
        migrations.AddField(
            model_name='factoritem',
            name='remain_fees',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=factors.models.get_empty_array),
        ),
    ]
