# Generated by Django 2.2 on 2021-01-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0032_auto_20210113_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
