# Generated by Django 2.2 on 2021-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0033_adjustment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousehandling',
            name='submit_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
