# Generated by Django 2.2 on 2020-04-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0033_auto_20200326_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factor',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factorexpense',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factoritem',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factorpayment',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
    ]
