# Generated by Django 2.2 on 2020-04-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0034_auto_20200422_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factorexpense',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factoritem',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factorpayment',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
    ]
