# Generated by Django 2.2 on 2021-01-21 10:11
from factors.models import FactorItem


def set_unit_count(apps, schema_editor):
    for item in FactorItem.objects.all():
        item.unit = item.ware.main_unit
        item.unit_count = item.count
        item.save()


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('factors', '0035_auto_20210121_1330'),
    ]

    operations = [
        migrations.RunPython(set_unit_count, migrations.RunPython.noop)
    ]
