# Generated by Django 2.2 on 2021-01-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0036_auto_20210121_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='total_sum',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='factorpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factorPayments', to='transactions.Transaction'),
        ),
    ]
