# Generated by Django 2.2 on 2021-02-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0038_auto_20210130_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousehandlingitem',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
