# Generated by Django 2.2 on 2021-02-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
        ('factors', '0039_warehousehandlingitem_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='distributions.Visitor'),
        ),
    ]
