# Generated by Django 2.2 on 2021-03-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0043_auto_20210301_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='backFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backFactor', to='factors.Factor'),
        ),
    ]
