# Generated by Django 2.2 on 2021-03-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0044_factor_backfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='backFrom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backFactor', to='factors.Factor'),
        ),
    ]
