# Generated by Django 2.2 on 2021-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0045_auto_20210308_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
