# Generated by Django 2.2 on 2021-04-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0046_transfer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoritem',
            name='tax_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='tax_value',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True),
        ),
    ]
