# Generated by Django 2.2 on 2021-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0047_auto_20210404_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='after_rows_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='bottom_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
