# Generated by Django 2.2 on 2021-05-12 14:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0051_auto_20210502_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoritem',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
