# Generated by Django 2.2 on 2021-05-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0052_factoritem_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='first_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='first_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='second_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='second_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='warehousehandling',
            name='first_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='warehousehandling',
            name='first_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='warehousehandling',
            name='second_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='warehousehandling',
            name='second_confirmed_by',
        ),
    ]
