# Generated by Django 2.2 on 2021-07-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factors', '0056_auto_20210704_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.transfer', 'مشاهده انتقال'), ('create.transfer', 'تعریف انتقال'), ('update.transfer', 'ویرایش انتقال'), ('delete.transfer', 'حذف انتقال'), ('define.transfer', 'قطعی کردن انتقال'), ('getOwn.transfer', 'مشاهده انتقال های خود'), ('updateOwn.transfer', 'ویرایش انتقال های خود'), ('deleteOwn.transfer', 'حذف انتقال های خود'), ('defineOwn.transfer', 'قطعی کردن انتقال های خود'))},
        ),
        migrations.AddField(
            model_name='transfer',
            name='defined_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='definition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_defined',
            field=models.BooleanField(default=False),
        ),
    ]
