# Generated by Django 2.2 on 2021-07-06 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factors', '0057_auto_20210705_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustment',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.adjustment', 'مشاهده تعدیل '), ('create.adjustment', 'تعریف تعدیل '), ('update.adjustment', 'ویرایش تعدیل '), ('delete.adjustment', 'حذف تعدیل '), ('define.adjustment', 'قطعی کردن تعدیل '), ('getOwn.adjustment', 'مشاهده تعدیل های خود'), ('updateOwn.adjustment', 'ویرایش تعدیل های خود'), ('deleteOwn.adjustment', 'حذف تعدیل های خود'), ('defineOwn.adjustment', 'قطعی کردن تعدیل های خود'))},
        ),
        migrations.AddField(
            model_name='adjustment',
            name='defined_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='definition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='is_defined',
            field=models.BooleanField(default=False),
        ),
    ]
