# Generated by Django 2.2 on 2021-07-06 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factors', '0058_auto_20210706_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustment',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.adjustment', 'مشاهده تعدیل '), ('create.adjustment', 'تعریف تعدیل '), ('update.adjustment', 'ویرایش تعدیل '), ('delete.adjustment', 'حذف تعدیل '), ('define.adjustment', 'قطعی کردن تعدیل '), ('lock.adjustment', 'قفل کردن تعدیل '), ('getOwn.adjustment', 'مشاهده تعدیل های خود'), ('updateOwn.adjustment', 'ویرایش تعدیل های خود'), ('deleteOwn.adjustment', 'حذف تعدیل های خود'), ('defineOwn.adjustment', 'قطعی کردن تعدیل های خود'), ('lockOwn.adjustment', 'قفل کردن تعدیل های خود'))},
        ),
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.buyFactor', 'مشاهده فاکتور خرید'), ('create.buyFactor', 'تعریف فاکتور خرید'), ('update.buyFactor', 'ویرایش فاکتور خرید'), ('delete.buyFactor', 'حذف فاکتور خرید'), ('define.buyFactor', 'قطعی کردن فاکتور خرید'), ('lock.buyFactor', 'قفل کردن فاکتور خرید'), ('get.saleFactor', 'مشاهده فاکتور فروش'), ('create.saleFactor', 'تعریف فاکتور فروش'), ('update.saleFactor', 'ویرایش فاکتور فروش'), ('delete.saleFactor', 'حذف فاکتور فروش'), ('define.saleFactor', 'قطعی کردن فاکتور فروش'), ('lock.saleFactor', 'قفل کردن فاکتور فروش'), ('get.backFromSaleFactor', 'مشاهده فاکتور برگشت از فروش'), ('create.backFromSaleFactor', 'تعریف فاکتور برگشت از فروش'), ('update.backFromSaleFactor', 'ویرایش فاکتور برگشت از فروش'), ('delete.backFromSaleFactor', 'حذف فاکتور برگشت از فروش'), ('define.backFromSaleFactor', 'قطعی کردن فاکتور برگشت از فروش'), ('lock.backFromSaleFactor', 'قفل کردن فاکتور برگشت از فروش'), ('get.backFromBuyFactor', 'مشاهده فاکتور برگشت از خرید'), ('create.backFromBuyFactor', 'تعریف فاکتور برگشت از خرید'), ('update.backFromBuyFactor', 'ویرایش فاکتور برگشت از خرید'), ('delete.backFromBuyFactor', 'حذف فاکتور برگشت از خرید'), ('define.backFromBuyFactor', 'قطعی کردن فاکتور برگشت از خرید'), ('lock.backFromBuyFactor', 'قفل کردن فاکتور برگشت از خرید'), ('get.consumptionWareFactor', 'مشاهده حواله کالای مصرفی'), ('create.consumptionWareFactor', 'تعریف حواله کالای مصرفی'), ('update.consumptionWareFactor', 'ویرایش حواله کالای مصرفی'), ('delete.consumptionWareFactor', 'حذف حواله کالای مصرفی'), ('define.consumptionWareFactor', 'قطعی کردن حواله کالای مصرفی'), ('lock.consumptionWareFactor', 'قفل کردن حواله کالای مصرفی'), ('get.notPaidFactor', 'مشاهده فاکتور های پرداخت نشده'), ('get.notReceivedFactor', 'مشاهده فاکتور های دریافت نشده'), ('getOwn.buyFactor', 'مشاهده فاکتور خرید خود'), ('updateOwn.buyFactor', 'ویرایش فاکتور های خرید خود'), ('deleteOwn.buyFactor', 'حذف فاکتور های خرید خود'), ('defineOwn.buyFactor', 'قطعی کردن فاکتور های خرید خود'), ('lockOwn.buyFactor', 'قفل کردن فاکتور های خرید خود'), ('getOwn.saleFactor', 'مشاهده فاکتور های فروش خود'), ('updateOwn.saleFactor', 'ویرایش فاکتور های فروش خود'), ('deleteOwn.saleFactor', 'حذف فاکتور های فروش خود'), ('defineOwn.saleFactor', 'قطعی کردن فاکتور های فروش خود'), ('lockOwn.saleFactor', 'قفل کردن فاکتور های فروش خود'), ('getOwn.backFromSaleFactor', 'مشاهده فاکتور های برگشت از فروش خود'), ('updateOwn.backFromSaleFactor', 'ویرایش فاکتور های برگشت از فروش خود'), ('deleteOwn.backFromSaleFactor', 'حذف فاکتور های برگشت از فروش خود'), ('defineOwn.backFromSaleFactor', 'قطعی کردن فاکتور های برگشت از فروش خود'), ('lockOwn.backFromSaleFactor', 'قفل کردن فاکتور های برگشت از فروش خود'), ('getOwn.backFromBuyFactor', 'مشاهده فاکتور های برگشت از خرید خود'), ('updateOwn.backFromBuyFactor', 'ویرایش فاکتور های برگشت از خرید خود'), ('deleteOwn.backFromBuyFactor', 'حذف فاکتور های برگشت از خرید خود'), ('defineOwn.backFromBuyFactor', 'قطعی کردن فاکتور های برگشت از خرید خود'), ('lockOwn.backFromBuyFactor', 'قفل کردن فاکتور های برگشت از خرید خود'), ('getOwn.consumptionWareFactor', 'مشاهده حواله کالای مصرفی خود'), ('updateOwn.consumptionWareFactor', 'ویرایش حواله کالای مصرفی خود'), ('deleteOwn.consumptionWareFactor', 'حذف حواله کالای مصرفی خود'), ('defineOwn.consumptionWareFactor', 'قطعی کردن حواله کالای مصرفی خود'), ('lockOwn.consumptionWareFactor', 'قفل کردن حواله کالای مصرفی خود'), ('getOwn.notPaidFactor', 'مشاهده فاکتور های پرداخت نشده خود'), ('getOwn.notReceivedFactor', 'مشاهده فاکتور های دریافت نشده خود'), ('get.firstPeriodInventory', 'مشاهده موجودی اول دوره'), ('update.firstPeriodInventory', 'ثبت موجودی اول دوره'), ('create.buyPreFactor', 'تعریف پیش فاکتور خرید'), ('get.buyPreFactor', 'مشاهده پیش فاکتور خرید'), ('update.buyPreFactor', 'ویرایش پیش فاکتور خرید'), ('delete.buyPreFactor', 'حذف پیش فاکتور خرید'), ('convert.buyPreFactor', 'تبدیل پیش فاکتور خرید به فاکتور'), ('getOwn.buyPreFactor', 'مشاهده پیش فاکتور خرید خود'), ('updateOwn.buyPreFactor', 'ویرایش پیش فاکتور خرید خود'), ('deleteOwn.buyPreFactor', 'حذف پیش فاکتور خرید خود'), ('convertOwn.buyPreFactor', 'تبدیل پیش فاکتور خرید خود به فاکتور'), ('create.salePreFactor', 'تعریف پیش فاکتور فروش'), ('get.salePreFactor', 'مشاهده پیش فاکتور فروش'), ('update.salePreFactor', 'ویرایش پیش فاکتور فروش'), ('delete.salePreFactor', 'حذف پیش فاکتور فروش'), ('convert.salePreFactor', 'تبدیل پیش فاکتور فروش به فاکتور'), ('getOwn.salePreFactor', 'مشاهده پیش فاکتور فروش خود'), ('updateOwn.salePreFactor', 'ویرایش پیش فاکتور فروش خود'), ('deleteOwn.salePreFactor', 'حذف پیش فاکتور فروش خود'), ('convertOwn.salePreFactor', 'تبدیل پیش فاکتور فروش خود به فاکتور'), ('create.receipt', 'تعریف رسید'), ('get.receipt', 'مشاهده رسید'), ('update.receipt', 'ویرایش رسید'), ('delete.receipt', 'حذف رسید'), ('getOwn.receipt', 'مشاهده رسید های خود'), ('updateOwn.receipt', 'ویرایش رسید های خود'), ('deleteOwn.receipt', 'حذف رسید های خود'), ('create.remittance', 'تعریف حواله'), ('get.remittance', 'مشاهده حواله'), ('update.remittance', 'ویرایش حواله'), ('delete.remittance', 'حذف حواله'), ('getOwn.remittance', 'مشاهده حواله های خود'), ('updateOwn.remittance', 'ویرایش حواله های خود'), ('deleteOwn.remittance', 'حذف حواله های خود'), ('create.production', 'تعریف تولید'), ('get.production', 'مشاهده تولید'), ('update.production', 'ویرایش تولید'), ('delete.production', 'حذف تولید'), ('getOwn.production', 'مشاهده تولید های خود'), ('updateOwn.production', 'ویرایش تولید های خود'), ('deleteOwn.production', 'حذف تولید های خود'))},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.transfer', 'مشاهده انتقال'), ('create.transfer', 'تعریف انتقال'), ('update.transfer', 'ویرایش انتقال'), ('delete.transfer', 'حذف انتقال'), ('define.transfer', 'قطعی کردن انتقال'), ('lock.transfer', 'قفل کردن انتقال'), ('getOwn.transfer', 'مشاهده انتقال های خود'), ('updateOwn.transfer', 'ویرایش انتقال های خود'), ('deleteOwn.transfer', 'حذف انتقال های خود'), ('lockOwn.transfer', 'قفل کردن انتقال های خود'))},
        ),
        migrations.AlterModelOptions(
            name='warehousehandling',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('create.warehouseHandling', 'تعریف انبار گردانی'), ('get.warehouseHandling', 'مشاهده انبار گردانی'), ('update.warehouseHandling', 'ویرایش انبار گردانی'), ('delete.warehouseHandling', 'حذف انبار گردانی'), ('lock.warehouseHandling', 'قفل کردن انبار گردانی'), ('getOwn.warehouseHandling', 'مشاهده انبار گردانی های خود'), ('updateOwn.warehouseHandling', 'ویرایش انبار گردانی های خود'), ('deleteOwn.warehouseHandling', 'حذف انبار گردانی های خود'), ('lockOwn.warehouseHandling', 'قفل کردن انبار گردانی های خود'))},
        ),
        migrations.AddField(
            model_name='adjustment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='lock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factor',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factor',
            name='lock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='lock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousehandling',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehousehandling',
            name='lock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousehandling',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
