# Generated by Django 2.2 on 2021-08-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0063_factorsaggregatedsanad_explanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factorsaggregatedsanad',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.buyFactorsAggregatedSanad', 'مشاهده سند تجمیعی فاکتور خرید'), ('create.buyFactorsAggregatedSanad', 'تعریف سند تجمیعی فاکتور خرید'), ('update.buyFactorsAggregatedSanad', 'ویرایش سند تجمیعی فاکتور خرید'), ('delete.buyFactorsAggregatedSanad', 'حذف سند تجمیعی فاکتور خرید'), ('get.saleFactorsAggregatedSanad', 'مشاهده سند تجمیعی فاکتور فروش'), ('create.saleFactorsAggregatedSanad', 'تعریف سند تجمیعی فاکتور فروش'), ('update.saleFactorsAggregatedSanad', 'ویرایش سند تجمیعی فاکتور فروش'), ('delete.saleFactorsAggregatedSanad', 'حذف سند تجمیعی فاکتور فروش'), ('get.backFromSaleFactorsAggregatedSanad', 'مشاهده سند تجمیعی فاکتور برگشت از فروش'), ('create.backFromSaleFactorsAggregatedSanad', 'تعریف سند تجمیعی فاکتور برگشت از فروش'), ('update.backFromSaleFactorsAggregatedSanad', 'ویرایش سند تجمیعی فاکتور برگشت از فروش'), ('delete.backFromSaleFactorsAggregatedSanad', 'حذف سند تجمیعی فاکتور برگشت از فروش'), ('get.backFromBuyFactorsAggregatedSanad', 'مشاهده سند تجمیعی فاکتور برگشت از خرید'), ('create.backFromBuyFactorsAggregatedSanad', 'تعریف سند تجمیعی فاکتور برگشت از خرید'), ('update.backFromBuyFactorsAggregatedSanad', 'ویرایش سند تجمیعی فاکتور برگشت از خرید'), ('delete.backFromBuyFactorsAggregatedSanad', 'حذف سند تجمیعی فاکتور برگشت از خرید'), ('getOwn.buyFactorsAggregatedSanad', 'مشاهده سند تجمیعی فاکتور خرید خود'), ('updateOwn.buyFactorsAggregatedSanad', 'ویرایش سند تجمیعی فاکتور های خرید خود'), ('deleteOwn.buyFactorsAggregatedSanad', 'حذف سند تجمیعی فاکتور های خرید خود'), ('getOwn.saleFactorsAggregatedSanad', 'مشاهده سند تجمیعی فاکتور های فروش خود'), ('updateOwn.saleFactorsAggregatedSanad', 'ویرایش سند تجمیعی فاکتور های فروش خود'), ('deleteOwn.saleFactorsAggregatedSanad', 'حذف سند تجمیعی فاکتور های فروش خود'), ('getOwn.backFromSaleFactorsAggregatedSanad', 'مشاهده سند تجمیعی فاکتور های برگشت از فروش خود'), ('updateOwn.backFromSaleFactorsAggregatedSanad', 'ویرایش سند تجمیعی فاکتور های برگشت از فروش خود'), ('deleteOwn.backFromSaleFactorsAggregatedSanad', 'حذف سند تجمیعی فاکتور های برگشت از فروش خود'), ('getOwn.backFromBuyFactorsAggregatedSanad', 'مشاهده سند تجمیعی فاکتور های برگشت از خرید خود'), ('updateOwn.backFromBuyFactorsAggregatedSanad', 'ویرایش سند تجمیعی فاکتور های برگشت از خرید خود'), ('deleteOwn.backFromBuyFactorsAggregatedSanad', 'حذف سند تجمیعی فاکتور های برگشت از خرید خود'))},
        ),
        migrations.RemoveField(
            model_name='factor',
            name='has_aggregated_sanad',
        ),
    ]
