# Generated by Django 2.2 on 2021-08-26 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0064_auto_20210804_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveredFactors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factor',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='distributions.Distribution'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='loaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loadedFactors', to=settings.AUTH_USER_MODEL),
        ),
    ]
