# Generated by Django 2.2 on 2021-09-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0065_auto_20210826_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='factor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='factors.Factor'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='input_factor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='input_transfer', to='factors.Factor'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='output_factor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='output_transfer', to='factors.Factor'),
        ),
    ]
