# Generated by Django 2.0.5 on 2018-07-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=0, max_digits=24)),
                ('min_sale', models.IntegerField(blank=True, null=True)),
                ('max_sale', models.IntegerField(blank=True, null=True)),
                ('min_inventory', models.IntegerField(blank=True, null=True)),
                ('max_inventory', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WareLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField(choices=[(0, 'nature'), (1, 'group'), (2, 'category'), (3, 'ware')])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wares.WareLevel')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='ware',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='wares.WareLevel'),
        ),
        migrations.AddField(
            model_name='ware',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='wares.Unit'),
        ),
        migrations.AddField(
            model_name='ware',
            name='wareHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='wares.Warehouse'),
        ),
    ]
