# Generated by Django 2.2 on 2020-04-24 08:26

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='companies.FinancialYear')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.unit', 'مشاهده واحد'), ('create.unit', 'تعریف واحد'), ('update.unit', 'ویرایش واحد'), ('delete.unit', 'حذف واحد')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('isDisabled', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=0, max_digits=24)),
                ('pricingType', models.IntegerField(blank=True, choices=[(0, 'فایفو'), (1, 'میانگین موزون')], null=True)),
                ('minSale', models.IntegerField(blank=True, null=True)),
                ('maxSale', models.IntegerField(blank=True, null=True)),
                ('minInventory', models.IntegerField(blank=True, null=True)),
                ('maxInventory', models.IntegerField(blank=True, null=True)),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('isService', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
                'permissions': (('get.ware', 'مشاهده کالا'), ('create.ware', 'تعریف کالا'), ('update.ware', 'ویرایش کالا'), ('delete.ware', 'حذف کالا'), ('get.wareInventory', 'مشاهده موجودی کالا')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.FinancialYear')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.warehouse', 'مشاهده انبار'), ('create.warehouse', 'تعریف انبار'), ('update.warehouse', 'ویرایش انبار'), ('delete.warehouse', 'حذف انبار')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WareLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField(choices=[(0, 'nature'), (1, 'group'), (2, 'category')])),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wareLevels', to='companies.FinancialYear')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='wares.WareLevel')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.wareLevel', 'مشاهده سطح کالا'), ('create.wareLevel', 'تعریف سطح کالا'), ('update.wareLevel', 'ویرایش سطح کالا'), ('delete.wareLevel', 'حذف سطح کالا')),
                'abstract': False,
                'default_permissions': (),
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='WareInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('fee', models.DecimalField(decimal_places=0, max_digits=24)),
                ('order', models.IntegerField()),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waresInventories', to='companies.FinancialYear')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='wares.Ware')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='wares.Warehouse')),
            ],
            options={
                'ordering': ['order'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='ware',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wares', to='wares.WareLevel'),
        ),
        migrations.AddField(
            model_name='ware',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='ware',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='ware',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wares', to='wares.Unit'),
        ),
        migrations.AddField(
            model_name='ware',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wares', to='wares.Warehouse'),
        ),
    ]
