# Generated by Django 2.0.5 on 2018-10-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warelevel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='warelevel',
            unique_together={('name', 'level')},
        ),
    ]
