# Generated by Django 2.0.5 on 2018-07-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ware',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='wares.WareLevel'),
        ),
        migrations.AlterField(
            model_name='warelevel',
            name='level',
            field=models.IntegerField(choices=[(0, 'nature'), (1, 'group'), (2, 'category')]),
        ),
    ]
