# Generated by Django 2.0.5 on 2019-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(0, 'فایفو'), (1, 'میانگین موزون')]),
        ),
    ]
