# Generated by Django 2.0.5 on 2018-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (3, 'special_value'), (2, 'avg'), (1, 'lifo')]),
        ),
    ]
