# Generated by Django 2.0.5 on 2018-07-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180714_1452'),
        ('wares', '0002_auto_20180710_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (0, 'fifl'), (2, 'avg'), (1, 'lifo')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ware',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wares', to='wares.WareLevel'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wares', to='wares.Unit'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='wareHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wares', to='wares.WareHouse'),
        ),
        migrations.AlterField(
            model_name='warelevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='wares.WareLevel'),
        ),
    ]
