# Generated by Django 2.2 on 2020-07-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0002_auto_20200719_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.unit', 'مشاهده واحد'), ('create.unit', 'تعریف واحد'), ('update.unit', 'ویرایش واحد'), ('delete.unit', 'حذف واحد'), ('getOwn.unit', 'مشاهده واحد های خود'), ('updateOwn.unit', 'ویرایش واحد های خود'), ('deleteOwn.unit', 'حذف واحد های خود'))},
        ),
        migrations.AlterModelOptions(
            name='ware',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (('get.ware', 'مشاهده کالا'), ('create.ware', 'تعریف کالا'), ('update.ware', 'ویرایش کالا'), ('delete.ware', 'حذف کالا'), ('get.wareInventory', 'مشاهده موجودی کالا'), ('getOwn.ware', 'مشاهده کالا های خود'), ('updateOwn.ware', 'ویرایش کالا های خود'), ('deleteOwn.ware', 'حذف کالا های خود'), ('getOwn.wareInventory', 'مشاهده موجودی کالا های خود'))},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.warehouse', 'مشاهده انبار'), ('create.warehouse', 'تعریف انبار'), ('update.warehouse', 'ویرایش انبار'), ('delete.warehouse', 'حذف انبار'), ('getOwn.warehouse', 'مشاهده انبار های خود'), ('updateOwn.warehouse', 'ویرایش انبار های خود'), ('deleteOwn.warehouse', 'حذف انبار های خود'))},
        ),
        migrations.AlterModelOptions(
            name='warelevel',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.wareLevel', 'مشاهده سطح کالا'), ('create.wareLevel', 'تعریف سطح کالا'), ('update.wareLevel', 'ویرایش سطح کالا'), ('delete.wareLevel', 'حذف سطح کالا'), ('getOwn.wareLevel', 'مشاهده سطح کالا های خود'), ('updateOwn.wareLevel', 'ویرایش سطح کالا های خود'), ('deleteOwn.wareLevel', 'حذف سطح کالا های خود'))},
        ),
    ]
