# Generated by Django 2.0.5 on 2018-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0002_auto_20180911_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (0, 'fifo'), (1, 'lifo'), (3, 'special_value')]),
        ),
    ]
