# Generated by Django 2.0.5 on 2019-03-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0002_auto_20190321_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseinventory',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='wares.Ware'),
        ),
        migrations.AlterField(
            model_name='warehouseinventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='wares.Warehouse'),
        ),
    ]
