# Generated by Django 2.2 on 2020-04-24 16:38

from django.db import migrations, models

from wares.models import Ware

Ware.objects.update(pricingType=0)


class Migration(migrations.Migration):
    dependencies = [
        ('wares', '0002_auto_20200424_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.CharField(choices=[('wm', 'میانگین موزون'), ('f', 'فایفو')], default='f', max_length=2),
            preserve_default=False,
        ),
    ]
