# Generated by Django 2.2 on 2020-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0003_auto_20200424_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.CharField(choices=[('f', 'فایفو'), ('wm', 'میانگین موزون')], max_length=2),
        ),
    ]
