# Generated by Django 2.0.5 on 2018-10-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0003_auto_20181017_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (1, 'lifo'), (0, 'fifo'), (3, 'special_value')]),
        ),
    ]
