# Generated by Django 2.2 on 2020-07-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0004_auto_20200725_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ware',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wareinventory',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warelevel',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
    ]
