# Generated by Django 2.2 on 2020-06-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0004_auto_20200530_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.CharField(choices=[('wm', 'میانگین موزون'), ('f', 'فایفو')], max_length=2),
        ),
    ]
