# Generated by Django 2.0.5 on 2018-07-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0004_auto_20180714_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (0, 'fifo'), (2, 'avg'), (1, 'lifo')]),
        ),
    ]
