# Generated by Django 2.0.5 on 2018-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0004_auto_20180913_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (2, 'avg'), (0, 'fifo'), (3, 'special_value')]),
        ),
    ]
