# Generated by Django 2.0.5 on 2018-10-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0005_auto_20181023_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(0, 'fifo'), (2, 'avg')]),
        ),
        migrations.AlterField(
            model_name='ware',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
    ]
