# Generated by Django 2.0.5 on 2019-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0005_auto_20190404_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(1, 'میانگین موزون'), (0, 'فایفو')]),
        ),
    ]
