# Generated by Django 2.2 on 2020-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0005_auto_20200607_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.CharField(choices=[('f', 'فایفو'), ('wm', 'میانگین موزون')], max_length=2),
        ),
    ]
