# Generated by Django 2.0.5 on 2018-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0006_auto_20181023_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(0, 'fifo'), (1, 'avg')]),
        ),
    ]
