# Generated by Django 2.0.5 on 2019-02-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0007_auto_20181122_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(0, 'فایفو'), (1, 'میانگین موزون')]),
        ),
    ]
