# Generated by Django 2.0.5 on 2018-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0007_auto_20180718_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (1, 'lifo'), (0, 'fifo'), (2, 'avg')]),
        ),
    ]
