# Generated by Django 2.0.5 on 2018-09-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0007_auto_20180923_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (3, 'special_value'), (0, 'fifo'), (1, 'lifo')]),
        ),
    ]
