# Generated by Django 2.0.5 on 2019-02-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0008_auto_20190218_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(1, 'میانگین موزون'), (0, 'فایفو')]),
        ),
    ]
