# Generated by Django 2.0.5 on 2018-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0008_auto_20180718_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (0, 'fifo'), (1, 'lifo'), (3, 'special_value')]),
        ),
    ]
