# Generated by Django 2.0.5 on 2018-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0008_auto_20180923_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (2, 'avg'), (0, 'fifo'), (3, 'special_value')]),
        ),
    ]
