# Generated by Django 2.2 on 2020-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wares', '0008_auto_20200616_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.CharField(choices=[('wm', 'میانگین موزون'), ('f', 'فایفو')], max_length=2),
        ),
    ]
