# Generated by Django 2.0.5 on 2019-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0009_auto_20190404_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(1, 'میانگین موزون'), (0, 'فایفو')]),
        ),
    ]
