# Generated by Django 2.0.5 on 2018-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0009_auto_20180924_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (2, 'avg'), (1, 'lifo'), (0, 'fifo')]),
        ),
    ]
