# Generated by Django 2.2 on 2020-10-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0009_auto_20200929_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_unit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ware',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_ware', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_warehouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wareinventory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_wareinventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warelevel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_warelevel', to=settings.AUTH_USER_MODEL),
        ),
    ]
