# Generated by Django 2.2 on 2020-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0009_auto_20200618_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.CharField(choices=[('f', 'فایفو'), ('wm', 'میانگین موزون')], max_length=2),
        ),
    ]
