# Generated by Django 2.2 on 2020-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0010_auto_20200618_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.CharField(choices=[('wm', 'میانگین موزون'), ('f', 'فایفو')], max_length=2),
        ),
    ]
