# Generated by Django 2.0.5 on 2018-10-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0011_auto_20180926_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (0, 'fifo'), (3, 'special_value'), (1, 'lifo')]),
        ),
    ]
