# Generated by Django 2.0.5 on 2019-04-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_financialyear_is_active'),
        ('wares', '0011_auto_20190404_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ware',
            options={'default_permissions': (), 'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='unit',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ware',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseinventory',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warelevel',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ware_levels', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
