# Generated by Django 2.2 on 2020-06-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0011_auto_20200624_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.CharField(choices=[('f', 'فایفو'), ('wm', 'میانگین موزون')], max_length=2),
        ),
    ]
