# Generated by Django 2.0.5 on 2018-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0012_auto_20180725_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (3, 'special_value'), (2, 'avg'), (0, 'fifo')]),
        ),
    ]
