# Generated by Django 2.0.5 on 2018-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0012_auto_20181004_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (3, 'special_value'), (1, 'lifo'), (0, 'fifo')]),
        ),
    ]
