# Generated by Django 2.0.5 on 2018-07-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0013_auto_20180727_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (2, 'avg'), (0, 'fifo'), (1, 'lifo')]),
        ),
    ]
