# Generated by Django 2.0.5 on 2019-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0014_auto_20190406_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ware',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='warelevel',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
