# Generated by Django 2.0.5 on 2018-07-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0014_auto_20180727_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (0, 'fifo'), (1, 'lifo'), (3, 'special_value')]),
        ),
    ]
