# Generated by Django 2.0.5 on 2019-04-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0015_auto_20190409_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(1, 'میانگین موزون'), (0, 'فایفو')]),
        ),
    ]
