# Generated by Django 2.0.5 on 2018-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0015_auto_20180729_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (2, 'avg'), (1, 'lifo'), (0, 'fifo')]),
        ),
    ]
