# Generated by Django 2.0.5 on 2018-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0016_auto_20180729_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (1, 'lifo'), (0, 'fifo'), (3, 'special_value')]),
        ),
    ]
