# Generated by Django 2.2 on 2021-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0016_auto_20201205_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ware',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (('get.ware', 'مشاهده کالا'), ('create.ware', 'تعریف کالا'), ('update.ware', 'ویرایش کالا'), ('delete.ware', 'حذف کالا'), ('getOwn.ware', 'مشاهده کالا های خود'), ('updateOwn.ware', 'ویرایش کالا های خود'), ('deleteOwn.ware', 'حذف کالا های خود'), ('sort.inventory', 'مرتب سازی کاردکس کالا'))},
        ),
        migrations.AddField(
            model_name='ware',
            name='check_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wareinventory',
            name='fee',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
