# Generated by Django 2.0.5 on 2019-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0017_auto_20190409_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(1, 'میانگین موزون'), (0, 'فایفو')]),
        ),
    ]
