# Generated by Django 2.2 on 2021-01-21 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ('companies', '0018_auto_20210104_1053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wares', '0017_auto_20210103_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='own_salepricetype', to=settings.AUTH_USER_MODEL)),
                ('financial_year',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (
                    ('get.salePriceType', 'مشاهده نوع های نرخ فروش '),
                    ('create.salePriceType', 'تعریف نوع های نرخ فروش '),
                    ('update.salePriceType', 'ویرایش نوع های نرخ فروش '),
                    ('delete.salePriceType', 'حذف نوع های نرخ فروش '),
                    ('getOwn.salePriceType', 'مشاهده نوع های نرخ فروش خود'),
                    ('updateOwn.salePriceType', 'ویرایش نوع های نرخ فروش خود'),
                    ('deleteOwn.salePriceType', 'حذف نوع های نرخ فروش خود')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_saleprice',
                                   to=settings.AUTH_USER_MODEL)),
                ('mainUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                               related_name='salePricesAsMainUnit', to='wares.Unit')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wares.SalePriceType')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salePrices',
                                           to='wares.Unit')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salePrices',
                                           to='wares.Ware')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.salePrice', 'مشاهده قیمت فروش'), ('create.salePrice', 'تعریف قیمت فروش'),
                                ('update.salePrice', 'ویرایش قیمت فروش'), ('delete.salePrice', 'حذف قیمت فروش'),
                                ('getOwn.salePrice', 'مشاهده قیمت های خود'),
                                ('updateOwn.salePrice', 'ویرایش قیمت های خود'),
                                ('deleteOwn.salePrice', 'حذف قیمت های خود')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
