# Generated by Django 2.2 on 2021-01-21 10:18

from django.db import migrations
from django.db.models import Q


def move_units_and_prices(apps, schema_editor):
    SalePriceType = apps.get_model('wares', 'SalePriceType')
    Ware = apps.get_model('wares', 'Ware')
    SalePrice = apps.get_model('wares', 'SalePrice')

    for ware in Ware.objects.filter(~Q(price=None)):
        financial_year = ware.financial_year

        salePriceType = SalePriceType.objects.filter(financial_year=financial_year).first()
        if not salePriceType:
            salePriceType = SalePriceType.objects.create(
                financial_year=financial_year,
                name='فروش عادی'
            )

        SalePrice.objects.create(
            type=salePriceType,
            ware=ware,
            unit=ware.unit,
            price=ware.price
        )


class Migration(migrations.Migration):
    dependencies = [
        ('wares', '0018_saleprice_salepricetype'),
    ]

    operations = [
        migrations.RunPython(move_units_and_prices, migrations.RunPython.noop)
    ]
