# Generated by Django 2.0.5 on 2018-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0018_auto_20180730_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (3, 'special_value'), (1, 'lifo'), (2, 'avg')]),
        ),
    ]
