# Generated by Django 2.0.5 on 2019-04-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0019_auto_20190410_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(1, 'میانگین موزون'), (0, 'فایفو')]),
        ),
    ]
