# Generated by Django 2.0.5 on 2019-04-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0020_auto_20190410_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='warelevel',
            name='financial_year',
        ),
    ]
