# Generated by Django 2.2 on 2021-01-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0020_auto_20210123_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleprice',
            options={'default_permissions': (), 'ordering': ('pk',), 'permissions': (('get.salePrice', 'مشاهده قیمت فروش'), ('create.salePrice', 'تعریف قیمت فروش'), ('update.salePrice', 'ویرایش قیمت فروش'), ('delete.salePrice', 'حذف قیمت فروش'), ('getOwn.salePrice', 'مشاهده قیمت های خود'), ('updateOwn.salePrice', 'ویرایش قیمت های خود'), ('deleteOwn.salePrice', 'حذف قیمت های خود'))},
        ),
        migrations.RemoveField(
            model_name='ware',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='unit',
        ),
    ]
