# Generated by Django 2.0.5 on 2018-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0020_auto_20180730_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (0, 'fifo'), (3, 'special_value'), (2, 'avg')]),
        ),
    ]
