# Generated by Django 2.0.5 on 2018-07-31 04:44

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0021_auto_20180730_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='created_at',
            field=django_jalali.db.models.jDateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (3, 'special_value'), (1, 'lifo'), (2, 'avg')]),
        ),
        migrations.AlterField(
            model_name='ware',
            name='updated_at',
            field=django_jalali.db.models.jDateField(blank=True, editable=False),
        ),
    ]
