# Generated by Django 2.0.5 on 2019-04-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0021_auto_20190410_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='warelevel',
            name='source_id',
        ),
    ]
