# Generated by Django 2.2 on 2021-01-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0021_auto_20210123_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salepricetype',
            options={'default_permissions': (), 'ordering': ('id',), 'permissions': (('get.salePriceType', 'مشاهده نوع های نرخ فروش '), ('create.salePriceType', 'تعریف نوع های نرخ فروش '), ('update.salePriceType', 'ویرایش نوع های نرخ فروش '), ('delete.salePriceType', 'حذف نوع های نرخ فروش '), ('getOwn.salePriceType', 'مشاهده نوع های نرخ فروش خود'), ('updateOwn.salePriceType', 'ویرایش نوع های نرخ فروش خود'), ('deleteOwn.salePriceType', 'حذف نوع های نرخ فروش خود'))},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'default_permissions': (), 'ordering': ('pk',), 'permissions': (('get.unit', 'مشاهده واحد'), ('create.unit', 'تعریف واحد'), ('update.unit', 'ویرایش واحد'), ('delete.unit', 'حذف واحد'), ('getOwn.unit', 'مشاهده واحد های خود'), ('updateOwn.unit', 'ویرایش واحد های خود'), ('deleteOwn.unit', 'حذف واحد های خود'))},
        ),
        migrations.AlterUniqueTogether(
            name='saleprice',
            unique_together={('ware', 'unit', 'type')},
        ),
    ]
