# Generated by Django 2.2 on 2021-01-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0022_auto_20210123_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ware',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='saleprice',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=24),
        ),
    ]
