# Generated by Django 2.0.5 on 2018-07-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0022_auto_20180731_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (2, 'avg'), (1, 'lifo'), (3, 'special_value')]),
        ),
    ]
