# Generated by Django 2.2 on 2021-02-02 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wares', '0023_auto_20210126_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('is_increase', models.BooleanField()),
                ('is_percent', models.BooleanField()),
                ('rate', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_salepricechange', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('get.salePriceChange', 'مشاهده تغییرات قیمت فروش'), ('getOwn.salePriceChange', 'مشاهده تغییرات قیمت های فروش خود')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='saleprice',
            options={'default_permissions': (), 'ordering': ('pk',), 'permissions': (('get.salePrice', 'مشاهده قیمت فروش'), ('create.salePrice', 'تعریف قیمت فروش'), ('update.salePrice', 'ویرایش قیمت فروش'), ('delete.salePrice', 'حذف قیمت فروش'), ('getOwn.salePrice', 'مشاهده قیمت های فروش خود'), ('updateOwn.salePrice', 'ویرایش قیمت های فروش خود'), ('deleteOwn.salePrice', 'حذف قیمت های فروش خود'))},
        ),
        migrations.CreateModel(
            name='WareSalePriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('previous_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('new_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_waresalepricechange', to=settings.AUTH_USER_MODEL)),
                ('salePrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wares.SalePrice')),
                ('salePriceChange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wares.SalePriceChange')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
