# Generated by Django 2.2 on 2021-02-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0024_auto_20210202_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salepricechange',
            options={'default_permissions': (), 'ordering': ('-pk',), 'permissions': (('get.salePriceChange', 'مشاهده تغییرات قیمت فروش'), ('getOwn.salePriceChange', 'مشاهده تغییرات قیمت های فروش خود'))},
        ),
    ]
