# Generated by Django 2.2 on 2021-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0025_auto_20210210_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='commission_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
