# Generated by Django 2.2 on 2021-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0026_ware_commission_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleprice',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ('pk',), 'permissions': (('get.salePrice', 'مشاهده قیمت فروش'), ('create.salePrice', 'تعریف قیمت فروش'), ('update.salePrice', 'ویرایش قیمت فروش'), ('delete.salePrice', 'حذف قیمت فروش'), ('getOwn.salePrice', 'مشاهده قیمت های فروش خود'), ('updateOwn.salePrice', 'ویرایش قیمت های فروش خود'), ('deleteOwn.salePrice', 'حذف قیمت های فروش خود'))},
        ),
        migrations.AlterModelOptions(
            name='salepricechange',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ('-pk',), 'permissions': (('get.salePriceChange', 'مشاهده تغییرات قیمت فروش'), ('getOwn.salePriceChange', 'مشاهده تغییرات قیمت های فروش خود'))},
        ),
        migrations.AlterModelOptions(
            name='salepricetype',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ('id',), 'permissions': (('get.salePriceType', 'مشاهده نوع های نرخ فروش '), ('create.salePriceType', 'تعریف نوع های نرخ فروش '), ('update.salePriceType', 'ویرایش نوع های نرخ فروش '), ('delete.salePriceType', 'حذف نوع های نرخ فروش '), ('getOwn.salePriceType', 'مشاهده نوع های نرخ فروش خود'), ('updateOwn.salePriceType', 'ویرایش نوع های نرخ فروش خود'), ('deleteOwn.salePriceType', 'حذف نوع های نرخ فروش خود'))},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ('pk',), 'permissions': (('get.unit', 'مشاهده واحد'), ('create.unit', 'تعریف واحد'), ('update.unit', 'ویرایش واحد'), ('delete.unit', 'حذف واحد'), ('getOwn.unit', 'مشاهده واحد های خود'), ('updateOwn.unit', 'ویرایش واحد های خود'), ('deleteOwn.unit', 'حذف واحد های خود'))},
        ),
        migrations.AlterModelOptions(
            name='ware',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['code'], 'permissions': (('get.ware', 'مشاهده کالا'), ('create.ware', 'تعریف کالا'), ('update.ware', 'ویرایش کالا'), ('delete.ware', 'حذف کالا'), ('getOwn.ware', 'مشاهده کالا های خود'), ('updateOwn.ware', 'ویرایش کالا های خود'), ('deleteOwn.ware', 'حذف کالا های خود'), ('sort.inventory', 'مرتب سازی کاردکس کالا'))},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.warehouse', 'مشاهده انبار'), ('create.warehouse', 'تعریف انبار'), ('update.warehouse', 'ویرایش انبار'), ('delete.warehouse', 'حذف انبار'), ('getOwn.warehouse', 'مشاهده انبار های خود'), ('updateOwn.warehouse', 'ویرایش انبار های خود'), ('deleteOwn.warehouse', 'حذف انبار های خود'))},
        ),
        migrations.AlterModelOptions(
            name='wareinventory',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['order'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='waresalepricechange',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ('pk',), 'permissions': ()},
        ),
    ]
