# Generated by Django 2.2 on 2021-03-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0028_auto_20210301_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleprice',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24, null=True),
        ),
    ]
