# Generated by Django 2.2 on 2019-05-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0032_auto_20190519_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(0, 'فایفو'), (1, 'میانگین موزون')]),
        ),
    ]
