# Generated by Django 2.0.5 on 2018-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0033_auto_20180811_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (2, 'avg'), (3, 'special_value'), (0, 'fifo')]),
        ),
    ]
