# Generated by Django 2.0.5 on 2018-08-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0035_auto_20180812_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (3, 'special_value'), (0, 'fifo'), (2, 'avg')]),
        ),
    ]
