# Generated by Django 2.0.5 on 2018-08-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0039_auto_20180814_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (2, 'avg'), (0, 'fifo'), (3, 'special_value')]),
        ),
    ]
