# Generated by Django 2.2 on 2020-02-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0039_auto_20200222_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warebalance',
            name='count',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
