# Generated by Django 2.0.5 on 2018-08-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0040_auto_20180815_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (1, 'lifo'), (2, 'avg'), (3, 'special_value')]),
        ),
    ]
