# Generated by Django 2.2 on 2020-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0040_auto_20200225_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(choices=[(1, 'میانگین موزون'), (0, 'فایفو')]),
        ),
    ]
