# Generated by Django 2.2 on 2020-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0041_auto_20200225_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='isService',
            field=models.BooleanField(default=False),
        ),
    ]
