# Generated by Django 2.0.5 on 2018-08-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0041_auto_20180816_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (0, 'fifo'), (2, 'avg'), (1, 'lifo')]),
        ),
    ]
