# Generated by Django 2.0.5 on 2018-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0044_auto_20180816_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (3, 'special_value'), (2, 'avg'), (1, 'lifo')]),
        ),
    ]
