# Generated by Django 2.2 on 2020-03-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0045_auto_20200303_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='warelevel',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(1, 'میانگین موزون'), (0, 'فایفو')], null=True),
        ),
    ]
