# Generated by Django 2.0.5 on 2018-08-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0046_auto_20180817_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (0, 'fifo'), (1, 'lifo'), (2, 'avg')]),
        ),
    ]
