# Generated by Django 2.2 on 2020-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0046_auto_20200307_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(0, 'فایفو'), (1, 'میانگین موزون')], null=True),
        ),
    ]
