# Generated by Django 2.0.5 on 2018-08-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0047_auto_20180817_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (1, 'lifo'), (0, 'fifo'), (3, 'special_value')]),
        ),
    ]
