# Generated by Django 2.2 on 2020-03-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0048_auto_20200309_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(0, 'فایفو'), (1, 'میانگین موزون')], null=True),
        ),
    ]
