# Generated by Django 2.0.5 on 2018-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0050_auto_20180820_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (3, 'special_value'), (0, 'fifo'), (2, 'avg')]),
        ),
    ]
