# Generated by Django 2.0.5 on 2018-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0053_auto_20180821_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (2, 'avg'), (1, 'lifo'), (3, 'special_value')]),
        ),
    ]
