# Generated by Django 2.2 on 2020-03-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0056_auto_20200310_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warebalance',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(0, 'فایفو'), (1, 'میانگین موزون')], null=True),
        ),
    ]
