# Generated by Django 2.0.5 on 2018-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0058_auto_20180822_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (3, 'special_value'), (0, 'fifo'), (1, 'lifo')]),
        ),
    ]
