# Generated by Django 2.2 on 2020-03-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20200314_1942'),
        ('wares', '0059_auto_20200315_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WareBalance',
            new_name='WareInventory',
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(1, 'میانگین موزون'), (0, 'فایفو')], null=True),
        ),
    ]
