# Generated by Django 2.2 on 2020-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0062_auto_20200315_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='wareinventory',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(0, 'فایفو'), (1, 'میانگین موزون')], null=True),
        ),
    ]
