# Generated by Django 2.0.5 on 2018-08-23 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0062_auto_20180823_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (0, 'fifo'), (2, 'avg'), (1, 'lifo')]),
        ),
        migrations.AddField(
            model_name='warehouseinventory',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='wares.Ware'),
        ),
        migrations.AddField(
            model_name='warehouseinventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='wares.Warehouse'),
        ),
    ]
