# Generated by Django 2.0.5 on 2018-08-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0063_auto_20180823_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseinventory',
            old_name='warehouse',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (1, 'lifo'), (2, 'avg'), (0, 'fifo')]),
        ),
    ]
