# Generated by Django 2.2 on 2020-03-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0063_auto_20200316_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wareinventory',
            options={'default_permissions': (), 'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='wareinventory',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(1, 'میانگین موزون'), (0, 'فایفو')], null=True),
        ),
    ]
