# Generated by Django 2.0.5 on 2018-08-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0064_auto_20180823_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (0, 'fifo'), (3, 'special_value'), (1, 'lifo')]),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseinventory',
            unique_together={('warehouse', 'ware')},
        ),
    ]
