# Generated by Django 2.2 on 2020-03-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0065_auto_20200321_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wareinventory',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waresInventories', to='companies.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='wareinventory',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='wares.Ware'),
        ),
        migrations.AlterField(
            model_name='wareinventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='wares.Warehouse'),
        ),
    ]
