# Generated by Django 2.0.5 on 2018-08-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0065_auto_20180824_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(3, 'special_value'), (1, 'lifo'), (2, 'avg'), (0, 'fifo')]),
        ),
    ]
