# Generated by Django 2.0.5 on 2018-08-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0066_auto_20180824_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (2, 'avg'), (3, 'special_value'), (1, 'lifo')]),
        ),
    ]
