# Generated by Django 2.2 on 2020-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0067_auto_20200323_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(0, 'فایفو'), (1, 'میانگین موزون')], null=True),
        ),
    ]
