# Generated by Django 2.0.5 on 2018-08-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0067_auto_20180824_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (1, 'lifo'), (3, 'special_value'), (2, 'avg')]),
        ),
    ]
