# Generated by Django 2.0.5 on 2018-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0068_auto_20180824_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(2, 'avg'), (3, 'special_value'), (1, 'lifo'), (0, 'fifo')]),
        ),
    ]
