# Generated by Django 2.2 on 2020-04-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0070_auto_20200419_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='ware',
            options={'ordering': ['code'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='wareinventory',
            options={'ordering': ['order'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='warelevel',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
    ]
