# Generated by Django 2.0.5 on 2018-08-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0070_auto_20180825_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(1, 'lifo'), (0, 'fifo'), (2, 'avg'), (3, 'special_value')]),
        ),
    ]
