# Generated by Django 2.2 on 2020-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0071_auto_20200422_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='ware',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='wareinventory',
            options={'default_permissions': (), 'ordering': ['order'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='warelevel',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterField(
            model_name='ware',
            name='pricingType',
            field=models.IntegerField(blank=True, choices=[(1, 'میانگین موزون'), (0, 'فایفو')], null=True),
        ),
    ]
