# Generated by Django 2.0.5 on 2018-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0071_auto_20180825_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='pricing_type',
            field=models.IntegerField(choices=[(0, 'fifo'), (1, 'lifo'), (2, 'avg'), (3, 'special_value')]),
        ),
    ]
