# Generated by Django 2.2 on 2020-07-19 12:42

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprestSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('settled_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('is_settled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-code'],
                'permissions': (('get.imprestSettlement', 'مشاهده تسویه تنخواه'), ('create.imprestSettlement', 'تعریف تسویه تنخواه'), ('update.imprestSettlement', 'ویرایش تسویه تنخواه'), ('delete.imprestSettlement', 'حذف تسویه تنخواه')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ImprestSettlementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('date', django_jalali.db.models.jDateField()),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlementItems', to='accounts.Account')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlementItemsAsCostCenter', to='accounts.FloatAccount')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
