# Generated by Django 2.2 on 2020-07-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20200719_1712'),
        ('accounts', '0002_auto_20200719_1712'),
        ('transactions', '0001_initial'),
        ('imprests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestsettlementitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imprestsettlementitem',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='imprestsettlementitem',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlementItems', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='imprestsettlementitem',
            name='imprestSettlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imprests.ImprestSettlement'),
        ),
        migrations.AddField(
            model_name='imprestsettlement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imprestsettlement',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='imprestsettlement',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlements', to='transactions.Transaction'),
        ),
    ]
