# Generated by Django 2.2 on 2020-07-12 10:13

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200708_1457'),
        ('transactions', '0003_auto_20200712_1443'),
        ('companies', '0005_auto_20200614_1141'),
        ('imprests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprestSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('settled_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlements', to='transactions.Transaction')),
            ],
            options={
                'ordering': ['-code'],
                'permissions': (('get.imprestSettlement', 'مشاهده تسویه تنخواه'), ('create.imprestSettlement', 'تعریف تسویه تنخواه'), ('update.imprestSettlement', 'ویرایش تسویه تنخواه'), ('delete.imprestSettlement', 'حذف تسویه تنخواه')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ImprestSettlementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlementItems', to='accounts.Account')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlementItemsAsCostCenter', to='accounts.FloatAccount')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlementItems', to='accounts.FloatAccount')),
                ('imprestSettlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imprests.ImprestSettlement')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='imprestcheckoutitem',
            name='account',
        ),
        migrations.RemoveField(
            model_name='imprestcheckoutitem',
            name='costCenter',
        ),
        migrations.RemoveField(
            model_name='imprestcheckoutitem',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='imprestcheckoutitem',
            name='floatAccount',
        ),
        migrations.RemoveField(
            model_name='imprestcheckoutitem',
            name='imprestCheckout',
        ),
        migrations.DeleteModel(
            name='ImprestCheckout',
        ),
        migrations.DeleteModel(
            name='ImprestCheckoutItem',
        ),
    ]
