# Generated by Django 2.2 on 2020-07-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0002_auto_20200712_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestsettlement',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imprestsettlement',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlement', to='transactions.Transaction'),
        ),
    ]
