# Generated by Django 2.2 on 2020-07-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0003_auto_20200712_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestsettlement',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlements', to='transactions.Transaction'),
        ),
    ]
