# Generated by Django 2.2 on 2020-07-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0007_auto_20200726_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestsettlement',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlement', to='transactions.Transaction'),
        ),
    ]
