# Generated by Django 2.2 on 2020-07-29 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imprests', '0009_auto_20200727_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imprestsettlement',
            options={'default_permissions': (), 'ordering': ['-code'], 'permissions': (('get.imprestSettlement', 'مشاهده تسویه تنخواه'), ('create.imprestSettlement', 'تعریف تسویه تنخواه'), ('update.imprestSettlement', 'ویرایش تسویه تنخواه'), ('delete.imprestSettlement', 'حذف تسویه تنخواه'), ('getOwn.imprestSettlement', 'مشاهده تسویه تنخواه های خود'), ('updateOwn.imprestSettlement', 'ویرایش تسویه تنخواه های خود'), ('deleteOwn.imprestSettlement', 'حذف تسویه تنخواه های خود'), ('firstConfirm.imprestSettlement', 'تایید اول تنخواه '), ('secondConfirm.imprestSettlement', 'تایید دوم تنخواه '), ('firstConfirmOwn.imprestSettlement', 'تایید اول تنخواه های خود'), ('secondConfirmOwn.imprestSettlement', 'تایید دوم تنخواه های خود'))},
        ),
        migrations.AddField(
            model_name='imprestsettlement',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='imprestsettlement',
            name='first_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_imprestsettlementConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imprestsettlement',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='imprestsettlement',
            name='second_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_imprestsettlementConfirmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
