# Generated by Django 2.2 on 2020-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0010_auto_20200729_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestsettlementitem',
            name='attachment',
            field=models.FileField(null=True, upload_to='imprestSettlementItem'),
        ),
    ]
