# Generated by Django 2.2 on 2020-08-09 05:55

from django.db import migrations, models
import imprests.models


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0011_imprestsettlementitem_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestsettlementitem',
            name='attachment',
            field=models.FileField(null=True, upload_to=imprests.models.upload_to),
        ),
    ]
