# Generated by Django 2.2 on 2020-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0012_auto_20200809_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestsettlement',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprestsettlementitem',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
