# Generated by Django 2.2 on 2020-08-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0013_auto_20200816_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestsettlement',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imprestsettlementitem',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
