# Generated by Django 2.2 on 2020-10-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0014_auto_20200816_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestsettlement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_imprestsettlement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imprestsettlementitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_imprestsettlementitem', to=settings.AUTH_USER_MODEL),
        ),
    ]
