# Generated by Django 2.2 on 2020-10-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0017_sanad_local_id'),
        ('imprests', '0015_auto_20201001_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestsettlement',
            name='sanad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlement', to='sanads.Sanad'),
        ),
    ]
