# Generated by Django 2.2 on 2020-10-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0016_imprestsettlement_sanad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestsettlement',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='imprestSettlement', to='transactions.Transaction'),
        ),
    ]
