# Generated by Django 2.2 on 2020-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0017_auto_20201007_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imprestsettlementitem',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': ()},
        ),
    ]
