# Generated by Django 2.2 on 2020-11-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0018_auto_20201107_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestsettlement',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imprestsettlement',
            name='first_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_imprestsettlementConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imprestsettlement',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imprestsettlement',
            name='second_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_imprestsettlementConfirmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
