# Generated by Django 2.2 on 2021-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprests', '0021_auto_20201118_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imprestsettlement',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-code'], 'permissions': (('get.imprestSettlement', 'مشاهده تسویه تنخواه'), ('create.imprestSettlement', 'تعریف تسویه تنخواه'), ('update.imprestSettlement', 'ویرایش تسویه تنخواه'), ('delete.imprestSettlement', 'حذف تسویه تنخواه'), ('getOwn.imprestSettlement', 'مشاهده تسویه تنخواه های خود'), ('updateOwn.imprestSettlement', 'ویرایش تسویه تنخواه های خود'), ('deleteOwn.imprestSettlement', 'حذف تسویه تنخواه های خود'), ('firstConfirm.imprestSettlement', 'تایید اول تنخواه '), ('secondConfirm.imprestSettlement', 'تایید دوم تنخواه '), ('firstConfirmOwn.imprestSettlement', 'تایید اول تنخواه های خود'), ('secondConfirmOwn.imprestSettlement', 'تایید دوم تنخواه های خود'))},
        ),
        migrations.AlterModelOptions(
            name='imprestsettlementitem',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': ()},
        ),
    ]
