# Generated by Django 2.2 on 2020-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200609_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (('get.receiveTransaction', 'مشاهده دریافت'), ('create.receiveTransaction', 'تعریف دریافت'), ('update.receiveTransaction', 'ویرایش دریافت'), ('delete.receiveTransaction', 'حذف دریافت'), ('get.paymentTransaction', 'مشاهده پرداخت'), ('create.paymentTransaction', 'تعریف پرداخت'), ('update.paymentTransaction', 'ویرایش پرداخت'), ('delete.paymentTransaction', 'حذف پرداخت'), ('get.imprestTransaction', 'مشاهده پرداخت تنخواه'), ('create.imprestTransaction', 'تعریف پرداخت تنخواه'), ('update.imprestTransaction', 'ویرایش پرداخت تنخواه'), ('delete.imprestTransaction', 'حذف پرداخت تنخواه'))},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('imprest', 'پرداخت تنخواه')], max_length=20),
        ),
    ]
