# Generated by Django 2.2 on 2020-07-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200719_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
    ]
