# Generated by Django 2.2 on 2020-07-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200726_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
