# Generated by Django 2.2 on 2020-07-29 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_auto_20200729_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='first_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_transactionConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='second_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_transactionConfirmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
