# Generated by Django 2.2 on 2020-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20201004_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionitem',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': ()},
        ),
    ]
