# Generated by Django 2.2 on 2020-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transactionitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
