# Generated by Django 2.2 on 2021-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20201118_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
