# Generated by Django 2.2 on 2021-07-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20210519_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['code'], 'permissions': (('get.receiveTransaction', 'مشاهده دریافت'), ('create.receiveTransaction', 'تعریف دریافت'), ('update.receiveTransaction', 'ویرایش دریافت'), ('delete.receiveTransaction', 'حذف دریافت'), ('define.receiveTransaction', 'قطعی کردن دریافت'), ('get.paymentTransaction', 'مشاهده پرداخت'), ('create.paymentTransaction', 'تعریف پرداخت'), ('update.paymentTransaction', 'ویرایش پرداخت'), ('delete.paymentTransaction', 'حذف پرداخت'), ('define.paymentTransaction', 'قطعی کردن پرداخت'), ('get.imprestTransaction', 'مشاهده پرداخت تنخواه'), ('create.imprestTransaction', 'تعریف پرداخت تنخواه'), ('update.imprestTransaction', 'ویرایش پرداخت تنخواه'), ('delete.imprestTransaction', 'حذف پرداخت تنخواه'), ('define.imprestTransaction', 'قعطی کردن پرداخت تنخواه'), ('getOwn.receiveTransaction', 'مشاهده دریافت های خود'), ('updateOwn.receiveTransaction', 'ویرایش دریافت های خود'), ('deleteOwn.receiveTransaction', 'حذف دریافت های خود'), ('defineOwn.receiveTransaction', 'قطعی کردن دریافت های خود'), ('getOwn.paymentTransaction', 'مشاهده پرداخت های خود'), ('updateOwn.paymentTransaction', 'ویرایش پرداخت های خود'), ('deleteOwn.paymentTransaction', 'حذف پرداخت های خود'), ('defineOwn.paymentTransaction', 'قطعی کردن پرداخت های خود'), ('getOwn.imprestTransaction', 'مشاهده پرداخت تنخواه های خود'), ('updateOwn.imprestTransaction', 'ویرایش پرداخت تنخواه های خود'), ('deleteOwn.imprestTransaction', 'حذف پرداخت تنخواه های خود'), ('defineOwn.imprestTransaction', 'قعطی کردن پرداخت تنخواه های خود'))},
        ),
    ]
