# Generated by Django 2.2 on 2021-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20210706_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['code'], 'permissions': (('get.receiveTransaction', 'مشاهده دریافت'), ('create.receiveTransaction', 'تعریف دریافت'), ('update.receiveTransaction', 'ویرایش دریافت'), ('delete.receiveTransaction', 'حذف دریافت'), ('define.receiveTransaction', 'قطعی کردن دریافت'), ('lock.receiveTransaction', 'قفل کردن دریافت'), ('get.paymentTransaction', 'مشاهده پرداخت'), ('create.paymentTransaction', 'تعریف پرداخت'), ('update.paymentTransaction', 'ویرایش پرداخت'), ('delete.paymentTransaction', 'حذف پرداخت'), ('define.paymentTransaction', 'قطعی کردن پرداخت'), ('lock.paymentTransaction', 'قفل کردن پرداخت'), ('get.imprestTransaction', 'مشاهده پرداخت تنخواه'), ('create.imprestTransaction', 'تعریف پرداخت تنخواه'), ('update.imprestTransaction', 'ویرایش پرداخت تنخواه'), ('delete.imprestTransaction', 'حذف پرداخت تنخواه'), ('define.imprestTransaction', 'قطعی کردن پرداخت تنخواه'), ('lock.imprestTransaction', 'قفل کردن پرداخت تنخواه'), ('getOwn.receiveTransaction', 'مشاهده دریافت های خود'), ('updateOwn.receiveTransaction', 'ویرایش دریافت های خود'), ('deleteOwn.receiveTransaction', 'حذف دریافت های خود'), ('defineOwn.receiveTransaction', 'قطعی کردن دریافت های خود'), ('lockOwn.receiveTransaction', 'قفل کردن دریافت های خود'), ('getOwn.paymentTransaction', 'مشاهده پرداخت های خود'), ('updateOwn:.paymentTransaction', 'ویرایش پرداخت های خود'), ('deleteOwn.paymentTransaction', 'حذف پرداخت های خود'), ('defineOwn.paymentTransaction', 'قطعی کردن پرداخت های خود'), ('lockOwn.paymentTransaction', 'قفل کردن پرداخت های خود'), ('getOwn.imprestTransaction', 'مشاهده پرداخت تنخواه های خود'), ('updateOwn.imprestTransaction', 'ویرایش پرداخت تنخواه های خود'), ('deleteOwn.imprestTransaction', 'حذف پرداخت تنخواه های خود'), ('defineOwn.imprestTransaction', 'قطعی کردن پرداخت تنخواه های خود'), ('lockOwn.imprestTransaction', 'قفل کردن پرداخت تنخواه های خود'))},
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
