# Generated by Django 2.2 on 2021-08-23 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20210718_1141'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0023_auto_20210815_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='banking_operation_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.CreateModel(
            name='BankingOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('get.bankingOperation', 'مشاهده عملیات های بانکی'), ('create.bankingOperation', 'تعریف عملیات های بانکی'), ('update.bankingOperation', 'ویرایش عملیات های بانکی'), ('delete.bankingOperation', 'حذف عملیات های بانکی'), ('getOwn.bankingOperation', 'مشاهده عملیات های بانکی خود'), ('updateOwn.bankingOperation', 'ویرایش عملیات های بانکی خود'), ('deleteOwn.bankingOperation', 'حذف عملیات های بانکی خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='bankingOperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.BankingOperations'),
        ),
    ]
