# Generated by Django 2.2 on 2021-08-23 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20210718_1141'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0024_auto_20210823_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankingOperations',
            new_name='BankingOperation',
        ),
    ]
