# Generated by Django 2.2 on 2021-09-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20210823_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('receive', 'دریافت'), ('payment', 'پرداخت'), ('imprest', 'پرداخت تنخواه'), ('bankTransfer', 'انتقال بین بانکی'), ('paymentGuarantee', 'اسناد ضمانتی پرداختی'), ('receivedGuarantee', 'اسناد ضمانتی دریافتی')], max_length=20),
        ),
    ]
