# Generated by Django 2.2 on 2021-09-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_auto_20210918_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactionItems', to='accounts.Account'),
        ),
    ]
