# Generated by Django 2.2 on 2020-07-19 12:42

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.accountBalanceReport', 'مشاهده تراز'), ('get.floatAccountBalanceByGroupReport', 'مشاهده تراز شناور بر اساس گروه'), ('get.floatAccountBalanceReport', 'مشاهده تراز شناور'), ('get.balanceSheetReport', 'مشاهده ترازنامه'), ('get.billReport', 'مشاهده صورت حساب تفصیلی'), ('get.buyReport', 'مشاهده گزارش خرید'), ('get.saleReport', 'مشاهده گزارش فروش'), ('get.incomeStatementReport', 'مشاهده گزارش سود و زیان تفصیلی'), ('get.wareInventoryReport', 'مشاهده کاردکس کالا'), ('get.allWaresInventoryReport', 'مشاهده کاردکس همه کالا ها'), ('get.warehouseInventoryReport', 'مشاهده کاردکس انبار'), ('get.allWarehousesInventoryReport', 'مشاهده کاردکس همه انبار ها'), ('get.journalReport', 'مشاهده دفتر روزنامه'), ('get.ledgerReport', 'مشاهده دفتر کل، معین، تفصیلی')),
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ExportVerifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.CharField(max_length=255)),
                ('form', models.CharField(choices=[('S', 'سند'), ('FB', 'فاکتور خرید'), ('FS', 'فاکتور فروش'), ('FBFB', 'فاکتور برگشت از خرید'), ('FBFS', 'فاکتور برگشت از فروش'), ('RT', 'رسید'), ('RC', 'حواله'), ('TR', 'دریافت'), ('TP', 'پرداخت'), ('t', 'انتقال')], max_length=4)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.exportVerifier', 'مشاهده تایید کنندگان خروجی'), ('create.exportVerifier', 'تعریف تایید کنندگان خروجی'), ('update.exportVerifier', 'ویرایش تایید کنندگان خروجی'), ('delete.exportVerifier', 'حذف تایید کنندگان خروجی')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
