# Generated by Django 2.0.5 on 2019-03-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportVerifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.CharField(max_length=255)),
                ('form', models.CharField(choices=[('S', 'سند'), ('FB', 'فاکتور خرید'), ('FS', 'فاکتور فروش'), ('FBFB', 'فاکتور برگشت از خرید'), ('FBFS', 'فاکتور برگشت از فروش'), ('RT', 'رسید'), ('RC', 'حواله'), ('TR', 'دریافت'), ('TP', 'پرداخت')], max_length=4)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
