# Generated by Django 2.0.5 on 2019-03-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportVerifiers',
            new_name='ExportVerifier',
        ),
    ]
