# Generated by Django 2.0.5 on 2019-04-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_exportverifier_source_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportverifier',
            name='source_id',
        ),
    ]
