# Generated by Django 2.2 on 2019-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_exportverifier_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportverifier',
            name='form',
            field=models.CharField(choices=[('S', 'سند'), ('FB', 'فاکتور خرید'), ('FS', 'فاکتور فروش'), ('FBFB', 'فاکتور برگشت از خرید'), ('FBFS', 'فاکتور برگشت از فروش'), ('RT', 'رسید'), ('RC', 'حواله'), ('TR', 'دریافت'), ('TP', 'پرداخت'), ('t', 'انتقال')], max_length=4),
        ),
    ]
