# Generated by Django 2.2 on 2020-03-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190603_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportverifier',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
    ]
