# Generated by Django 2.2 on 2020-04-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200307_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportverifier',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
    ]
