# Generated by Django 2.2 on 2020-10-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20200926_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportverifier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_exportverifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
