# Generated by Django 2.2 on 2020-11-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20201019_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportverifier',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.exportVerifier', 'مشاهده تایید کنندگان خروجی'), ('create.exportVerifier', 'تعریف تایید کنندگان خروجی'), ('update.exportVerifier', 'ویرایش تایید کنندگان خروجی'), ('delete.exportVerifier', 'حذف تایید کنندگان خروجی'))},
        ),
    ]
