# Generated by Django 2.2 on 2020-11-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_reportpermissions'),
    ]

    operations = [
        # - Model Report Does not exists
        #
        # migrations.DeleteModel(
        #     name='Report',
        # ),
    ]
