# Generated by Django 2.2 on 2020-12-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportverifier',
            name='form',
            field=models.CharField(choices=[('s', 'سند'), ('fb', 'فاکتور خرید'), ('fs', 'فاکتور فروش'), ('fbfb', 'فاکتور برگشت از خرید'), ('fbfs', 'فاکتور برگشت از فروش'), ('tr', 'دریافت'), ('tp', 'پرداخت'), ('t', 'انتقال'), ('cwr', 'حواله کالای مصرفی'), ('fpi', 'موجودی اول دوره'), ('ia', 'رسید تعدیل انبار'), ('oa', 'حواله تعدیل انبار')], max_length=4),
        ),
    ]
