# Generated by Django 2.2 on 2021-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20210103_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportverifier',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.exportVerifier', 'مشاهده تایید کنندگان خروجی'), ('create.exportVerifier', 'تعریف تایید کنندگان خروجی'), ('update.exportVerifier', 'ویرایش تایید کنندگان خروجی'), ('delete.exportVerifier', 'حذف تایید کنندگان خروجی'))},
        ),
    ]
