# Generated by Django 2.2 on 2021-03-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20210301_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportverifier',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('create.exportVerifier', 'تعریف تایید کنندگان خروجی'), ('get.exportVerifier', 'مشاهده تایید کنندگان خروجی'), ('update.exportVerifier', 'ویرایش تایید کنندگان خروجی'), ('delete.exportVerifier', 'حذف تایید کنندگان خروجی'), ('getOwn.exportVerifier', 'مشاهده تایید کنندگان خروجی خود'), ('updateOwn.exportVerifier', 'ویرایش تایید کنندگان خروجی خود'), ('deleteOwn.exportVerifier', 'حذف تایید کنندگان خروجی خود'))},
        ),
    ]
