# Generated by Django 2.2 on 2021-07-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20210428_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportPermissions',
            new_name='ReportsPermissions',
        ),
    ]
