# Generated by Django 2.2 on 2022-08-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_auto_20210710_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
