# Generated by Django 2.2 on 2020-07-19 12:42

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=255, unique=True)),
                ('usage', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.option', 'مشاهده تنظیمات'), ('update.option', 'ویرایش تنظیمات')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
