# Generated by Django 2.2 on 2020-07-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.option', 'مشاهده تنظیمات'), ('update.option', 'ویرایش تنظیمات'))},
        ),
        migrations.AlterField(
            model_name='option',
            name='codename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
