# Generated by Django 2.2 on 2020-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200701_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='usage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
