# Generated by Django 2.2 on 2020-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201001_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.option', 'مشاهده تنظیمات'), ('update.option', 'ویرایش تنظیمات'))},
        ),
    ]
