# Generated by Django 2.0.5 on 2018-07-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_auto_20180716_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('exp', models.TextField(blank=True, null=True)),
                ('usage', models.CharField(choices=[('receive', 'receive'), ('payment', 'payment'), ('both', 'both')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RPType', to='accounts.Account')),
            ],
        ),
    ]
