# Generated by Django 2.2 on 2020-07-19 12:42

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='شماره سند')),
                ('explanation', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('temporary', 'موقت'), ('definite', 'قطعی')], max_length=20)),
                ('createType', models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی')], default='manual', max_length=20, verbose_name='نوع ثبت')),
                ('bed', models.DecimalField(decimal_places=0, default=0, max_digits=24, verbose_name='بدهکار')),
                ('bes', models.DecimalField(decimal_places=0, default=0, max_digits=24, verbose_name='بستانکار')),
            ],
            options={
                'ordering': ['-code'],
                'permissions': (('get.sanad', 'مشاهده سند'), ('create.sanad', 'تعریف سند'), ('update.sanad', 'ویرایش سند'), ('delete.sanad', 'حذف سند'), ('reorder.sanad', 'مرتب کردن کد اسناد بر اساس تاریخ')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SanadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('bed', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('bes', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('explanation', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanadItems', to='accounts.Account', verbose_name='حساب')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanadItemsAsCostCenter', to='accounts.FloatAccount', verbose_name='مرکز هزینه')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
