# Generated by Django 2.0.5 on 2019-03-10 09:19

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cheques', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='شماره سند')),
                ('explanation', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('temporary', 'موقت'), ('definite', 'قطعی')], max_length=20)),
                ('createType', models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی')], default='manual', max_length=20, verbose_name='نوع ثبت')),
                ('bed', models.DecimalField(decimal_places=0, default=0, max_digits=24, verbose_name='بدهکار')),
                ('bes', models.DecimalField(decimal_places=0, default=0, max_digits=24, verbose_name='بستانکار')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='SanadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=24)),
                ('valueType', models.CharField(choices=[('bed', 'bed'), ('bes', 'bes')], max_length=3)),
                ('explanation', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanadItems', to='accounts.Account', verbose_name='حساب')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.CostCenter', verbose_name='مرکز هزینه')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanadItems', to='accounts.FloatAccount', verbose_name='حساب شناور')),
                ('sanad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sanads.Sanad', verbose_name='سند')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date', django_jalali.db.models.jDateField()),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('receive', 'receive'), ('payment', 'payment')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.Account')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.FloatAccount')),
                ('sanad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='sanads.Sanad')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=24)),
                ('date', django_jalali.db.models.jDateField()),
                ('due', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('documentNumber', models.CharField(blank=True, max_length=50)),
                ('bankName', models.CharField(blank=True, max_length=255)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactionItems', to='accounts.Account')),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionItem', to='cheques.Cheque')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactionItems', to='accounts.FloatAccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sanads.Transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.DefaultAccount')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('code', 'type')},
        ),
    ]
