# Generated by Django 2.2 on 2020-06-09 07:54

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False),
        ),
    ]
