# Generated by Django 2.0.5 on 2019-03-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='cheque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionItem', to='cheques.Cheque'),
        ),
    ]
