# Generated by Django 2.0.5 on 2018-09-22 09:32

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='bed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24, verbose_name='بدهکار'),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='bes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24, verbose_name='بستانکار'),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='createType',
            field=models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی')], default='manual', max_length=20, verbose_name='نوع ثبت'),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='explanation',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='type',
            field=models.CharField(choices=[('temporary', 'موقت'), ('definite', 'قطعی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sanaditem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanadItems', to='accounts.Account', verbose_name='حساب'),
        ),
        migrations.AlterField(
            model_name='sanaditem',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.CostCenter', verbose_name='مرکز هزینه'),
        ),
        migrations.AlterField(
            model_name='sanaditem',
            name='explanation',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='sanaditem',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='floatAccount', to='accounts.FloatAccount', verbose_name='حساب شناور'),
        ),
        migrations.AlterField(
            model_name='sanaditem',
            name='sanad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sanads.Sanad', verbose_name='سند'),
        ),
    ]
