# Generated by Django 2.0.5 on 2018-07-27 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bank'),
        ('sanads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('temporary', 'temporary'), ('definite', 'definite')], max_length=20)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SanadItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('bed', models.DecimalField(blank=True, decimal_places=0, max_digits=24, null=True)),
                ('bes', models.DecimalField(blank=True, decimal_places=0, max_digits=24, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanadItems', to='accounts.Account')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.CostCenter')),
                ('sanad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sanads.Sanad')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sanads.RPType')),
            ],
        ),
    ]
