# Generated by Django 2.0.5 on 2019-04-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0002_auto_20190330_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanaditem',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='transactionitem',
            options={'default_permissions': ()},
        ),
    ]
