# Generated by Django 2.0.5 on 2018-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0002_auto_20180922_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sanad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='sanads.Sanad'),
        ),
    ]
