# Generated by Django 2.0.5 on 2018-07-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bank'),
        ('sanads', '0002_sanad_sanaditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=24)),
                ('valueType', models.CharField(choices=[('bed', 'bed'), ('bes', 'bes')], max_length=3)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanadItems', to='accounts.Account')),
                ('costCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.CostCenter')),
                ('sanad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sanads.Sanad')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sanads.RPType')),
            ],
        ),
        migrations.RemoveField(
            model_name='sanaditems',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sanaditems',
            name='costCenter',
        ),
        migrations.RemoveField(
            model_name='sanaditems',
            name='sanad',
        ),
        migrations.RemoveField(
            model_name='sanaditems',
            name='type',
        ),
        migrations.DeleteModel(
            name='SanadItems',
        ),
    ]
