# Generated by Django 2.2 on 2020-07-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0003_auto_20200719_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'default_permissions': (), 'ordering': ['-code'], 'permissions': (('get.sanad', 'مشاهده سند'), ('create.sanad', 'تعریف سند'), ('update.sanad', 'ویرایش سند'), ('delete.sanad', 'حذف سند'), ('getOwn.sanad', 'مشاهده سند های خود'), ('updateOwn.sanad', 'ویرایش سند های خود'), ('deleteOwn.sanad', 'حذف سند های خود'), ('reorder.sanad', 'مرتب کردن کد اسناد بر اساس تاریخ'))},
        ),
    ]
