# Generated by Django 2.0.5 on 2019-04-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_financialyear_is_active'),
        ('sanads', '0003_auto_20190404_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'default_permissions': (), 'ordering': ['-code']},
        ),
        migrations.AddField(
            model_name='sanad',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sanads', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanaditem',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sanad_items', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
