# Generated by Django 2.0.5 on 2019-02-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0003_auto_20181017_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanaditem',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanadItems', to='accounts.FloatAccount', verbose_name='حساب شناور'),
        ),
    ]
