# Generated by Django 2.0.5 on 2018-07-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bank'),
        ('sanads', '0003_auto_20180727_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanaditem',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='floatAccount', to='accounts.FloatAccount'),
        ),
        migrations.AlterField(
            model_name='sanaditem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='accounts.Account'),
        ),
    ]
