# Generated by Django 2.0.5 on 2019-04-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_financialyear_is_active'),
        ('sanads', '0004_auto_20190404_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': (), 'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactionItems', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
