# Generated by Django 2.0.5 on 2019-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0005_auto_20190404_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanad',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sanaditem',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
