# Generated by Django 2.0.5 on 2018-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0005_auto_20180729_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='date',
            field=models.DateField(default='2018-03-07'),
            preserve_default=False,
        ),
    ]
