# Generated by Django 2.2 on 2020-07-28 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanads', '0006_auto_20200726_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'default_permissions': (), 'ordering': ['-code'], 'permissions': (('get.sanad', 'مشاهده سند'), ('create.sanad', 'تعریف سند'), ('update.sanad', 'ویرایش سند'), ('delete.sanad', 'حذف سند'), ('getOwn.sanad', 'مشاهده سند های خود'), ('updateOwn.sanad', 'ویرایش سند های خود'), ('deleteOwn.sanad', 'حذف سند های خود'), ('firstConfirm.sanad', 'تایید اول سند'), ('secondConfirm.sanad', 'تایید دوم سند'), ('firstConfirmOwn.sanad', 'تایید اول سند های خود'), ('secondConfirmOwn.sanad', 'تایید دوم سند های خود'), ('reorder.sanad', 'مرتب کردن کد اسناد بر اساس تاریخ'))},
        ),
        migrations.AddField(
            model_name='sanad',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sanad',
            name='first_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firstsanadConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanad',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sanad',
            name='second_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondsanadConfirmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
