# Generated by Django 2.0.5 on 2019-04-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0006_auto_20190409_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanad',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='sanaditem',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='source_id',
        ),
    ]
