# Generated by Django 2.0.5 on 2018-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0006_transactionitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sanaditem',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
