# Generated by Django 2.2 on 2020-02-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0007_auto_20190410_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanaditem',
            name='value',
        ),
        migrations.RemoveField(
            model_name='sanaditem',
            name='valueType',
        ),
        migrations.AddField(
            model_name='sanaditem',
            name='bed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='sanaditem',
            name='bes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
    ]
