# Generated by Django 2.0.5 on 2018-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0007_auto_20180730_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='documentNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
