# Generated by Django 2.0.5 on 2018-07-30 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bank'),
        ('sanads', '0008_transactionitem_documentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.FloatAccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.datetime.now),
        ),
    ]
