# Generated by Django 2.0.5 on 2018-07-30 13:30

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0009_auto_20180730_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='created_at',
            field=django_jalali.db.models.jDateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='updated_at',
            field=django_jalali.db.models.jDateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=django_jalali.db.models.jDateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=django_jalali.db.models.jDateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
