# Generated by Django 2.2 on 2020-08-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0009_auto_20200820_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanad',
            name='type',
        ),
    ]
