# Generated by Django 2.2 on 2020-03-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0009_auto_20200303_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanaditem',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='transactionitem',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
    ]
