# Generated by Django 2.2 on 2020-03-09 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0010_auto_20200307_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanaditem',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.FloatAccount', verbose_name='مرکز هزینه'),
        ),
    ]
