# Generated by Django 2.0.5 on 2018-07-31 04:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0010_auto_20180730_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
