# Generated by Django 2.2 on 2020-08-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0010_remove_sanad_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanad',
            name='createType',
        ),
    ]
