# Generated by Django 2.2 on 2020-08-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0011_remove_sanad_createtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanaditem',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanadItemsAsCostCenter', to='accounts.FloatAccount', verbose_name='مرکز هزینه و درآمد'),
        ),
    ]
