# Generated by Django 2.0.5 on 2018-08-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0011_auto_20180731_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanad',
            name='createType',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], default='auto', max_length=20),
            preserve_default=False,
        ),
    ]
