# Generated by Django 2.2 on 2020-03-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0011_auto_20200309_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
