# Generated by Django 2.2 on 2020-09-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0012_auto_20200827_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='is_auto_created',
            field=models.BooleanField(default=True),
        ),
    ]
