# Generated by Django 2.0.5 on 2018-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0012_sanad_createtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanad',
            name='bed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='sanad',
            name='bes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
    ]
