# Generated by Django 2.2 on 2020-03-10 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0012_auto_20200310_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanaditem',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanadItemsAsCostCenter', to='accounts.FloatAccount', verbose_name='مرکز هزینه'),
        ),
    ]
