# Generated by Django 2.0.5 on 2018-08-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0013_auto_20180809_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='createType',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], default='manual', max_length=20),
        ),
    ]
