# Generated by Django 2.2 on 2020-09-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0013_auto_20200916_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'default_permissions': (), 'ordering': ['-code'], 'permissions': (('get.sanad', 'مشاهده سند'), ('create.sanad', 'تعریف سند'), ('update.sanad', 'ویرایش سند'), ('getOwn.sanad', 'مشاهده سند های خود'), ('updateOwn.sanad', 'ویرایش سند های خود'), ('firstConfirm.sanad', 'تایید اول سند'), ('secondConfirm.sanad', 'تایید دوم سند'), ('firstConfirmOwn.sanad', 'تایید اول سند های خود'), ('secondConfirmOwn.sanad', 'تایید دوم سند های خود'), ('reorder.sanad', 'مرتب کردن کد اسناد بر اساس تاریخ'))},
        ),
    ]
