# Generated by Django 2.2 on 2020-03-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_defaultaccount_costcenter'),
        ('sanads', '0013_auto_20200310_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactionsAsCostCenter', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactionItemsAsCostCenter', to='accounts.FloatAccount'),
        ),
    ]
