# Generated by Django 2.2 on 2020-10-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0014_auto_20200921_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_sanad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sanaditem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_sanaditem', to=settings.AUTH_USER_MODEL),
        ),
    ]
