# Generated by Django 2.0.5 on 2018-08-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bank'),
        ('sanads', '0014_auto_20180811_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('exp', models.TextField(blank=True, null=True)),
                ('usage', models.CharField(choices=[('receive', 'receive'), ('payment', 'payment'), ('both', 'both')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RPType', to='accounts.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='rptype',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sanaditem',
            name='type',
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sanads.DefaultAccount'),
        ),
        migrations.DeleteModel(
            name='RPType',
        ),
    ]
