# Generated by Django 2.0.5 on 2018-08-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0015_auto_20180814_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultaccount',
            old_name='exp',
            new_name='explanation',
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='programingName',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='defaultaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defaultAccount', to='accounts.Account'),
        ),
    ]
