# Generated by Django 2.2 on 2020-10-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20201001_1533'),
        ('sanads', '0015_auto_20201001_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sanad',
            unique_together={('code', 'financial_year')},
        ),
    ]
