# Generated by Django 2.2 on 2020-03-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0015_auto_20200315_1954'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sanad',
            unique_together=set(),
        ),
    ]
