# Generated by Django 2.0.5 on 2018-08-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0016_auto_20180814_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'ordering': ['-code']},
        ),
    ]
