# Generated by Django 2.2 on 2020-10-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0016_auto_20201004_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanad',
            name='local_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
