# Generated by Django 2.2 on 2020-04-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0016_auto_20200322_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'ordering': ['-code'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='sanaditem',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['code'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='transactionitem',
            options={'ordering': ['pk'], 'permissions': ()},
        ),
    ]
