# Generated by Django 2.2 on 2020-04-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0017_auto_20200422_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'default_permissions': (), 'ordering': ['-code'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='sanaditem',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='transactionitem',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': ()},
        ),
    ]
