# Generated by Django 2.0.5 on 2018-08-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0017_auto_20180817_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultaccount',
            name='account',
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.DefaultAccount'),
        ),
        migrations.DeleteModel(
            name='DefaultAccount',
        ),
    ]
