# Generated by Django 2.2 on 2020-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0017_sanad_local_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanaditem',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': ()},
        ),
    ]
