# Generated by Django 2.2 on 2020-04-24 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sanads', '0018_auto_20200422_1930'),
    ]

    database_operations = [
        migrations.AlterModelTable('Transaction', 'transactions_transaction'),
        migrations.AlterModelTable('TransactionItem', 'transactions_transactionitem')
    ]

    state_operations = [
        migrations.DeleteModel('Transaction'),
        migrations.DeleteModel('TransactionItem')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
