# Generated by Django 2.2 on 2020-04-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0019_auto_20200424_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'default_permissions': (), 'ordering': ['-code'], 'permissions': (('get.sanad', 'مشاهده سند'), ('create.sanad', 'تعریف سند'), ('update.sanad', 'ویرایش سند'), ('delete.sanad', 'حذف سند'), ('reorder.sanad', 'مرتب کردن کد اسناد بر اساس تاریخ'))},
        ),
    ]
