# Generated by Django 2.0.5 on 2018-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0020_auto_20180824_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='bankName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
