# Generated by Django 2.0.5 on 2018-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0021_transactionitem_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('code', 'type')},
        ),
    ]
