# Generated by Django 2.2 on 2020-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0021_auto_20201118_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanaditem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
