# Generated by Django 2.2 on 2020-12-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0022_auto_20201118_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanaditem',
            options={'default_permissions': (), 'ordering': ('order', 'pk'), 'permissions': ()},
        ),
    ]
