# Generated by Django 2.2 on 2021-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0026_auto_20210519_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanad',
            name='type',
            field=models.CharField(choices=[('o', 'افتتاحیه'), ('c', 'اختتامیه'), ('n', 'عادی')], default='n', max_length=3),
        ),
    ]
