# Generated by Django 2.2 on 2021-07-04 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanads', '0027_sanad_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-code'], 'permissions': (('get.sanad', 'مشاهده سند'), ('create.sanad', 'تعریف سند'), ('update.sanad', 'ویرایش سند'), ('getOwn.sanad', 'مشاهده سند های خود'), ('updateOwn.sanad', 'ویرایش سند های خود'), ('firstConfirm.sanad', 'تایید اول سند'), ('secondConfirm.sanad', 'تایید دوم سند'), ('firstConfirmOwn.sanad', 'تایید اول سند های خود'), ('secondConfirmOwn.sanad', 'تایید دوم سند های خود'), ('reorder.sanad', 'مرتب کردن کد اسناد بر اساس تاریخ'), ('define.sanad', 'قطعی کردن سند'))},
        ),
        migrations.AddField(
            model_name='sanad',
            name='defined_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanad',
            name='definition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanad',
            name='is_definite',
            field=models.BooleanField(default=False),
        ),
    ]
