# Generated by Django 2.2 on 2021-07-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0028_auto_20210704_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanad',
            old_name='is_definite',
            new_name='is_defined',
        ),
    ]
