# Generated by Django 2.2 on 2021-07-06 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanads', '0029_auto_20210704_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanad',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-code'], 'permissions': (('create.sanad', 'تعریف سند'), ('get.sanad', 'مشاهده سند'), ('update.sanad', 'ویرایش سند'), ('define.sanad', 'قطعی کردن سند'), ('lock.sanad', 'قفل کردن سند'), ('getOwn.sanad', 'مشاهده سند های خود'), ('updateOwn.sanad', 'ویرایش سند های خود'), ('defineOwn.sanad', 'قطعی کردن سند های خود'), ('lockOwn.sanad', 'قفل کردن سند های خود'), ('reorder.sanad', 'مرتب کردن کد اسناد بر اساس تاریخ'))},
        ),
        migrations.AddField(
            model_name='sanad',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanad',
            name='lock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanad',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
