# Generated by Django 2.2 on 2021-07-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sanads', '0030_auto_20210706_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanad',
            name='origin_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sanad',
            name='origin_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanaditem',
            name='origin_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sanaditem',
            name='origin_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
