# Generated by Django 2.2 on 2021-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0033_auto_20211017_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanaditem',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
