# Generated by Django 2.0.5 on 2019-02-18 06:57

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('start', django_jalali.db.models.jDateField()),
                ('end', django_jalali.db.models.jDateField()),
                ('is_active', models.BooleanField(default=0)),
                ('explanation', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='fiscal_year_end',
        ),
        migrations.RemoveField(
            model_name='company',
            name='fiscal_year_start',
        ),
        migrations.AddField(
            model_name='financialyear',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_years', to='companies.Company'),
        ),
    ]
