# Generated by Django 2.0.5 on 2019-04-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='is_active',
        ),
    ]
