# Generated by Django 2.0.5 on 2018-07-31 04:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fiscal_year_end',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='fiscal_year_start',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
