# Generated by Django 2.2 on 2020-04-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanads', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='currentEarningsClosingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsCurrentEarningsClosingSanad', to='sanads.Sanad'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='openingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsOpeningSanad', to='sanads.Sanad'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='permanentsClosingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsPermanentsClosingSanad', to='sanads.Sanad'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='temporaryClosingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsTemporaryClosingSanad', to='sanads.Sanad'),
        ),
    ]
