# Generated by Django 2.2 on 2020-04-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200424_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.company', 'مشاهده شرکت'), ('create.company', 'تعریف شرکت'), ('update.company', 'ویرایش شرکت'), ('delete.company', 'حذف شرکت'))},
        ),
        migrations.AlterModelOptions(
            name='financialyear',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.financialYear', 'مشاهده سال مالی'), ('create.financialYear', 'تعریف سال مالی'), ('update.financialYear', 'ویرایش سال مالی'), ('delete.financialYear', 'حذف سال مالی'), ('move.financialYear', 'انتقال سال مالی'), ('close.financialYear', 'بستن سال مالی'), ('cancelClosing.financialYear', 'لغو بستن سال مالی'))},
        ),
    ]
