# Generated by Django 2.0.5 on 2019-04-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190409_1655'),
        ('companies', '0002_remove_financialyear_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='accounts',
            field=models.ManyToManyField(related_name='financial_year', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='cost_center_groups',
            field=models.ManyToManyField(related_name='financial_year', to='accounts.CostCenterGroup'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='cost_centers',
            field=models.ManyToManyField(related_name='financial_year', to='accounts.CostCenter'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='float_account_groups',
            field=models.ManyToManyField(related_name='financial_year', to='accounts.FloatAccountGroup'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='float_accounts',
            field=models.ManyToManyField(related_name='financial_year', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='independent_account',
            field=models.ManyToManyField(related_name='financial_year', to='accounts.IndependentAccount'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='persons',
            field=models.ManyToManyField(related_name='financial_year', to='accounts.Person'),
        ),
    ]
