# Generated by Django 2.2 on 2020-06-13 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200424_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='explanation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول کد پستی باید 11 رقم باشد', regex='^.{11}$')]),
        ),
    ]
