# Generated by Django 2.2 on 2020-06-14 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200613_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول کد پستی باید 10 رقم باشد', regex='^.{10}$')]),
        ),
    ]
