# Generated by Django 2.2 on 2020-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20200726_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
