# Generated by Django 2.0.5 on 2019-04-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20190410_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialyear',
            old_name='unit',
            new_name='units',
        ),
    ]
