# Generated by Django 2.0.5 on 2019-04-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190410_1641'),
        ('companies', '0009_auto_20190410_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='float_account_relations',
            field=models.ManyToManyField(blank=True, related_name='financial_year', to='accounts.FloatAccountRelation'),
        ),
    ]
