# Generated by Django 2.2 on 2020-08-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20200816_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialyear',
            options={'default_permissions': (), 'ordering': ('-id',), 'permissions': (('get.financialYear', 'مشاهده سال مالی'), ('create.financialYear', 'تعریف سال مالی'), ('update.financialYear', 'ویرایش سال مالی'), ('delete.financialYear', 'حذف سال مالی'), ('move.financialYear', 'انتقال سال مالی'), ('close.financialYear', 'بستن سال مالی'), ('cancelClosing.financialYear', 'لغو بستن سال مالی'), ('getOwn.financialYear', 'مشاهده سال های مالی خود'), ('updateOwn.financialYear', 'ویرایش سال های مالی خود'), ('deleteOwn.financialYear', 'حذف سال های مالی خود'), ('moveOwn.financialYear', 'انتقال سال های مالی خود'), ('closeOwn.financialYear', 'بستن سال های مالی خود'), ('cancelClosingOwn.financialYear', 'لغو بستن سال های مالی خود'))},
        ),
    ]
