# Generated by Django 2.0.5 on 2019-04-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_financialyear_float_account_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='float_account_relations',
        ),
    ]
