# Generated by Django 2.2 on 2020-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='financialyear',
            unique_together={('company', 'name')},
        ),
    ]
