# Generated by Django 2.2 on 2019-04-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190411_1337'),
        ('companies', '0011_remove_financialyear_float_account_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='float_account_relations',
            field=models.ManyToManyField(blank=True, related_name='financial_year', to='accounts.FloatAccountRelation'),
        ),
    ]
