# Generated by Django 2.2 on 2020-03-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_financialyear_float_account_relations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialyear',
            old_name='default_accounts',
            new_name='defaultAccounts',
        ),
        migrations.RenameField(
            model_name='financialyear',
            old_name='float_account_groups',
            new_name='floatAccountGroups',
        ),
        migrations.RenameField(
            model_name='financialyear',
            old_name='float_account_relations',
            new_name='floatAccountRelations',
        ),
        migrations.RenameField(
            model_name='financialyear',
            old_name='float_accounts',
            new_name='floatAccounts',
        ),
        migrations.RenameField(
            model_name='financialyear',
            old_name='ware_levels',
            new_name='wareLevels',
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='banks',
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='cost_center_groups',
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='cost_centers',
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='independent_accounts',
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='persons',
        ),
    ]
