# Generated by Django 2.2 on 2020-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20201001_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.company', 'مشاهده شرکت'), ('create.company', 'تعریف شرکت'), ('update.company', 'ویرایش شرکت'), ('delete.company', 'حذف شرکت'), ('getOwn.company', 'مشاهده شرکت های خود'), ('updateOwn.company', 'ویرایش شرکت های خود'), ('deleteOwn.company', 'حذف شرکت های خود'))},
        ),
    ]
