# Generated by Django 2.2 on 2021-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20201107_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='warehouse_system',
            field=models.CharField(choices=[('a', 'ادواری'), ('d', 'دائمی')], default='d', max_length=2),
        ),
    ]
