# Generated by Django 2.2 on 2021-01-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_financialyear_warehouse_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='warehouse_system',
            field=models.CharField(choices=[('a', 'ادواری'), ('d', 'دائمی')], max_length=2),
        ),
    ]
