# Generated by Django 2.2 on 2020-03-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0014_auto_20200310_1326'),
        ('companies', '0015_financialyear_closingsanad'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='openingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financialYearAsOpeningSanad', to='sanads.Sanad'),
        ),
    ]
