# Generated by Django 2.2 on 2020-03-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_financialyear_openingsanad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='closingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsClosingSanad', to='sanads.Sanad'),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='openingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsOpeningSanad', to='sanads.Sanad'),
        ),
    ]
