# Generated by Django 2.2 on 2021-01-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20210103_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='are_factors_sorted',
            field=models.BooleanField(default=False),
        ),
    ]
