# Generated by Django 2.2 on 2021-01-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_financialyear_are_factors_sorted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='are_factors_sorted',
            field=models.BooleanField(default=True),
        ),
    ]
