# Generated by Django 2.2 on 2020-04-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0016_auto_20200322_1742'),
        ('companies', '0017_auto_20200316_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='closingSanad',
        ),
        migrations.AddField(
            model_name='financialyear',
            name='currentEarningsClosingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsCurrentEarningsClosingSanad', to='sanads.Sanad'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='permanentsClosingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsPermanentsClosingSanad', to='sanads.Sanad'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='temporaryClosingSanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialYearAsTemporaryClosingSanad', to='sanads.Sanad'),
        ),
    ]
