# Generated by Django 2.2 on 2021-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_auto_20210104_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.company', 'مشاهده شرکت'), ('create.company', 'تعریف شرکت'), ('update.company', 'ویرایش شرکت'), ('delete.company', 'حذف شرکت'), ('getOwn.company', 'مشاهده شرکت های خود'), ('updateOwn.company', 'ویرایش شرکت های خود'), ('deleteOwn.company', 'حذف شرکت های خود'))},
        ),
        migrations.AlterModelOptions(
            name='financialyear',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ('-id',), 'permissions': (('get.financialYear', 'مشاهده سال مالی'), ('create.financialYear', 'تعریف سال مالی'), ('update.financialYear', 'ویرایش سال مالی'), ('delete.financialYear', 'حذف سال مالی'), ('move.financialYear', 'انتقال سال مالی'), ('close.financialYear', 'بستن سال مالی'), ('cancelClosing.financialYear', 'لغو بستن سال مالی'), ('getOwn.financialYear', 'مشاهده سال های مالی خود'), ('updateOwn.financialYear', 'ویرایش سال های مالی خود'), ('deleteOwn.financialYear', 'حذف سال های مالی خود'), ('moveOwn.financialYear', 'انتقال سال های مالی خود'), ('closeOwn.financialYear', 'بستن سال های مالی خود'), ('cancelClosingOwn.financialYear', 'لغو بستن سال های مالی خود'))},
        ),
    ]
