# Generated by Django 2.2 on 2020-04-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20200419_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': ()},
        ),
    ]
