# Generated by Django 2.2 on 2020-04-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20200422_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('get.company', 'مشاهده شرکت'), ('create.company', 'تعریف شرکت'), ('update.company', 'ویرایش شرکت'), ('delete.company', 'حذف شرکت'))},
        ),
        migrations.AlterModelOptions(
            name='financialyear',
            options={'permissions': (('get.financialYear', 'مشاهده سال مالی'), ('create.financialYear', 'تعریف سال مالی'), ('update.financialYear', 'ویرایش سال مالی'), ('delete.financialYear', 'حذف سال مالی'), ('move.financialYear', 'انتقال سال مالی'), ('close.financialYear', 'بستن سال مالی'), ('cancelClosing.financialYear', 'لغو بستن سال مالی'))},
        ),
    ]
