# Generated by Django 2.2 on 2021-04-14 08:18

from django.db import migrations, models
import helpers.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20210301_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(null=True, upload_to=helpers.models.upload_to),
        ),
    ]
