# Generated by Django 2.2 on 2021-05-08 09:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_auto_20210413_1008'),
        ('companies', '0022_auto_20210414_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='modules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='superuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_as_superuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyUsers', to='companies.Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, related_name='companyUsers', to='users.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyUsers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='companies', through='companies.CompanyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
