# Generated by Django 2.2 on 2021-05-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_auto_20210508_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='financialYears',
            field=models.ManyToManyField(related_name='companyUsers', to='companies.FinancialYear'),
        ),
    ]
