# Generated by Django 2.2 on 2021-05-11 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_auto_20210413_1008'),
        ('companies', '0024_companyuser_financialyears'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together={('company', 'user')},
        ),
        migrations.CreateModel(
            name='CompanyUserInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150)),
                ('confirmation_code', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyUserInvitations', to='companies.Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('financialYears', models.ManyToManyField(related_name='companyUserInvitations', to='companies.FinancialYear')),
                ('roles', models.ManyToManyField(blank=True, related_name='companyUserInvitations', to='users.Role')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
                'unique_together': {('company', 'username')},
            },
        ),
    ]
