# Generated by Django 2.2 on 2021-05-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_auto_20210511_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserinvitation',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
