# Generated by Django 2.2 on 2021-05-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_companyuserinvitation_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuserinvitation',
            name='is_registered',
        ),
        migrations.AddField(
            model_name='companyuserinvitation',
            name='status',
            field=models.CharField(choices=[('p', 'در انتظار بررسی'), ('a', 'تایید شده'), ('r', 'رد شده')], default='p', max_length=1),
        ),
    ]
