# Generated by Django 2.2 on 2021-05-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_auto_20210516_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyuserinvitation',
            unique_together=set(),
        ),
    ]
