# Generated by Django 2.2 on 2021-06-12 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0028_auto_20210516_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYearOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('operation', models.CharField(choices=[('m', 'انتقال'), ('c', 'بستن'), ('cm', 'بستن و انتقال')], max_length=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fromFinancialYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='companies.FinancialYear')),
                ('toFinancialYear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
