# Generated by Django 2.2 on 2021-06-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_financialyearoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyearoperation',
            name='operation',
            field=models.CharField(choices=[('m', 'انتقال'), ('c', 'بستن'), ('cm', 'بستن و انتقال'), ('cc', 'لغو بستن')], max_length=2),
        ),
    ]
