# Generated by Django 2.2 on 2022-11-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofpay',
            name='company',
        ),
        migrations.RemoveField(
            model_name='listofpayitem',
            name='company',
        ),
    ]
