# Generated by Django 2.2 on 2022-08-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnelfamily',
            old_name='Personnel',
            new_name='personnel',
        ),
        migrations.RenameField(
            model_name='workshoppersonnel',
            old_name='Personnel',
            new_name='personnel',
        ),
        migrations.RemoveField(
            model_name='personnelfamily',
            name='row',
        ),
        migrations.AddField(
            model_name='personnel',
            name='location_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='location_of_exportation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='sector_of_exportation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='degree_of_education',
            field=models.CharField(choices=[('un', 'زیر دیپلم'), ('di', 'دیپلم'), ('as', 'کاردانی'), ('ba', 'لیسانس'), ('ma', 'فوق لیسانس'), ('do', 'دکترا'), ('pd', 'فوق دکترا')], default='di', max_length=2),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='contract_type',
            field=models.CharField(choices=[('p', 'پاره وقت'), ('f', 'تمام وقت'), ('t', 'موقت'), ('h', 'ساعتی'), ('c', 'پیمانی')], default='f', max_length=2),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='employee_status',
            field=models.CharField(choices=[('nr', 'معمولی'), ('fc', 'فرزند شهید'), ('st', 'جانباز'), ('fr', 'آزاده'), ('ar', 'نیروهای مسلح'), ('bn', 'مشمولین بند چهارده ماده نود و هفت'), ('fo', 'اتباع خارجی مشمول قانون اجتناب از اخذ مالیات مضاعف')], default='nr', max_length=2),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='employment_type',
            field=models.CharField(choices=[('c', 'پیمانی'), ('co', 'قراردادی'), ('cr', 'َشرکتی'), ('fu', 'مامور'), ('or', 'سایر'), ('p', 'رسمی')], default='co', max_length=2),
        ),
    ]
