# Generated by Django 2.2 on 2022-10-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='contract_row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
