# Generated by Django 2.2 on 2022-09-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
