# Generated by Django 2.2 on 2022-12-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
