# Generated by Django 2.2 on 2022-09-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_delete_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='current_insurance_history_in_workshop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='insurance_history_totality',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='job_group',
            field=models.CharField(choices=[('st', 'آموزشي و فرهنگي'), ('fn', 'اداري و مالي'), ('so', 'اموراجتماعي'), ('he', 'درماني و بهداشتي'), ('it', 'اطلاعات فناوري'), ('se', 'خدمات'), ('en', 'فني و مهندسي'), ('ar', 'كشاورزي ومحيط زيست'), ('pr', 'تولیدی'), ('sr', 'تحقیقاتی'), ('wo', 'کارگری'), ('sc', 'حراست و نگهبانی'), ('tr', 'ترابری'), ('sa', 'بازاریابی و فروش'), ('ju', 'قضات'), ('wa', 'انبارداری'), ('co', 'کنترل کیفی'), ('ma', 'هیات علمی'), ('ot', 'سایر')], max_length=2),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='job_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='previous_insurance_history_in_workshop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='previous_insurance_history_out_workshop',
            field=models.IntegerField(default=0),
        ),
    ]
