# Generated by Django 2.2 on 2022-11-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20221130_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpayitem',
            name='haghe_sanavat_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='padash_total',
            field=models.IntegerField(default=0),
        ),
    ]
