# Generated by Django 2.2 on 2022-10-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20221023_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='contract_row',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='branch_code',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
