# Generated by Django 2.2 on 2022-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_contractrow_use_in_insurance_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='location_of_foreign_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
