# Generated by Django 2.2 on 2022-10-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20221023_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='branch_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
