# Generated by Django 2.2 on 2022-12-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20221130_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='postal_code',
            field=models.IntegerField(default=0),
        ),
    ]
