# Generated by Django 2.2 on 2022-09-03 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0003_auto_20220903_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='current_insurance_history_in_workshop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='insurance_history_totality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='previous_insurance_history_in_workshop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='previous_insurance_history_out_workshop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ListOfPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('is_defined', models.BooleanField(default=False)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('month_days', models.IntegerField(default=30)),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_date', django_jalali.db.models.jDateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_pay', to='payroll.Workshop')),
            ],
            options={
                'verbose_name': 'ListOfPay',
                'ordering': ['-pk'],
                'permissions': (('get.payroll_list', 'مشاهده حقوق و دستمزد'), ('create.payroll_list', 'تعریف حقوق و دستمزد'), ('update.payroll_list', 'ویرایش حقوق و دستمزد'), ('delete.payroll_list', 'حذف حقوق و دستمزد'), ('getOwn.payroll_list', 'مشاهده حقوق و دستمزد خود'), ('updateOwn.payroll_list', 'ویرایش حقوق و دستمزد خود'), ('deleteOwn.payroll_list', 'حذف حقوق و دستمزد خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
