# Generated by Django 2.2 on 2022-09-03 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0004_auto_20220903_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofpay',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.list_of_pay', 'مشاهده حقوق و دستمزد'), ('create.list_of_pay', 'تعریف حقوق و دستمزد'), ('update.list_of_pay', 'ویرایش حقوق و دستمزد'), ('delete.list_of_pay', 'حذف حقوق و دستمزد'), ('getOwn.list_of_pay', 'مشاهده حقوق و دستمزد خود'), ('updateOwn.list_of_pay', 'ویرایش حقوق و دستمزد خود'), ('deleteOwn.list_of_pay', 'حذف حقوق و دستمزد خود')), 'verbose_name': 'ListOfPay'},
        ),
        migrations.CreateModel(
            name='ListOfPayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('is_defined', models.BooleanField(default=False)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField(blank=True, null=True)),
                ('hoghoogh_roozane', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('pay_base', models.IntegerField(default=0)),
                ('hourly_pay_base', models.IntegerField(default=0)),
                ('normal_worktime', models.IntegerField(default=0)),
                ('entitlement_leave_day', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('absence_day', models.IntegerField(default=0)),
                ('illness_leave_day', models.IntegerField(default=0)),
                ('without_salary_leave_day', models.IntegerField(default=0)),
                ('real_worktime', models.IntegerField(default=0)),
                ('ezafe_kari', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('ezafe_kari_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True)),
                ('tatil_kari', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('tatil_kari_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('kasre_kar', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('kasre_kar_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('shab_kari', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('shab_kari_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nobat_kari_sob_asr', models.IntegerField(default=0)),
                ('nobat_kari_sob_asr_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nobat_kari_sob_shab', models.IntegerField(default=0)),
                ('nobat_kari_sob_shab_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nobat_kari_asr_shab', models.IntegerField(default=0)),
                ('nobat_kari_asr_shab_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nobat_kari_sob_asr_shab', models.IntegerField(default=0)),
                ('nobat_kari_sob_asr_shab_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('list_of_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_pay_item', to='payroll.ListOfPay')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workshop_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_list_item', to='payroll.WorkshopPersonnel')),
            ],
            options={
                'verbose_name': 'ListOfPayItem',
                'ordering': ['-pk'],
                'permissions': (('get.list_of_pay_item', 'مشاهده آیتم های حقوق و دستمزد'), ('create.list_of_pay_item', 'تعریف آیتم های حقوق و دستمزد'), ('update.list_of_pay_item', 'ویرایش آیتم های حقوق و دستمزد'), ('delete.list_of_pay_item', 'حذف آیتم های حقوق و دستمزد'), ('getOwn.list_of_pay_item', 'مشاهده آیتم های حقوق و دستمزد خود'), ('updateOwn.list_of_pay_item', 'ویرایش آیتم های حقوق و دستمزد خود'), ('deleteOwn.list_of_pay_item', 'حذف آیتم های حقوق و دستمزد خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
