# Generated by Django 2.2 on 2022-12-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20221201_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
