# Generated by Django 2.2 on 2022-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20221023_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='personnel_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
