# Generated by Django 2.2 on 2022-09-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20220903_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpayitem',
            name='workshop_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_pay_item', to='payroll.WorkshopPersonnel'),
        ),
    ]
