# Generated by Django 2.2 on 2022-12-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20221201_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelfamily',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='national_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
