# Generated by Django 2.2 on 2022-12-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_personnel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='account_bank_name',
            field=models.CharField(blank=True, choices=[('BCDEVE', 'بانک توسعه تعاون'), ('BCITY', 'بانک شهر'), ('BDAY', 'بانک دی'), ('BEDIRA', 'بانک توسعه صادرات  ایران'), ('BEGHTE', 'بانک اقتصاد نوین'), ('BGHARZ', 'بانک قرض الحسنه مهر ایران'), ('BINDMI', 'بانک صنعت و معدن'), ('BKARAF', 'بانک کارآفرین'), ('BKESHA', 'بانک کشاورزی'), ('BMASKA', 'بانک مسکن'), ('BMELLA', 'بانک ملت'), ('BMELLI', 'بانک  ملی ایران'), ('BPARSI', 'بانک پارسیان'), ('BPASAR', 'بانک پاسارگاد'), ('BPOST', 'پست بانک'), ('BREFAH', 'بانک  رفاه کارگران'), ('BSADER', 'بانک صادرات'), ('BSAMAN', 'بانک سامان'), ('BSARMA', 'بانک سرمایه'), ('BSEPAH', 'بانک  سپه'), ('BSINA', 'بانک سینا'), ('BTAT', 'بانک تات'), ('BTEJAR', 'بانک تجارت'), ('BTOURI', 'بانک  گردشگری'), ('BRESALA', 'بانک قرض الحسنه رسالت'), ('BAYAN', 'بانک آینده'), ('CHART', 'استاندارد چارترد'), ('CHART', 'بانک تجاری ایران و اروپا'), ('KHAVA', 'بانک خاورمیانه'), ('VENE', 'بانک مشترک ایران - ونزوئلا'), ('ESLA', 'تعاون اسلامی برای سرمایه\u200cگذاری (مصرف التعاون الاسلامی للاستثمار)'), ('FUTU', 'فیوچر بانک (المستقبل)'), ('CASP', 'مؤسسه اعتباری غیربانکی کاسپین '), ('TOSE', 'مؤسسه اعتباری غیربانکی توسعه '), ('MELAL', 'مؤسسه اعتباری غیربانکی ملل '), ('NOR', 'مؤسسه اعتباری غیربانکی نور '), ('ZAMIN', 'بانک ایران زمین')], max_length=10, null=True),
        ),
    ]
