# Generated by Django 2.2 on 2022-10-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20221023_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='save_leaave',
            field=models.IntegerField(default=0),
        ),
    ]
