# Generated by Django 2.2 on 2022-12-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20221203_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelfamily',
            name='gender',
            field=models.CharField(choices=[('m', 'مرد'), ('f', 'زن')], default='m', max_length=1),
        ),
    ]
