# Generated by Django 2.2 on 2022-08-16 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import helpers.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0006_hrletter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('is_defined', models.BooleanField(default=False)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField(blank=True, null=True)),
                ('insurance', models.BooleanField(default=False)),
                ('insurance_add_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('work_title', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_insurance_history_out_workshop', models.IntegerField()),
                ('previous_insurance_history_in_workshop', models.IntegerField()),
                ('current_insurance_history_in_workshop', models.IntegerField()),
                ('insurance_history_totality', models.IntegerField()),
                ('job_position', models.CharField(max_length=100)),
                ('job_group', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_location_status', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('c', 'پیمانی'), ('co', 'قراردادی'), ('cr', 'َشرکتی'), ('fu', 'مامور'), ('or', 'سایر'), ('p', 'رسمی')], default='co', max_length=2)),
                ('contract_type', models.CharField(choices=[('p', 'پاره وقت'), ('f', 'تمام وقت'), ('t', 'موقت'), ('h', 'ساعتی'), ('c', 'پیمانی')], default='f', max_length=2)),
                ('employee_status', models.CharField(choices=[('nr', 'معمولی'), ('fc', 'فرزند شهید'), ('st', 'جانباز'), ('fr', 'آزاده'), ('ar', 'نیروهای مسلح'), ('bn', 'مشمولین بند چهارده ماده نود و هفت'), ('fo', 'اتباع خارجی مشمول قانون اجتناب از اخذ مالیات مضاعف')], default='nr', max_length=2)),
                ('contract_row', models.ManyToManyField(related_name='contract', to='payroll.ContractRow')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='payroll.Personnel')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='payroll.Workshop')),
            ],
            options={
                'verbose_name': 'WorkshopPersonnel',
                'ordering': ['-pk'],
                'permissions': (('get.workshop_personnel', 'مشاهده پرسنل کارگاه'), ('create.workshop_personnel', 'تعریف پرسنل کارگاه'), ('update.workshop_personnel', 'ویرایش پرسنل کارگاه'), ('delete.workshop_personnel', 'حذف پرسنل کارگاه'), ('getOwn.workshop_personnel', 'مشاهده پرسنل کارگاه خود'), ('updateOwn.workshop_personnel', 'ویرایش پرسنل کارگاه خود'), ('deleteOwn.workshop_personnel', 'حذف پرسنل کارگاه خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.workshop_personnel', 'مشاهده قرارداد'), ('create.workshop_personnel', 'تعریف قرارداد'), ('update.workshop_personnel', 'ویرایش قرارداد'), ('delete.workshop_personnel', 'حذف قرارداد'), ('getOwn.workshop_personnel', 'مشاهده قرارداد خود'), ('updateOwn.workshop_personnel', 'ویرایش قرارداد خود'), ('deleteOwn.workshop_personnel', 'حذف قرارداد خود')), 'verbose_name': 'Contract'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_row',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='current_insurance_history_in_workshop',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='employee_status',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='insurance_add_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='insurance_history_totality',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='job_group',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='job_location_status',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='previous_insurance_history_in_workshop',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='previous_insurance_history_out_workshop',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='work_title',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='workshop',
        ),
        migrations.AddField(
            model_name='personnelfamily',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='ساختار شماره موبایل صحیح نبست', regex='^(09){1}[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_from_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_to_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_letter', to='payroll.WorkshopPersonnel'),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='military_service',
            field=models.CharField(choices=[('d', 'انجام داده'), ('n', 'انجام نداده'), ('e', 'معاف'), ('x', 'هیچ کدام')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='national_code',
            field=models.IntegerField(unique=True, validators=[helpers.models.is_valid_melli_code]),
        ),
        migrations.AddField(
            model_name='contract',
            name='workshop_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='payroll.WorkshopPersonnel'),
        ),
    ]
