# Generated by Django 2.2 on 2022-10-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_personnel_save_leaave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='save_leaave',
        ),
        migrations.AddField(
            model_name='workshoppersonnel',
            name='save_leaave',
            field=models.IntegerField(default=0),
        ),
    ]
