# Generated by Django 2.2 on 2022-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20220903_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='aele_mande',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='aele_mandi_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
