# Generated by Django 2.2 on 2022-10-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20221025_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofpayitem',
            name='jome_kar',
        ),
        migrations.RemoveField(
            model_name='listofpayitem',
            name='jome_kar_amount',
        ),
        migrations.RemoveField(
            model_name='listofpayitem',
            name='jome_kar_nerkh',
        ),
        migrations.RemoveField(
            model_name='listofpayitem',
            name='jome_kar_total',
        ),
    ]
