# Generated by Django 2.2 on 2022-12-03 11:24

from django.db import migrations, models
import payroll.functions


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_personnelfamily_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='assignor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='assignor_national_code',
            field=models.CharField(max_length=20, validators=[payroll.functions.is_shenase_meli]),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='assignor_workshop_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='contract_row',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='status',
            field=models.CharField(choices=[('a', 'فعال'), ('n', 'غیر فعال')], max_length=1),
        ),
    ]
