# Generated by Django 2.2 on 2022-08-16 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0007_auto_20220816_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.contract', 'مشاهده قرارداد'), ('create.contract', 'تعریف قرارداد'), ('update.contract', 'ویرایش قرارداد'), ('delete.contract', 'حذف قرارداد'), ('getOwn.contract', 'مشاهده قرارداد خود'), ('updateOwn.contract', 'ویرایش قرارداد خود'), ('deleteOwn.contract', 'حذف قرارداد خود')), 'verbose_name': 'Contract'},
        ),
        migrations.CreateModel(
            name='LeaveOrAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('is_defined', models.BooleanField(default=False)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('e', 'استحقاقی'), ('i', 'استعلاجی'), ('w', 'بدون حقوق'), ('a', 'غیبت')], default='w', max_length=2)),
                ('entitlement_leave_type', models.CharField(blank=True, choices=[('e', 'استحقاقی'), ('i', 'استعلاجی'), ('w', 'بدون حقوق'), ('a', 'غیبت')], max_length=2, null=True)),
                ('from_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('to_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('from_hour', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('to_hour', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workshop_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='payroll.WorkshopPersonnel')),
            ],
            options={
                'verbose_name': 'LeaveOrAbsence',
                'ordering': ['-pk'],
                'permissions': (('get.leave_or_absence', 'مشاهده مرخصی'), ('create.leave_or_absence', 'تعریف مرخصی'), ('update.leave_or_absence', 'ویرایش مرخصی'), ('delete.leave_or_absence', 'حذف مرخصی'), ('getOwn.leave_or_absence', 'مشاهده مرخصی خود'), ('updateOwn.leave_or_absence', 'ویرایش مرخصی خود'), ('deleteOwn.leave_or_absence', 'حذف مرخصی خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
