# Generated by Django 2.2 on 2022-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20220903_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='aele_mandi_nerkh',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='ezafe_kari_nerkh',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='kasre_kar_nerkh',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='nobat_kari_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.025, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='nobat_kari_sob_asr_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='nobat_kari_sob_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='nobat_kari_sob_shab_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.225, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='shab_kari_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.35, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='tatil_kari_nerkh',
            field=models.DecimalField(decimal_places=2, default=1.96, max_digits=24),
        ),
    ]
