# Generated by Django 2.2 on 2022-12-08 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0008_auto_20221207_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('is_defined', models.BooleanField(default=False)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('change_date', django_jalali.db.models.jDateField()),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('contract_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='payroll.ContractRow')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adjustment',
                'ordering': ['-pk'],
                'permissions': (('get.adjustment', 'مشاهده تعدیل'), ('create.adjustment', 'تعریف تعدیل'), ('update.adjustment', 'ویرایش تعدیل'), ('delete.adjustment', 'حذف تعدیل'), ('getOwn.adjustment', 'مشاهده تعدیل خود'), ('updateOwn.adjustment', 'ویرایش تعدیل خود'), ('deleteOwn.adjustment', 'حذف تعدیل خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
