# Generated by Django 2.2 on 2022-10-26 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0008_auto_20221025_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('date', django_jalali.db.models.jDateField()),
                ('bank_pay_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('list_of_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='payroll.ListOfPay')),
            ],
            options={
                'verbose_name': 'Pay',
                'ordering': ['-pk'],
                'permissions': (('get.pay', 'مشاهده لیست پرداخت'), ('create.pay', 'تعریف لیست پرداخت'), ('update.pay', 'ویرایش لیست پرداخت'), ('delete.pay', 'حذف لیست پرداخت'), ('getOwn.pay', 'مشاهده پرداخت خود'), ('updateOwn.pay', 'ویرایش پرداخت خود'), ('deleteOwn.pay', 'حذف پرداخت خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('list_of_pay_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='payroll.ListOfPayItem')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='payroll.Pay')),
            ],
            options={
                'verbose_name': 'PayItem',
                'ordering': ['-pk'],
                'permissions': (('get.pay_item', 'مشاهده پرداخت'), ('create.pay_item', 'تعریف پرداخت'), ('update.pay_item', 'ویرایش پرداخت'), ('delete.pay_item', 'حذف پرداخت'), ('getOwn.pay_item', 'مشاهده پرداخت خود'), ('updateOwn.pay_item', 'ویرایش پرداخت خود'), ('deleteOwn.pay_item', 'حذف پرداخت خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
