# Generated by Django 2.2 on 2022-09-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20220904_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='sanavat_base',
            field=models.DecimalField(decimal_places=6, default=True, max_digits=24),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='sanavat_month',
            field=models.IntegerField(default=0),
        ),
    ]
