# Generated by Django 2.2 on 2022-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20220816_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
