# Generated by Django 2.2 on 2022-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20221203_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='assignor_workshop_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='contract_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='contract_row',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
