# Generated by Django 2.2 on 2022-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_contract_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='identity_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='national_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='employer_insurance_contribution',
            field=models.IntegerField(),
        ),
    ]
