# Generated by Django 2.2 on 2022-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
