# Generated by Django 2.2 on 2022-10-27 05:45

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_pay_payitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payitem',
            name='list_of_pay_item',
        ),
        migrations.RemoveField(
            model_name='payitem',
            name='pay',
        ),
        migrations.AddField(
            model_name='listofpay',
            name='bank_pay_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listofpay',
            name='pay_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listofpay',
            name='pay_form_create_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
        migrations.DeleteModel(
            name='PayItem',
        ),
    ]
