# Generated by Django 2.2 on 2022-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20220904_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='aele_mandi_child',
            field=models.IntegerField(default=0),
        ),
    ]
