# Generated by Django 2.2 on 2022-12-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20221203_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelfamily',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
