# Generated by Django 2.2 on 2022-08-17 08:17

from django.db import migrations, models
import helpers.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20220817_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelfamily',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[helpers.models.is_valid_melli_code]),
        ),
    ]
