# Generated by Django 2.2 on 2022-09-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_listofpayitem_aele_mandi_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='total_insurance_month',
            field=models.IntegerField(default=0),
        ),
    ]
