# Generated by Django 2.2 on 2022-12-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_adjustment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
