# Generated by Django 2.2 on 2022-08-17 09:24

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20220817_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelfamily',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
