# Generated by Django 2.2 on 2022-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20221102_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='sayer_kosoorat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
