# Generated by Django 2.2 on 2022-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_listofpayitem_total_insurance_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='mission_day',
            field=models.IntegerField(default=0),
        ),
    ]
