# Generated by Django 2.2 on 2022-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_auto_20221204_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveorabsence',
            name='leave_type',
            field=models.CharField(choices=[('e', 'استحقاقی'), ('i', 'استعلاجی'), ('w', 'بدون حقوق'), ('a', 'غیبت'), ('m', 'ماده 73')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('h', 'ساعتی'), ('d', 'روزانه')], max_length=2),
        ),
    ]
