# Generated by Django 2.2 on 2022-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_auto_20220817_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='personnel_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='contract_row',
            field=models.ManyToManyField(blank=True, related_name='contract_rows', to='payroll.ContractRow'),
        ),
    ]
