# Generated by Django 2.2 on 2022-11-17 07:20

from django.db import migrations, models
import payroll.functions


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_listofpayitem_sayer_kosoorat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='employer_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=24),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='unemployed_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=24),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='worker_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=24),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='assignor_national_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[payroll.functions.is_shenase_meli]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='employer_insurance_contribution',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
