# Generated by Django 2.2 on 2022-12-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_auto_20221210_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='assignor_workshop_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
