# Generated by Django 2.2 on 2022-09-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20220904_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='mission_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='mission_nerkh',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='ezafe_kari_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='ezafe_kari_nerkh',
            field=models.DecimalField(decimal_places=2, default=1.96, max_digits=24),
        ),
    ]
