# Generated by Django 2.2 on 2022-11-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20221117_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='cumulative_absence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='cumulative_entitlement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='cumulative_illness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='cumulative_mission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='cumulative_without_salary',
            field=models.IntegerField(default=0),
        ),
    ]
