# Generated by Django 2.2 on 2022-08-18 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20220817_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول کد پستی باید 10 رقم باشد', regex='^.{10}$')]),
        ),
    ]
