# Generated by Django 2.2 on 2022-12-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20221210_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='is_personnel_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
