# Generated by Django 2.2 on 2022-08-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_workshop_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='contract_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_rows', to='payroll.Workshop'),
        ),
    ]
