# Generated by Django 2.2 on 2022-09-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20220904_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofpayitem',
            name='aele_mande',
        ),
    ]
