# Generated by Django 2.2 on 2022-11-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20221127_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanitem',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.loan_item', 'مشاهده قسط وام'), ('create.loan_item', 'تعریف قسط وام'), ('update.loan_item', 'ویرایش قسط وام'), ('delete.loan_item', 'حذف قسط وام'), ('getOwn.loan_item', 'مشاهده قسط وام خود'), ('updateOwn.loan_item', 'ویرایش وام قسط خود'), ('deleteOwn.loan_item', 'حذف وام قسط خود')), 'verbose_name': 'LoanItem'},
        ),
        migrations.AddField(
            model_name='hrletter',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
