# Generated by Django 2.2 on 2022-12-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20221204_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='account_bank_name',
            field=models.CharField(blank=True, choices=[('BANSAR', 'بانک انصار'), ('BCDEVE', 'بانک توسعه تعاون'), ('BCENTR', 'بانک مرکزی ایران'), ('BCITY', 'بانک شهر'), ('BDAY', 'بانک دی'), ('BEDIRA', 'بانک  صادرات توسعه ایران'), ('BEGHTE', 'بانک اقتصاد نوین'), ('BGHARZ', 'بانک قرض الحسنه مهر'), ('BHEKMA', 'بانک حکمت ایرانیان'), ('BINDMI', 'بانک صنعت و معدن'), ('BKARAF', 'بانک کارآفرین'), ('BKESHA', 'بانک کشاورزی'), ('BMASKA', 'بانک مسکن'), ('BMELLA', 'بانک ملت'), ('BMELLI', 'بانک  ملی ایران'), ('BPARSI', 'بانک پارسیان'), ('BPASAR', 'بانک پاسارگاد'), ('BPOST', 'پست بانک'), ('BREFAH', 'بانک  رفاه کارگران'), ('BSADER', 'بانک صادرات'), ('BSAMAN', 'بانک سامان'), ('BSARMA', 'بانک سرمایه'), ('BSEPAH', 'بانک  سپه'), ('BSINA', 'بانک سینا'), ('BTAT', 'بانک تات'), ('BTEJAR', 'بانک تجارت'), ('BTOURI', 'بانک  گردشگری'), ('BRESALA', 'بانک رسالت')], max_length=10, null=True),
        ),
    ]
