# Generated by Django 2.2 on 2022-09-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_remove_listofpayitem_aele_mande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrletter',
            name='haghe_owlad_amount',
        ),
        migrations.RemoveField(
            model_name='hrletter',
            name='haghe_owlad_nature',
        ),
        migrations.RemoveField(
            model_name='hrletter',
            name='haghe_owlad_use_base',
        ),
        migrations.RemoveField(
            model_name='hrletter',
            name='haghe_owlad_use_insurance',
        ),
        migrations.RemoveField(
            model_name='hrletter',
            name='haghe_owlad_use_tax',
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_shoghl_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_jazb_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_modiriyat_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_sarparasti_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='paye_sanavat_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
