# Generated by Django 2.2 on 2022-12-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_auto_20221204_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='insurance_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
