# Generated by Django 2.2 on 2022-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_auto_20220818_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='university_type',
            field=models.CharField(blank=True, choices=[('st', 'دولتی'), ('op', 'آزاد'), ('np', 'غیر انتفاعی')], max_length=2, null=True),
        ),
    ]
