# Generated by Django 2.2 on 2022-11-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20210718_1141'),
        ('payroll', '0015_auto_20221129_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoptax',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='companies.Company'),
        ),
    ]
