# Generated by Django 2.2 on 2022-08-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20220820_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='account_bank_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='bank_cart_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
