# Generated by Django 2.2 on 2022-09-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20220904_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='total_payment',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
