# Generated by Django 2.2 on 2022-11-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20210718_1141'),
        ('payroll', '0016_auto_20221130_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_letter', to='companies.Company'),
        ),
    ]
