# Generated by Django 2.2 on 2022-12-05 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20221205_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='status',
            field=models.CharField(choices=[('a', 'فعال'), ('n', 'غیر فعال')], max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='postal_code',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول کد پستی باید 10 رقم باشد', regex='^.{10}$')]),
            preserve_default=False,
        ),
    ]
