# Generated by Django 2.2 on 2022-11-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20210718_1141'),
        ('payroll', '0017_hrletter_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpay',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_pay', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_pay_item', to='companies.Company'),
        ),
    ]
