# Generated by Django 2.2 on 2022-12-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_auto_20221205_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='degree_education',
            field=models.IntegerField(blank=True, choices=[(1, 'کم سواد'), (2, 'زیر دیپلم'), (3, 'دیپلم'), (4, 'کاردانی'), (5, 'لیسانس'), (6, 'فوق لیسانس'), (7, 'دکترا'), (8, 'فوق دکترا')], null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('s', 'مجرد'), ('m', 'متاهل'), ('c', 'سرپرست فرزند')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='military_service',
            field=models.CharField(blank=True, choices=[('d', 'انجام داده'), ('n', 'انجام نداده'), ('e', 'معاف'), ('x', 'هبچ کدام')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nationality',
            field=models.IntegerField(blank=True, choices=[(1, 'ایرانی'), (2, 'غیر ایرانی')], null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('s', 'مجرد'), ('m', 'متاهل'), ('c', 'سرپرست فرزند')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='military_service',
            field=models.CharField(blank=True, choices=[('d', 'انجام داده'), ('n', 'انجام نداده'), ('e', 'معاف'), ('x', 'هیچ کدام')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='physical_condition',
            field=models.CharField(blank=True, choices=[('h', 'سالم'), ('p', 'بیمار'), ('m', 'نفص عضو')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='relative',
            field=models.CharField(blank=True, choices=[('f', 'پدر'), ('m', 'مادر'), ('c', 'فرزند'), ('s', 'همسر')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='study_status',
            field=models.CharField(blank=True, choices=[('s', 'محصل'), ('n', 'غیر محصل')], max_length=1, null=True),
        ),
    ]
