# Generated by Django 2.2 on 2022-08-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_auto_20220820_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='city_phone_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='mobile_number_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='mobile_number_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
