# Generated by Django 2.2 on 2022-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_auto_20220904_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='hoghooghe_roozane_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
