# Generated by Django 2.2 on 2022-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_auto_20221210_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='work_title_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
