# Generated by Django 2.2 on 2022-08-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_auto_20220820_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='degree_of_education',
            new_name='degree_education',
        ),
    ]
