# Generated by Django 2.2 on 2022-12-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_auto_20221210_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='work_title_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
