# Generated by Django 2.2 on 2022-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_auto_20220820_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrow',
            name='is_activate',
        ),
        migrations.AddField(
            model_name='contractrow',
            name='status',
            field=models.CharField(choices=[('a', 'فعال'), ('n', 'راکد')], default='n', max_length=1),
        ),
    ]
