# Generated by Django 2.2 on 2022-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_auto_20220904_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='calculate_payment',
            field=models.BooleanField(default=False),
        ),
    ]
