# Generated by Django 2.2 on 2022-08-21 11:08

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_auto_20220820_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelfamily',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='leaveorabsence',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='assignor_national_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='leaveorabsence',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveorabsence',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='employment_type',
            field=models.CharField(choices=[('c', 'پیمانی'), ('co', 'قراردادی'), ('cr', 'َشرکتی'), ('fu', 'مامور'), ('p', 'رسمی'), ('or', 'سایر')], default='co', max_length=2),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='job_location_status',
            field=models.CharField(choices=[('nr', 'معمولی'), ('dp', 'مناطق کمتر توسعه یافته'), ('ft', 'مناطق آزاد تجاری'), ('sp', 'پارک علم و فناوری')], default='nr', max_length=2),
        ),
    ]
