# Generated by Django 2.2 on 2022-09-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_listofpayitem_calculate_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofpayitem',
            name='calculate_payment',
        ),
    ]
