# Generated by Django 2.2 on 2022-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_auto_20221210_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
