# Generated by Django 2.2 on 2022-09-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_remove_listofpayitem_calculate_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='sayer_ezafat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
