# Generated by Django 2.2 on 2022-08-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20220827_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveorabsence',
            name='time_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
    ]
