# Generated by Django 2.2 on 2022-09-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_listofpayitem_sayer_ezafat'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='calculate_payment',
            field=models.BooleanField(default=False),
        ),
    ]
