# Generated by Django 2.2 on 2022-12-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_auto_20221211_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrow',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
    ]
