# Generated by Django 2.2 on 2022-08-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_auto_20220827_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='base_pay_type',
            field=models.CharField(choices=[('d', 'روزانه'), ('m', 'ماهیانه')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='ezafe_kari_nerkh',
            field=models.DecimalField(decimal_places=6, default=1.4, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='kasre_kar_nerkh',
            field=models.DecimalField(decimal_places=6, default=1.4, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_asr_shab',
            field=models.DecimalField(decimal_places=6, default=0.025, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_sob_asr',
            field=models.DecimalField(decimal_places=6, default=0.1, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_sob_asr_shab',
            field=models.DecimalField(decimal_places=6, default=0.15, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_sob_shab',
            field=models.DecimalField(decimal_places=6, default=0.225, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sanavat_type',
            field=models.CharField(choices=[('c', 'پیوسته'), ('n', 'نا پیوسته')], default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='shab_kari_nerkh',
            field=models.DecimalField(decimal_places=6, default=0.35, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tatil_kari_nerkh',
            field=models.DecimalField(decimal_places=6, default=1.96, max_digits=24),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='status',
            field=models.CharField(choices=[('a', 'فعال'), ('n', 'غیر فعال')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='ayabo_zahab_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='ayabo_zahab_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='bon_kharo_bar_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='bon_kharo_bar_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='eydi_salane_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='eydi_salane_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='ezafe_kari_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='ezafe_kari_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_afzayesh_bahrevari_tolid_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_afzayesh_bahrevari_tolid_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_badi_abohava_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_badi_abohava_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_mahal_khedmat_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_mahal_khedmat_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_nobat_kar_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_nobat_kar_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_sakhti_kar_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_sakhti_kar_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_shab_kari_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_shab_kari_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_sharayet_mohit_kar_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_sharayet_mohit_kar_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_shoghl_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_shoghl_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_tolid_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_tolid_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_ankal_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_ankal_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_jazb_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_jazb_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_lavazem_tahrir_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_lavazem_tahrir_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_mamooriat_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_mamooriat_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_maskan_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_maskan_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_modiriyat_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_modiriyat_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_owlad_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_owlad_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_sanavat_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_sanavat_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_sarparasti_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_sarparasti_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_shift_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_shift_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_shir_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_shir_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_taahol_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_taahol_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='hoghooghe_roozane_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='hoghooghe_roozane_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='is_template',
            field=models.CharField(choices=[('t', 'قالب'), ('p', 'شخصی')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='jome_kari_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='jome_kari_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_mahdekoodak_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_mahdekoodak_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_mobile_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_mobile_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_varzesh_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_varzesh_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='mahroomiat_tashilat_zendegi_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='mahroomiat_tashilat_zendegi_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='maskan_ba_asasiye_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='maskan_ba_asasiye_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='maskan_bi_asasiye_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='maskan_bi_asasiye_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='mazaya_gheyr_naqdi_pardakhti_kargaran_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='mazaya_gheyr_naqdi_pardakhti_kargaran_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='otomobil_shakhsi_ba_ranande_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='otomobil_shakhsi_ba_ranande_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='otomobil_shakhsi_bi_ranande_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='otomobil_shakhsi_bi_ranande_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='paye_sanavat_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='paye_sanavat_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='poorsant_foroosh_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='poorsant_foroosh_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='yarane_ghaza_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='yarane_ghaza_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='zakhire_ayam_morakhasi_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='zakhire_ayam_morakhasi_nature',
            field=models.CharField(choices=[('b', 'حقوق پایه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='personnelfamily',
            name='national_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='contract_row',
            field=models.ManyToManyField(blank=True, related_name='workshop_personnel', to='payroll.ContractRow'),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='job_position',
            field=models.CharField(choices=[('st', 'آموزشي و فرهنگي'), ('fn', 'اداري و مالي'), ('so', 'اموراجتماعي'), ('he', 'درماني و بهداشتي'), ('it', 'اطلاعات فناوري'), ('se', 'خدمات'), ('en', 'فني و مهندسي'), ('ar', 'كشاورزي ومحيط زيست'), ('pr', 'تولیدی'), ('sr', 'تحقیقاتی'), ('wo', 'کارگری'), ('sc', 'حراست و نگهبانی'), ('tr', 'ترابری'), ('sa', 'بازاریابی و فروش'), ('ju', 'قضات'), ('wa', 'انبارداری'), ('co', 'کنترل کیفی'), ('ma', 'هیات علمی'), ('ot', 'سایر')], max_length=2),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_personnel', to='payroll.Personnel'),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_personnel', to='payroll.Workshop'),
        ),
    ]
