# Generated by Django 2.2 on 2022-09-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_listofpayitem_is_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='aele_mandi',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
