# Generated by Django 2.2 on 2022-08-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_auto_20220828_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_letter', to='payroll.Contract'),
        ),
    ]
