# Generated by Django 2.2 on 2022-09-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_listofpayitem_aele_mandi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpayitem',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
