# Generated by Django 2.2 on 2022-09-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20220907_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpayitem',
            name='aele_mandi',
            field=models.IntegerField(default=0),
        ),
    ]
