# Generated by Django 2.2 on 2022-09-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20220907_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='ezafe_kari_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='kasre_kar_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='shab_kari_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='tatil_kari_total',
            field=models.IntegerField(default=0),
        ),
    ]
