# Generated by Django 2.2 on 2022-08-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20220829_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='daily_pay_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='monthly_pay_base',
            field=models.IntegerField(default=0),
        ),
    ]
