# Generated by Django 2.2 on 2022-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20221212_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractrow',
            name='contract_initial_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
