# Generated by Django 2.2 on 2022-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_auto_20220829_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='ezafe_kari_pay_type',
            field=models.CharField(choices=[('h', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='kasre_kar_pay_type',
            field=models.CharField(choices=[('h', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_asr_shab_pay_type',
            field=models.CharField(choices=[('h', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_sob_asr_pay_type',
            field=models.CharField(choices=[('h', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_sob_asr_shab_pay_type',
            field=models.CharField(choices=[('h', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_sob_shab_pay_type',
            field=models.CharField(choices=[('h', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tatil_kari_pay_type',
            field=models.CharField(choices=[('h', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
    ]
