# Generated by Django 2.2 on 2022-09-07 10:52

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_auto_20220907_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='insurance_add_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractrow',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
