# Generated by Django 2.2 on 2022-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_auto_20220831_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='nobat_kari_asr_shab',
            new_name='nobat_kari_asr_shab_nerkh',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='nobat_kari_sob_asr',
            new_name='nobat_kari_sob_asr_nerkh',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='nobat_kari_sob_asr_shab',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='nobat_kari_sob_shab',
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_sob_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=6, default=0.15, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='nobat_kari_sob_shab_nerkh',
            field=models.DecimalField(decimal_places=6, default=0.225, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='shab_kari_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='base_pay_type',
            field=models.CharField(choices=[('d', 'مزد مبنای روزانه'), ('m', 'مزد مبنای ماهیانه')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='ezafe_kari_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='kasre_kar_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_asr_shab_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_asr_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_asr_shab_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_shab_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tatil_kari_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
    ]
