# Generated by Django 2.2 on 2022-12-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_auto_20221212_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelfamily',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
