# Generated by Django 2.2 on 2022-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_auto_20220907_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='employee_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='unemployed_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='worker_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=24),
        ),
    ]
