# Generated by Django 2.2 on 2022-12-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_auto_20221213_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='city_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='location_of_exportation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='sector_of_exportation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='location_of_exportation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sector_of_exportation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
