# Generated by Django 2.2 on 2022-09-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_auto_20220907_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='daily_entitlement_leave_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='hourly_entitlement_leave_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='entitlement_leave_day',
            field=models.IntegerField(default=0),
        ),
    ]
