# Generated by Django 2.2 on 2022-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_auto_20220831_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='ezafe_kari_nerkh',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='kasre_kar_nerkh',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.025, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_asr_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_shab_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.225, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='shab_kari_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.35, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tatil_kari_nerkh',
            field=models.DecimalField(decimal_places=2, default=1.96, max_digits=24),
        ),
    ]
