# Generated by Django 2.2 on 2022-08-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_auto_20220831_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='day_hourly_pay_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='month_hourly_pay_base',
            field=models.IntegerField(default=0),
        ),
    ]
