# Generated by Django 2.2 on 2022-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_auto_20220908_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpayitem',
            name='entitlement_leave_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
    ]
