# Generated by Django 2.2 on 2022-12-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_auto_20221214_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
