# Generated by Django 2.2 on 2022-09-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_auto_20220908_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='contract_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_pay_item', to='payroll.ContractRow'),
        ),
    ]
