# Generated by Django 2.2 on 2022-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_auto_20221214_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveorabsence',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
