# Generated by Django 2.2 on 2022-09-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_auto_20220910_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrow',
            name='contract_row',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('m', 'مرد'), ('f', 'زن')], default='m', max_length=1),
        ),
    ]
