# Generated by Django 2.2 on 2022-12-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_leaveorabsence_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
