# Generated by Django 2.2 on 2022-09-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_auto_20220911_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='ezafe_kari_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='ezafe_kari_use_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='ezafe_kari_use_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='haghe_maamooriat_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='haghe_maamooriat_use_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='haghe_maamooriat_use_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='jome_kari_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='jome_kari_use_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='jome_kari_use_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='mazaya_mostamar_gheyre_naghdi_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='mazaya_mostamar_gheyre_naghdi_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='mazaya_mostamar_gheyre_naghdi_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='mazaya_mostamar_gheyre_naghdi_use_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='mazaya_mostamar_gheyre_naghdi_use_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='nobat_kari_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='nobat_kari_use_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='nobat_kari_use_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='shab_kari_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='shab_kari_use_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='shab_kari_use_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='tatil_kari_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='tatil_kari_use_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='tatil_kari_use_tax',
            field=models.BooleanField(default=False),
        ),
    ]
