# Generated by Django 2.2 on 2022-09-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_auto_20220913_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='maskan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='otomobil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='mazaya_gheyr_mostamar',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
