# Generated by Django 2.2 on 2022-09-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_auto_20220913_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='ejtenab_maliat_mozaaf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='hazine_made_137',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='kosoorat_insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='manategh_tejari_moafiat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='naghdi_gheye_naghdi_tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listofpayitem',
            name='sayer_moafiat',
            field=models.IntegerField(default=0),
        ),
    ]
