# Generated by Django 2.2 on 2022-12-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0039_auto_20221215_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelfamily',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
