# Generated by Django 2.2 on 2022-09-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0039_auto_20220913_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='hade_aghal_hoghoogh',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='hade_aksar_mashmool_bime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='moafial_maliat_haghe_bime_sahme_bime_shavande',
            field=models.IntegerField(choices=[(1.0, '7/7'), (0.42857142857142855, '2/7')], default=1.0),
        ),
    ]
