# Generated by Django 2.2 on 2022-09-13 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0040_auto_20220913_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopTaxRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('is_defined', models.BooleanField(default=False)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField(blank=True, null=True)),
                ('from_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('to_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('ratio', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_row', to='payroll.Workshop')),
            ],
            options={
                'verbose_name': 'WorkshopTaxRow',
                'ordering': ['-pk'],
                'permissions': (('get.workshop_tax_row', 'مشاهده ردیف معاف مالیات'), ('create.workshop_tax_row', 'تعریف ردیف معاف مالیات'), ('update.workshop_tax_row', 'ویرایش ردیف معاف مالیات'), ('delete.workshop_tax_row', 'حذف ردیف معاف مالیات'), ('getOwn.workshop_tax_row', 'مشاهده ردیف معاف مالیات خود'), ('updateOwn.workshop_tax_row', 'ویرایش ردیف معاف مالیات خود'), ('deleteOwn.workshop_tax_row', 'حذف ردیف معاف مالیات خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
