# Generated by Django 2.2 on 2022-12-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_auto_20221215_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_identify_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
    ]
