# Generated by Django 2.2 on 2022-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_auto_20221215_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
