# Generated by Django 2.2 on 2022-09-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_workshoptaxrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_pay_item', to='payroll.Contract'),
        ),
        migrations.AlterField(
            model_name='workshoptaxrow',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_row', to='payroll.Workshop'),
        ),
    ]
