# Generated by Django 2.2 on 2022-12-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0042_auto_20221215_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_days',
        ),
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_identify_amount',
        ),
    ]
