# Generated by Django 2.2 on 2022-09-18 09:45

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_workshop_made_86'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoptaxrow',
            name='workshop',
        ),
        migrations.AddField(
            model_name='workshoptaxrow',
            name='from_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshoptaxrow',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workshoptaxrow',
            name='to_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
