# Generated by Django 2.2 on 2022-12-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_workshoppersonnel_sanavat_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_day',
        ),
    ]
