# Generated by Django 2.2 on 2022-09-18 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0044_auto_20220918_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoptaxrow',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='workshoptaxrow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workshoptaxrow',
            name='to_date',
        ),
        migrations.CreateModel(
            name='WorkshopTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('is_defined', models.BooleanField(default=False)),
                ('definition_date', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('to_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WorkshopTax',
                'ordering': ['-pk'],
                'permissions': (('get.workshop_tax', 'مشاهده  معاف مالیات'), ('create.workshop_tax', 'تعریف  معاف مالیات'), ('update.workshop_tax', 'ویرایش  معاف مالیات'), ('delete.workshop_tax', 'حذف  معاف مالیات'), ('getOwn.workshop_tax', 'مشاهده  معاف مالیات خود'), ('updateOwn.workshop_tax', 'ویرایش  معاف مالیات خود'), ('deleteOwn.workshop_tax', 'حذف  معاف مالیات خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='workshoptaxrow',
            name='workshop_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_row', to='payroll.WorkshopTax'),
        ),
    ]
