# Generated by Django 2.2 on 2022-12-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0045_remove_workshoppersonnel_haghe_sanavat_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshoppersonnel',
            old_name='sanavat_day',
            new_name='haghe_sanavat_days',
        ),
        migrations.RenameField(
            model_name='workshoppersonnel',
            old_name='haghe_sanavat_amount',
            new_name='haghe_sanavat_identify_amount',
        ),
    ]
