# Generated by Django 2.2 on 2022-09-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0045_auto_20220918_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='moafial_maliat_haghe_bime_sahme_bime_shavande',
        ),
    ]
