# Generated by Django 2.2 on 2022-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0046_remove_workshop_moafial_maliat_haghe_bime_sahme_bime_shavande'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='include_made_86',
            field=models.BooleanField(default=False),
        ),
    ]
