# Generated by Django 2.2 on 2022-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0047_hrletter_include_made_86'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='made_86',
        ),
        migrations.AddField(
            model_name='workshop',
            name='made_86_nerkh',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tax_employer_type',
            field=models.IntegerField(choices=[(1, '7/7'), (0.42857142857142855, '2/7')], default=1),
        ),
    ]
