# Generated by Django 2.2 on 2022-12-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0047_auto_20221215_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
