# Generated by Django 2.2 on 2022-12-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0049_auto_20221217_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_days',
        ),
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_identify_amount',
        ),
    ]
