# Generated by Django 2.2 on 2022-09-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0049_auto_20220924_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveorabsence',
            name='leave_type',
            field=models.CharField(choices=[('e', 'استحقاقی'), ('i', 'استعلاجی'), ('w', 'بدون حقوق'), ('a', 'غیبت'), ('m', 'ماده 73')], default='w', max_length=2),
        ),
    ]
