# Generated by Django 2.2 on 2022-12-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0050_auto_20221217_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppersonnel',
            name='sanavat_previous_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshoppersonnel',
            name='sanavat_previuos_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
