# Generated by Django 2.2 on 2022-09-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0050_auto_20220928_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveorabsence',
            name='matter_57_leave_type',
            field=models.CharField(blank=True, choices=[('c', 'زایمان'), ('m', 'ازدواج'), ('s', 'مرگ همسر'), ('d', 'مرگ فرزند'), ('p', 'مرگ پدر یا مادر')], max_length=2, null=True),
        ),
    ]
