# Generated by Django 2.2 on 2022-12-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0051_auto_20221217_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='sanavat_previous_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='sanavat_previuos_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
