# Generated by Django 2.2 on 2022-09-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0051_leaveorabsence_matter_57_leave_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveorabsence',
            old_name='matter_57_leave_type',
            new_name='matter_73_leave_type',
        ),
    ]
