# Generated by Django 2.2 on 2022-12-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0052_auto_20221217_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveorabsence',
            name='matter73_leave_type',
            field=models.CharField(blank=True, choices=[('m', 'ازدواج'), ('s', 'مرگ همسر'), ('d', 'مرگ فرزند'), ('p', 'مرگ پدر یا مادر')], max_length=2, null=True),
        ),
    ]
