# Generated by Django 2.2 on 2022-12-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0053_auto_20221217_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveorabsence',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('e', 'استحقاقی'), ('i', 'استعلاجی'), ('w', 'بدون حقوق'), ('a', 'غیبت'), ('m', 'ماده 73'), ('c', 'زایمان')], max_length=2, null=True),
        ),
    ]
