# Generated by Django 2.2 on 2022-09-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0053_auto_20220928_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='eydi_padash_Identification',
            field=models.CharField(choices=[('m', 'ماهانه'), ('y', 'سالانه')], default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='eydi_padash_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='haghe_sanavat_Identification',
            field=models.CharField(choices=[('m', 'ماهانه'), ('y', 'سالانه')], default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='haghe_sanavat_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='haghe_sanavat_type',
            field=models.CharField(choices=[('c', 'قطعی'), ('o', 'علی الحساب')], default='c', max_length=1),
        ),
    ]
