# Generated by Django 2.2 on 2022-09-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0054_auto_20220928_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='eydi_padash_Identification',
            new_name='eydi_padash_identification',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='haghe_sanavat_Identification',
            new_name='haghe_sanavat_identification',
        ),
        migrations.AddField(
            model_name='workshop',
            name='mission_save_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('h', 'جمع تمام مزایای حکم کارگزینی')], default='d', max_length=1),
        ),
    ]
