# Generated by Django 2.2 on 2022-09-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0055_auto_20220928_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='mission_save_pay_type',
            new_name='leave_save_pay_type',
        ),
        migrations.AddField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshoppersonnel',
            name='haghe_sanavat_identify_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
