# Generated by Django 2.2 on 2022-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0055_auto_20221217_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
