# Generated by Django 2.2 on 2022-10-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0056_auto_20220928_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='matter_47_leave_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='workshop',
            name='save_absence_limit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='save_absence_transfer_next_year',
            field=models.BooleanField(default=False),
        ),
    ]
