# Generated by Django 2.2 on 2022-10-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0057_auto_20221002_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofpay',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ('month',), 'permissions': (('get.list_of_pay', 'مشاهده حقوق و دستمزد'), ('create.list_of_pay', 'تعریف حقوق و دستمزد'), ('update.list_of_pay', 'ویرایش حقوق و دستمزد'), ('delete.list_of_pay', 'حذف حقوق و دستمزد'), ('getOwn.list_of_pay', 'مشاهده حقوق و دستمزد خود'), ('updateOwn.list_of_pay', 'ویرایش حقوق و دستمزد خود'), ('deleteOwn.list_of_pay', 'حذف حقوق و دستمزد خود')), 'verbose_name': 'ListOfPay'},
        ),
        migrations.AddField(
            model_name='listofpay',
            name='ultimate',
            field=models.BooleanField(default=False),
        ),
    ]
