# Generated by Django 2.2 on 2022-12-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0057_auto_20221217_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
