# Generated by Django 2.2 on 2022-12-18 07:13

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0058_contract_insurance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppersonnel',
            name='insurance_add_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveorabsence',
            name='workshop_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='payroll.WorkshopPersonnel'),
        ),
    ]
