# Generated by Django 2.2 on 2022-12-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0061_workshoppersonnel_sanavat_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='sanavat_button',
        ),
    ]
