# Generated by Django 2.2 on 2022-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0062_remove_workshoppersonnel_sanavat_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractrow',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveorabsence',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personnelfamily',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshoppersonnel',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
    ]
