# Generated by Django 2.2 on 2022-12-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0063_auto_20221219_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
