# Generated by Django 2.2 on 2022-12-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0065_auto_20221220_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
    ]
