# Generated by Django 2.2 on 2022-12-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0066_auto_20221221_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='is_template',
            field=models.CharField(blank=True, choices=[('t', 'قالب'), ('p', 'شخصی')], max_length=1, null=True),
        ),
    ]
