# Generated by Django 2.2 on 2022-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0067_auto_20221221_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
    ]
