# Generated by Django 2.2 on 2022-12-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0068_auto_20221221_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('l', 'وام'), ('d', 'مساعده')], max_length=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='workshop_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='payroll.WorkshopPersonnel'),
        ),
    ]
