# Generated by Django 2.2 on 2022-12-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20210718_1141'),
        ('payroll', '0069_auto_20221221_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaldeduction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction', to='companies.Company'),
        ),
    ]
