# Generated by Django 2.2 on 2022-12-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0070_optionaldeduction_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaldeduction',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='optionaldeduction',
            name='un_editable',
            field=models.BooleanField(default=False),
        ),
    ]
