# Generated by Django 2.2 on 2022-12-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0071_auto_20221221_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionaldeduction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
    ]
