# Generated by Django 2.2 on 2022-12-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0073_auto_20221221_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoppersonnel',
            name='job_group',
            field=models.IntegerField(blank=True, choices=[(2, 'آموزشی و فرهنگی'), (1, 'اداری و مالی'), (3, 'اموراجتماعی'), (5, 'درمانی و بهداشتی'), (4, 'اطلاعات فناوری'), (7, 'خدمات'), (6, 'فنی و مهندسي'), (8, 'كشاورزی ومحيط زيست'), (13, 'تولیدی'), (15, 'تحقیقاتی'), (11, 'کارگری'), (10, 'حراست و نگهبانی'), (12, 'ترابری'), (9, 'بازاریابی و فروش'), (17, 'قضات'), (16, 'انبارداری'), (14, 'کنترل کیفی'), (18, 'هیات علمی'), (0, 'سایر')], null=True),
        ),
    ]
