# Generated by Django 2.2 on 2022-12-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0074_auto_20221222_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
