# Generated by Django 2.2 on 2022-12-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0075_auto_20221224_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelfamily',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
