# Generated by Django 2.2 on 2022-12-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0076_auto_20221224_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
