# Generated by Django 2.2 on 2022-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0077_hrletter_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='ayabo_zahab_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='bon_kharo_bar_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_badi_abohava_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_mahal_khedmat_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_sakhti_kar_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_sharayet_mohit_kar_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='fogholade_shoghl_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_ankal_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_jazb_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_maskan_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_modiriyat_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_sarparasti_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_shir_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_taahol_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='haghe_tahsilat_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='hoghooghe_roozane_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_mahdekoodak_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_mobile_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='komakhazine_varzesh_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='mahroomiat_tashilat_zendegi_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='paye_sanavat_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='yarane_ghaza_nature',
            field=models.CharField(choices=[('b', 'دستمزد رورانه'), ('p', 'مستمر'), ('u', 'غیر مستمر')], max_length=1),
        ),
    ]
