# Generated by Django 2.2 on 2022-12-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0082_auto_20221231_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='employer_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='unemployed_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=24),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='worker_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='employee_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='unemployed_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='worker_insurance_nerkh',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=24),
        ),
    ]
