# Generated by Django 2.2 on 2023-01-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0083_auto_20221231_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='aele_mandi_nerkh',
            field=models.DecimalField(decimal_places=12, default=3, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='employee_insurance_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='ezafe_kari_nerkh',
            field=models.DecimalField(decimal_places=12, default=1.4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='jome_kari_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.1, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='kasre_kar_nerkh',
            field=models.DecimalField(decimal_places=12, default=1.4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='mission_pay_nerkh',
            field=models.DecimalField(decimal_places=12, default=1, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.025, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_asr_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.1, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.15, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_sob_shab_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.225, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='shab_kari_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.35, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tatil_kari_nerkh',
            field=models.DecimalField(decimal_places=12, default=1.96, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='unemployed_insurance_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.03, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='worker_insurance_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.03, max_digits=24),
        ),
    ]
