# Generated by Django 2.2 on 2023-01-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0084_auto_20230101_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='employer_insurance_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='unemployed_insurance_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.03, max_digits=24),
        ),
        migrations.AlterField(
            model_name='hrletter',
            name='worker_insurance_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.03, max_digits=24),
        ),
    ]
