# Generated by Django 2.2 on 2023-01-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0085_auto_20230101_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='worker_insurance_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.07, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nobat_kari_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.225, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='worker_insurance_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.07, max_digits=24),
        ),
    ]
