# Generated by Django 2.2 on 2023-01-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0086_auto_20230101_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='jome_kari_pay_type',
        ),
        migrations.AddField(
            model_name='hrletter',
            name='aele_mandi_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='eydi_padash_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='ezafe_kari_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='haghe_sanavat_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='kasre_kar_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='mission_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='nobat_kari_asr_shab_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='nobat_kari_sob_asr_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='nobat_kari_sob_asr_shab_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='nobat_kari_sob_shab_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='shab_kari_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='hrletter',
            name='tatil_kari_pay_type',
            field=models.CharField(choices=[('d', 'حداقل حقوق روزانه'), ('b', 'مزد مبنا')], default='b', max_length=1),
        ),
    ]
