# Generated by Django 2.2 on 2023-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0087_auto_20230102_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='jome_kari_nerkh',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tax_employer_type',
            field=models.IntegerField(choices=[(1, '7/7'), (2, '2/7')], default=1),
        ),
    ]
