# Generated by Django 2.2 on 2023-01-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0088_auto_20230103_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_asr_shab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_asr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_asr_shab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_shab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
    ]
