# Generated by Django 2.2 on 2023-01-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0090_auto_20230104_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
