# Generated by Django 2.2 on 2023-01-05 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0091_worktitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktitle',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('create.city', 'تعریف عناوین شغلی'), ('get.city', 'مشاهده عناوین شغلی'), ('update.city', 'ویرایش عناوین شغلی'), ('delete.city', 'حذف عناوین شغلی'), ('getOwn.city', 'مشاهده عناوین شغلی های خود'), ('updateOwn.city', 'ویرایش شهر عناوین شغلی خود'), ('deleteOwn.city', 'حذف شهر عناوین شغلی خود')), 'verbose_name': 'WorkTitle'},
        ),
        migrations.AddField(
            model_name='worktitle',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='worktitle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktitle',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worktitle',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True),
        ),
    ]
