# Generated by Django 2.2 on 2023-01-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0094_auto_20230105_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpayitem',
            name='ezafe_kari',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='kasre_kar',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_asr_shab',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_asr',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_asr_shab',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_shab',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='shab_kari',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='tatil_kari',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
