# Generated by Django 2.2 on 2023-01-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0095_auto_20230105_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='current_insurance_history_in_workshop',
        ),
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='insurance_history_totality',
        ),
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='work_title',
        ),
        migrations.RemoveField(
            model_name='workshoppersonnel',
            name='work_title_code',
        ),
    ]
