# Generated by Django 2.2 on 2023-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0098_auto_20230109_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='illness_absence_in_real_work',
            field=models.BooleanField(default=False),
        ),
    ]
