# Generated by Django 2.2 on 2023-01-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0099_workshop_illness_absence_in_real_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofpay',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ('-id',), 'permissions': (('get.list_of_pay', 'مشاهده حقوق و دستمزد'), ('create.list_of_pay', 'تعریف حقوق و دستمزد'), ('update.list_of_pay', 'ویرایش حقوق و دستمزد'), ('delete.list_of_pay', 'حذف حقوق و دستمزد'), ('getOwn.list_of_pay', 'مشاهده حقوق و دستمزد خود'), ('updateOwn.list_of_pay', 'ویرایش حقوق و دستمزد خود'), ('deleteOwn.list_of_pay', 'حذف حقوق و دستمزد خود')), 'verbose_name': 'ListOfPay'},
        ),
    ]
