# Generated by Django 2.2 on 2023-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0100_auto_20230117_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='total_tax',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
