# Generated by Django 2.2 on 2023-01-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0101_listofpayitem_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='hr_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_pay_item', to='payroll.HRLetter'),
        ),
    ]
