# Generated by Django 2.2 on 2023-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0102_listofpayitem_hr_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletter',
            name='tax_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
