# Generated by Django 2.2 on 2023-01-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0103_hrletter_tax_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrletter',
            name='tax_total',
        ),
    ]
