# Generated by Django 2.2 on 2023-01-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0104_remove_hrletter_tax_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaldeduction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
