# Generated by Django 2.2 on 2023-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0105_optionaldeduction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='save_leave',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
