# Generated by Django 2.2 on 2023-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0106_listofpayitem_save_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpayitem',
            name='loan_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
