# Generated by Django 2.2 on 2023-01-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0109_listofpayitem_taamin_ejtemaee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='ezafe_kari_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='kasre_kar_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tatil_kari_nerkh',
            field=models.DecimalField(decimal_places=12, default=0.96, max_digits=24),
        ),
    ]
