# Generated by Django 2.2 on 2023-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0110_auto_20230130_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpayitem',
            name='aele_mandi_nerkh',
            field=models.DecimalField(decimal_places=4, default=3, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='ezafe_kari_nerkh',
            field=models.DecimalField(decimal_places=4, default=1.96, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='kasre_kar_nerkh',
            field=models.DecimalField(decimal_places=4, default=1.4, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='mission_nerkh',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=4, default=0.025, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_asr_nerkh',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_asr_shab_nerkh',
            field=models.DecimalField(decimal_places=4, default=0.15, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='nobat_kari_sob_shab_nerkh',
            field=models.DecimalField(decimal_places=4, default=0.225, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='shab_kari_nerkh',
            field=models.DecimalField(decimal_places=4, default=0.35, max_digits=24),
        ),
        migrations.AlterField(
            model_name='listofpayitem',
            name='tatil_kari_nerkh',
            field=models.DecimalField(decimal_places=4, default=1.96, max_digits=24),
        ),
    ]
