# Generated by Django 2.2 on 2023-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0111_auto_20230201_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppersonnel',
            name='save_leave_limit',
            field=models.IntegerField(default=0),
        ),
    ]
