# Generated by Django 2.2 on 2023-02-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0112_workshoppersonnel_save_leave_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='save_leave_limit',
            field=models.IntegerField(default=0),
        ),
    ]
