# Generated by Django 2.2 on 2023-02-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0115_workshoptaxrow_is_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletter',
            name='paye_sanavat_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=24, null=True),
        ),
    ]
