# Generated by Django 2.2 on 2023-02-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0117_listofpayitem_dept_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpay',
            name='bank_pay_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listofpay',
            name='bank_pay_explanation',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
