# Generated by Django 2.0.5 on 2018-08-05 05:00

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_bank'),
        ('sanads', '0011_auto_20180731_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=24, null=True)),
                ('due', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('predictedDate', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('blank', 'blank'), ('notPassed', 'notPassed'), ('inFlow', 'inFlow'), ('passed', 'passed'), ('bounced', 'bounced'), ('cashed', 'cashed'), ('revoked', 'revoked'), ('transferred', 'transferred')], max_length=30)),
                ('type', models.IntegerField(choices=[('0', 'unknown')])),
                ('transferNumber', models.IntegerField(null=True)),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivedCheques', to='accounts.Account')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Chequebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('serial_from', models.IntegerField()),
                ('serial_to', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chequebook', to='accounts.Account')),
                ('floatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequebook', to='accounts.FloatAccount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='cheque',
            name='chequebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='cheques.Chequebook'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivedCheques', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='sanadItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque', to='sanads.SanadItem'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='transactionItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque', to='sanads.TransactionItem'),
        ),
    ]
