# Generated by Django 2.0.5 on 2018-08-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='transactionItem',
        ),
    ]
