# Generated by Django 2.0.5 on 2019-03-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cheques', '0001_initial'),
        ('sanads', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschange',
            name='sanad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statusChange', to='sanads.Sanad'),
        ),
        migrations.AddField(
            model_name='chequebook',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chequebook', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='chequebook',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequebook', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivedCheques', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='chequebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='cheques.Chequebook'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='floatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivedCheques', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='lastAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lastCheques', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='lastFloatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lastCheques', to='accounts.FloatAccount'),
        ),
    ]
