# Generated by Django 2.2 on 2020-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_auto_20200424_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='serial',
            field=models.IntegerField(),
        ),
    ]
