# Generated by Django 2.0.5 on 2018-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_remove_cheque_transactionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='type',
            field=models.IntegerField(blank=True, choices=[('0', 'unknown')], null=True),
        ),
    ]
