# Generated by Django 2.0.5 on 2019-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_auto_20190310_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='serial',
            field=models.CharField(max_length=255),
        ),
    ]
