# Generated by Django 2.0.5 on 2018-08-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_auto_20180811_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='type',
            field=models.BooleanField(choices=[('0', 'چک پرداختی'), ('1', 'چک دریافتی')], default=0),
            preserve_default=False,
        ),
    ]
