# Generated by Django 2.0.5 on 2018-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_auto_20180912_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='sanad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statusChange', to='sanads.Sanad'),
        ),
    ]
