# Generated by Django 2.2 on 2020-07-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_auto_20200719_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequebook',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
