# Generated by Django 2.2 on 2020-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_auto_20200614_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequebook',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.chequebook', 'مشاهده دفتر چک'), ('create.chequebook', 'تعریف دفتر چک'), ('update.chequebook', 'ویرایش دفتر چک'), ('delete.chequebook', 'حذف دفتر چک')), 'verbose_name': 'دفتر چک'},
        ),
        migrations.RemoveField(
            model_name='chequebook',
            name='code',
        ),
        migrations.AddField(
            model_name='chequebook',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
