# Generated by Django 2.2 on 2020-07-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_chequebook_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequebook',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.chequebook', 'مشاهده دفتر چک'), ('create.chequebook', 'تعریف دفتر چک'), ('update.chequebook', 'ویرایش دفتر چک'), ('delete.chequebook', 'حذف دفتر چک'), ('getOwn.chequebook', 'مشاهده دفتر چک های خود'), ('updateOwn.chequebook', 'ویرایش دفتر چک های خود'), ('deleteOwn.chequebook', 'حذف دفتر چک های خود')), 'verbose_name': 'دفتر چک'},
        ),
    ]
