# Generated by Django 2.0.5 on 2019-03-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_auto_20181017_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='received_or_paid',
            field=models.CharField(choices=[('r', 'دریافتنی'), ('p', 'پرداختنی')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheque',
            name='type',
            field=models.CharField(choices=[('p', 'شخصی'), ('op', 'شخصی سایرین'), ('c', 'شرکت'), ('oc', 'شرکت سایرین')], max_length=10),
        ),
    ]
