# Generated by Django 2.0.5 on 2018-08-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_auto_20180812_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='type',
            field=models.IntegerField(blank=True, choices=[('0', 'unknown')], null=True),
        ),
    ]
