# Generated by Django 2.0.5 on 2018-08-13 04:44

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bank'),
        ('cheques', '0005_auto_20180812_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('fromStatus', models.CharField(choices=[('blank', 'blank'), ('notPassed', 'notPassed'), ('inFlow', 'inFlow'), ('passed', 'passed'), ('bounced', 'bounced'), ('cashed', 'cashed'), ('revoked', 'revoked'), ('transferred', 'transferred')], max_length=30)),
                ('toStatus', models.CharField(choices=[('blank', 'blank'), ('notPassed', 'notPassed'), ('inFlow', 'inFlow'), ('passed', 'passed'), ('bounced', 'bounced'), ('cashed', 'cashed'), ('revoked', 'revoked'), ('transferred', 'transferred')], max_length=30)),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('bedAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequeStatusChangesAsBedAccount', to='accounts.Account')),
                ('bedFloatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequeStatusChangesAsBesAccount', to='accounts.Account')),
                ('besAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequeStatusChangesAsBedFloatAccount', to='accounts.Account')),
                ('besFloatAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequeStatusChangesAsBesFloatAccount', to='accounts.Account')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='predictedDate',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='cheque',
            name='type',
            field=models.CharField(choices=[('paid', 'پرداختی'), ('received', 'دریافتی')], default='paid', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statuschange',
            name='cheque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusChanges', to='cheques.Cheque'),
        ),
    ]
