# Generated by Django 2.0.5 on 2019-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_auto_20190404_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chequebook',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='statuschange',
            name='source_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
