# Generated by Django 2.0.5 on 2018-08-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bank'),
        ('cheques', '0006_auto_20180813_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='lastAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lastCheques', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='lastFloatAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lastCheques', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='statuschange',
            name='bankName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statuschange',
            name='branchName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statuschange',
            name='chequeAccountNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
