# Generated by Django 2.0.5 on 2019-04-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_auto_20190409_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='chequebook',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='statuschange',
            name='source_id',
        ),
    ]
