# Generated by Django 2.0.5 on 2018-08-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_auto_20180814_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuschange',
            name='bankName',
        ),
        migrations.RemoveField(
            model_name='statuschange',
            name='branchName',
        ),
        migrations.RemoveField(
            model_name='statuschange',
            name='chequeAccountNumber',
        ),
        migrations.AddField(
            model_name='cheque',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bankName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='branchName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
