# Generated by Django 2.2 on 2020-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_auto_20190410_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='explanation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
