# Generated by Django 2.2 on 2020-07-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0008_auto_20200726_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chequebook',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
