# Generated by Django 2.2 on 2020-03-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_defaultaccount_costcenter'),
        ('cheques', '0008_auto_20200303_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivedChequesAsCostCenter', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='lastCostCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lastChequesAsCostCenter', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='chequebook',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequebooksAsCostCenter', to='accounts.FloatAccount'),
        ),
    ]
