# Generated by Django 2.2 on 2020-07-29 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheques', '0009_auto_20200726_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'default_permissions': (), 'ordering': ['serial'], 'permissions': (('get.receivedCheque', 'مشاهده چک دریافتی'), ('update.receivedCheque', 'ویرایش چک دریافتی'), ('delete.receivedCheque', 'حذف چک دریافتی'), ('submit.receivedCheque', 'ثبت چک دریافتی'), ('changeStatus.receivedCheque', 'تغییر وضعیت دریافتی'), ('get.paidCheque', 'مشاهده چک پرداختی'), ('update.paidCheque', 'ویرایش چک پرداختی'), ('delete.paidCheque', 'حذف چک پرداختی'), ('submit.paidCheque', 'ثبت چک پرداختی'), ('changeStatus.paidCheque', 'تغییر وضعیت پرداختی'), ('getOwn.receivedCheque', 'مشاهده چک های دریافتی خود'), ('updateOwn.receivedCheque', 'ویرایش چک های دریافتی خود'), ('deleteOwn.receivedCheque', 'حذف چک های دریافتی خود'), ('changeStatusOwn.receivedCheque', 'تغییر وضعیت های دریافتی خود'), ('getOwn.paidCheque', 'مشاهده چک های پرداختی خود'), ('updateOwn.paidCheque', 'ویرایش چک های پرداختی خود'), ('deleteOwn.paidCheque', 'حذف چک های پرداختی خود'), ('changeStatusOwn.paidCheque', 'تغییر وضعیت های پرداختی خود'), ('firstConfirm.receivedCheque', 'تایید اول چک دریافتی'), ('secondConfirm.receivedCheque', 'تایید دوم چک دریافتی'), ('firstConfirmOwn.receivedCheque', 'تایید اول چک های دریافتی خود'), ('secondConfirmOwn.receivedCheque', 'تایید دوم چک های دریافتی خود'), ('firstConfirm.paidCheque', 'تایید اول چک پرداختی '), ('secondConfirm.paidCheque', 'تایید دوم چک پرداختی '), ('firstConfirmOwn.paidCheque', 'تایید اول چک های پرداختی خود'), ('secondConfirmOwn.paidCheque', 'تایید دوم چک های پرداختی خود')), 'verbose_name': 'چک'},
        ),
        migrations.AddField(
            model_name='cheque',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='first_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_chequeConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='second_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_chequeConfirmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
