# Generated by Django 2.2 on 2020-10-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_auto_20200729_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_cheque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chequebook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_chequebook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_statuschange', to=settings.AUTH_USER_MODEL),
        ),
    ]
