# Generated by Django 2.0.5 on 2018-08-16 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_statuschange_sanad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='sanad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statusChange', to='sanads.Sanad'),
        ),
    ]
