# Generated by Django 2.2 on 2020-03-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_auto_20200310_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusChanges', to='companies.FinancialYear'),
        ),
    ]
