# Generated by Django 2.2 on 2020-04-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0011_auto_20200314_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['serial'], 'permissions': (), 'verbose_name': 'چک'},
        ),
        migrations.AlterModelOptions(
            name='chequebook',
            options={'ordering': ['code'], 'permissions': (), 'verbose_name': 'دفتر چک'},
        ),
        migrations.AlterModelOptions(
            name='statuschange',
            options={'ordering': ['id'], 'permissions': (), 'verbose_name': 'تغییر وضعیت'},
        ),
    ]
