# Generated by Django 2.0.5 on 2018-08-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0011_auto_20180816_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='bedAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chequeStatusChangesAsBedAccount', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='besAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chequeStatusChangesAsBedFloatAccount', to='accounts.Account'),
        ),
    ]
