# Generated by Django 2.0.5 on 2018-08-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0012_auto_20180816_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuschange',
            options={'ordering': ['id']},
        ),
    ]
