# Generated by Django 2.2 on 2020-04-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0012_auto_20200422_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'default_permissions': (), 'ordering': ['serial'], 'permissions': (), 'verbose_name': 'چک'},
        ),
        migrations.AlterModelOptions(
            name='chequebook',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (), 'verbose_name': 'دفتر چک'},
        ),
        migrations.AlterModelOptions(
            name='statuschange',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': (), 'verbose_name': 'تغییر وضعیت'},
        ),
    ]
