# Generated by Django 2.0.5 on 2018-08-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0013_auto_20180817_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='sanadItem',
        ),
    ]
