# Generated by Django 2.2 on 2020-04-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0013_auto_20200422_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'default_permissions': (), 'ordering': ['serial'], 'permissions': (('get.receivedCheque', 'مشاهده چک دریافتی'), ('update.receivedCheque', 'ویرایش چک دریافتی'), ('delete.receivedCheque', 'حذف چک دریافتی'), ('submit.receivedCheque', 'ثبت چک دریافتی'), ('changeStatus.receivedCheque', 'تغییر وضعیت دریافتی'), ('get.paidCheque', 'مشاهده چک پرداختی'), ('update.paidCheque', 'ویرایش چک پرداختی'), ('delete.paidCheque', 'حذف چک پرداختی'), ('submit.paidCheque', 'ثبت چک پرداختی'), ('changeStatus.paidCheque', 'تغییر وضعیت پرداختی')), 'verbose_name': 'چک'},
        ),
        migrations.AlterModelOptions(
            name='chequebook',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': (('get.chequebook', 'مشاهده دفتر چک'), ('create.chequebook', 'تعریف دفتر چک'), ('update.chequebook', 'ویرایش دفتر چک'), ('delete.chequebook', 'حذف دفتر چک')), 'verbose_name': 'دفتر چک'},
        ),
        migrations.AlterModelOptions(
            name='statuschange',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': (('delete.receivedChequeStatusChange', 'حذف تغییر وضعیت های چک دریافتی'), ('delete.paidChequeStatusChange', 'حذف تغییر وضعیت های چک پرداختی')), 'verbose_name': 'تغییر وضعیت'},
        ),
    ]
