# Generated by Django 2.2 on 2021-06-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0016_auto_20210519_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='bedAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequeStatusChangesAsBedAccount', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='besAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequeStatusChangesAsBedFloatAccount', to='accounts.Account'),
        ),
    ]
