# Generated by Django 2.2 on 2021-09-07 10:34

from django.db import migrations, models


def fill_is_paid(apps, schema_editor):
    Cheque = apps.get_model("cheques", "Cheque")
    for cheque in Cheque.objects.all():
        cheque.is_paid = cheque.received_or_paid == 'p'
        cheque.save()


def fill_received_or_paid(apps, schema_editor):
    Cheque = apps.get_model("cheques", "Cheque")
    for cheque in Cheque.objects.all():
        cheque.received_or_paid = 'p' if cheque.is_paid else 'r'
        cheque.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cheques', '0017_auto_20210602_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['serial'], 'permissions': (
                ('get.receivedCheque', 'مشاهده چک دریافتی'), ('update.receivedCheque', 'ویرایش چک دریافتی'),
                ('delete.receivedCheque', 'حذف چک دریافتی'), ('submit.receivedCheque', 'ثبت چک دریافتی'),
                ('changeStatus.receivedCheque', 'تغییر وضعیت دریافتی'), ('get.paidCheque', 'مشاهده چک پرداختی'),
                ('update.paidCheque', 'ویرایش چک پرداختی'), ('delete.paidCheque', 'حذف چک پرداختی'),
                ('submit.paidCheque', 'ثبت چک پرداختی'), ('changeStatus.paidCheque', 'تغییر وضعیت پرداختی'),
                ('getOwn.receivedCheque', 'مشاهده چک های دریافتی خود'),
                ('updateOwn.receivedCheque', 'ویرایش چک های دریافتی خود'),
                ('deleteOwn.receivedCheque', 'حذف چک های دریافتی خود'),
                ('changeStatusOwn.receivedCheque', 'تغییر وضعیت های دریافتی خود'),
                ('getOwn.paidCheque', 'مشاهده چک های پرداختی خود'),
                ('updateOwn.paidCheque', 'ویرایش چک های پرداختی خود'),
                ('deleteOwn.paidCheque', 'حذف چک های پرداختی خود'),
                ('changeStatusOwn.paidCheque', 'تغییر وضعیت های پرداختی خود')), 'verbose_name': 'چک'},
        ),
        migrations.AddField(
            model_name='cheque',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cheque',
            name='owner_type',
            field=models.CharField(blank=True,
                                   choices=[('p', 'شخصی'), ('op', 'شخصی سایرین'), ('c', 'شرکت'), ('oc', 'شرکت سایرین')],
                                   max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='type',
            field=models.CharField(choices=[('c', 'چک'), ('pn', 'سفته'), ('bg', 'ضمانت نامه بانکی')], default='c',
                                   max_length=2),
        ),
        migrations.RunPython(fill_is_paid, fill_received_or_paid)
    ]
