# Generated by Django 2.2 on 2021-09-07 10:50

from django.db import migrations


def fill_type(apps, schema_editor):
    Cheque = apps.get_model("cheques", "Cheque")
    for cheque in Cheque.objects.all():
        cheque.type = 'c'
        cheque.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cheques', '0018_auto_20210907_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='received_or_paid',
        ),
        migrations.RunPython(fill_type, migrations.RunPython.noop)
    ]
