# Generated by Django 2.2 on 2021-10-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0019_remove_cheque_received_or_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='type',
            field=models.CharField(choices=[('c', 'چک'), ('gc', 'چک ضمانتی'), ('pn', 'سفته'), ('bg', 'ضمانت نامه بانکی')], default='c', max_length=2),
        ),
    ]
