# Generated by Django 2.2 on 2021-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0020_auto_20211017_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('blank', 'سفید'), ('notPassed', 'پاس نشده'), ('guarantee', 'ضمانتی'), ('inFlow', 'در جریان'), ('passed', 'پاس شده'), ('bounced', 'برگشتی'), ('cached', 'نقد شده'), ('revoked', 'باطل شده'), ('transferred', 'انتقالی'), ('revokeGuarantee', 'ابطال ضمانتی')], max_length=30),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='fromStatus',
            field=models.CharField(choices=[('blank', 'سفید'), ('notPassed', 'پاس نشده'), ('guarantee', 'ضمانتی'), ('inFlow', 'در جریان'), ('passed', 'پاس شده'), ('bounced', 'برگشتی'), ('cached', 'نقد شده'), ('revoked', 'باطل شده'), ('transferred', 'انتقالی'), ('revokeGuarantee', 'ابطال ضمانتی')], max_length=30),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='toStatus',
            field=models.CharField(choices=[('blank', 'سفید'), ('notPassed', 'پاس نشده'), ('guarantee', 'ضمانتی'), ('inFlow', 'در جریان'), ('passed', 'پاس شده'), ('bounced', 'برگشتی'), ('cached', 'نقد شده'), ('revoked', 'باطل شده'), ('transferred', 'انتقالی'), ('revokeGuarantee', 'ابطال ضمانتی')], max_length=30),
        ),
    ]
