# Generated by Django 2.2 on 2022-08-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0021_auto_20211027_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('blank', 'سفید'), ('notPassed', 'پاس نشده'), ('guarantee', 'ضمانتی'), ('inFlow', 'در جریان'), ('passed', 'پاس شده'), ('bounced', 'برگشتی'), ('cashed', 'نقد شده'), ('revoked', 'باطل شده'), ('transferred', 'انتقالی'), ('extended', 'تمدید شده')], max_length=30),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='fromStatus',
            field=models.CharField(choices=[('blank', 'سفید'), ('notPassed', 'پاس نشده'), ('guarantee', 'ضمانتی'), ('inFlow', 'در جریان'), ('passed', 'پاس شده'), ('bounced', 'برگشتی'), ('cashed', 'نقد شده'), ('revoked', 'باطل شده'), ('transferred', 'انتقالی'), ('extended', 'تمدید شده')], max_length=30),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='toStatus',
            field=models.CharField(choices=[('blank', 'سفید'), ('notPassed', 'پاس نشده'), ('guarantee', 'ضمانتی'), ('inFlow', 'در جریان'), ('passed', 'پاس شده'), ('bounced', 'برگشتی'), ('cashed', 'نقد شده'), ('revoked', 'باطل شده'), ('transferred', 'انتقالی'), ('extended', 'تمدید شده')], max_length=30),
        ),
    ]
