from decimal import Decimal

from django.core.management.base import BaseCommand

from factors.models import FactorItem
from helpers.test import set_user
from users.models import User
from wares.models import Ware, SalePriceType, SalePrice, Unit


class Command(BaseCommand):
    help = 'Tmp command, for testing, correcting, bug fixing and etc'

    def handle(self, *args, **options):
        set_user(User.objects.get(pk=1))

        wares_units = [{'id': 176, 'unit_id': 18, 'price': None}, {'id': 401, 'unit_id': 26, 'price': None},
                       {'id': 194, 'unit_id': 20, 'price': None}, {'id': 180, 'unit_id': 1, 'price': None},
                       {'id': 207, 'unit_id': 21, 'price': Decimal('100')},
                       {'id': 186, 'unit_id': 19, 'price': Decimal('15000000')},
                       {'id': 317, 'unit_id': 25, 'price': None}, {'id': 203, 'unit_id': 19, 'price': None},
                       {'id': 318, 'unit_id': 25, 'price': None}, {'id': 181, 'unit_id': 1, 'price': Decimal('1000')},
                       {'id': 402, 'unit_id': 26, 'price': None}, {'id': 182, 'unit_id': 1, 'price': Decimal('1000')},
                       {'id': 319, 'unit_id': 25, 'price': None}, {'id': 190, 'unit_id': 1, 'price': Decimal('20000')},
                       {'id': 320, 'unit_id': 25, 'price': None}, {'id': 321, 'unit_id': 25, 'price': None},
                       {'id': 322, 'unit_id': 25, 'price': None}, {'id': 323, 'unit_id': 25, 'price': None},
                       {'id': 324, 'unit_id': 25, 'price': None}, {'id': 325, 'unit_id': 25, 'price': None},
                       {'id': 326, 'unit_id': 25, 'price': None}, {'id': 327, 'unit_id': 25, 'price': None},
                       {'id': 328, 'unit_id': 25, 'price': None}, {'id': 329, 'unit_id': 25, 'price': None},
                       {'id': 330, 'unit_id': 25, 'price': None}, {'id': 333, 'unit_id': 25, 'price': None},
                       {'id': 334, 'unit_id': 25, 'price': None}, {'id': 335, 'unit_id': 25, 'price': None},
                       {'id': 336, 'unit_id': 25, 'price': None}, {'id': 337, 'unit_id': 25, 'price': None},
                       {'id': 338, 'unit_id': 25, 'price': None}, {'id': 367, 'unit_id': 25, 'price': None},
                       {'id': 379, 'unit_id': 25, 'price': None}, {'id': 383, 'unit_id': 25, 'price': None},
                       {'id': 405, 'unit_id': 25, 'price': None}, {'id': 420, 'unit_id': 25, 'price': None},
                       {'id': 430, 'unit_id': 25, 'price': None}, {'id': 436, 'unit_id': 25, 'price': None},
                       {'id': 457, 'unit_id': 25, 'price': None}, {'id': 460, 'unit_id': 25, 'price': None},
                       {'id': 475, 'unit_id': 25, 'price': None}, {'id': 476, 'unit_id': 25, 'price': None},
                       {'id': 429, 'unit_id': 25, 'price': None}, {'id': 423, 'unit_id': 25, 'price': None},
                       {'id': 473, 'unit_id': 25, 'price': None},
                       {'id': 198, 'unit_id': 19, 'price': Decimal('120000')}, {'id': 130, 'unit_id': 8, 'price': None},
                       {'id': 131, 'unit_id': 8, 'price': Decimal('59285714')},
                       {'id': 132, 'unit_id': 8, 'price': None}, {'id': 133, 'unit_id': 8, 'price': None},
                       {'id': 134, 'unit_id': 8, 'price': None}, {'id': 135, 'unit_id': 8, 'price': None},
                       {'id': 136, 'unit_id': 8, 'price': None}, {'id': 137, 'unit_id': 8, 'price': None},
                       {'id': 138, 'unit_id': 8, 'price': None},
                       {'id': 139, 'unit_id': 8, 'price': Decimal('25102500')},
                       {'id': 331, 'unit_id': 25, 'price': None}, {'id': 332, 'unit_id': 25, 'price': None},
                       {'id': 339, 'unit_id': 25, 'price': None}, {'id': 144, 'unit_id': 7, 'price': None},
                       {'id': 340, 'unit_id': 25, 'price': None}, {'id': 378, 'unit_id': 25, 'price': None},
                       {'id': 341, 'unit_id': 25, 'price': None}, {'id': 145, 'unit_id': 7, 'price': None},
                       {'id': 342, 'unit_id': 25, 'price': None}, {'id': 419, 'unit_id': 25, 'price': None},
                       {'id': 443, 'unit_id': 25, 'price': None}, {'id': 343, 'unit_id': 25, 'price': None},
                       {'id': 148, 'unit_id': 8, 'price': None}, {'id': 395, 'unit_id': 25, 'price': None},
                       {'id': 374, 'unit_id': 25, 'price': None}, {'id': 393, 'unit_id': 25, 'price': None},
                       {'id': 391, 'unit_id': 25, 'price': None}, {'id': 397, 'unit_id': 25, 'price': None},
                       {'id': 344, 'unit_id': 25, 'price': None}, {'id': 345, 'unit_id': 25, 'price': None},
                       {'id': 346, 'unit_id': 25, 'price': None}, {'id': 347, 'unit_id': 25, 'price': None},
                       {'id': 377, 'unit_id': 25, 'price': None}, {'id': 461, 'unit_id': 25, 'price': None},
                       {'id': 348, 'unit_id': 25, 'price': None}, {'id': 349, 'unit_id': 25, 'price': None},
                       {'id': 350, 'unit_id': 25, 'price': None}, {'id': 351, 'unit_id': 25, 'price': None},
                       {'id': 352, 'unit_id': 25, 'price': None}, {'id': 353, 'unit_id': 25, 'price': None},
                       {'id': 446, 'unit_id': 25, 'price': None}, {'id': 478, 'unit_id': 25, 'price': None},
                       {'id': 354, 'unit_id': 25, 'price': None}, {'id': 355, 'unit_id': 25, 'price': None},
                       {'id': 356, 'unit_id': 25, 'price': None}, {'id': 357, 'unit_id': 25, 'price': None},
                       {'id': 435, 'unit_id': 25, 'price': None}, {'id': 434, 'unit_id': 25, 'price': None},
                       {'id': 442, 'unit_id': 25, 'price': None}, {'id': 411, 'unit_id': 25, 'price': None},
                       {'id': 412, 'unit_id': 25, 'price': None}, {'id': 418, 'unit_id': 25, 'price': None},
                       {'id': 432, 'unit_id': 25, 'price': None}, {'id': 439, 'unit_id': 25, 'price': None},
                       {'id': 441, 'unit_id': 25, 'price': None}, {'id': 481, 'unit_id': 25, 'price': None},
                       {'id': 414, 'unit_id': 25, 'price': None}, {'id': 477, 'unit_id': 25, 'price': None},
                       {'id': 358, 'unit_id': 25, 'price': None}, {'id': 359, 'unit_id': 25, 'price': None},
                       {'id': 360, 'unit_id': 25, 'price': None}, {'id': 365, 'unit_id': 25, 'price': None},
                       {'id': 366, 'unit_id': 25, 'price': None}, {'id': 440, 'unit_id': 25, 'price': None},
                       {'id': 445, 'unit_id': 25, 'price': None}, {'id': 448, 'unit_id': 25, 'price': None},
                       {'id': 479, 'unit_id': 25, 'price': None}, {'id': 361, 'unit_id': 25, 'price': None},
                       {'id': 362, 'unit_id': 25, 'price': None}, {'id': 363, 'unit_id': 25, 'price': None},
                       {'id': 364, 'unit_id': 25, 'price': None}, {'id': 404, 'unit_id': 25, 'price': None},
                       {'id': 409, 'unit_id': 25, 'price': None}, {'id': 433, 'unit_id': 25, 'price': None},
                       {'id': 447, 'unit_id': 25, 'price': None}, {'id': 382, 'unit_id': 25, 'price': None},
                       {'id': 408, 'unit_id': 25, 'price': None}, {'id': 431, 'unit_id': 25, 'price': None},
                       {'id': 417, 'unit_id': 25, 'price': None}, {'id': 437, 'unit_id': 25, 'price': None},
                       {'id': 459, 'unit_id': 25, 'price': None}, {'id': 480, 'unit_id': 25, 'price': None},
                       {'id': 438, 'unit_id': 25, 'price': None}, {'id': 458, 'unit_id': 25, 'price': None},
                       {'id': 462, 'unit_id': 25, 'price': None}, {'id': 474, 'unit_id': 25, 'price': None},
                       {'id': 456, 'unit_id': 25, 'price': None}, {'id': 53, 'unit_id': 12, 'price': Decimal('1200')},
                       {'id': 78, 'unit_id': 12, 'price': None}, {'id': 79, 'unit_id': 12, 'price': None},
                       {'id': 80, 'unit_id': 12, 'price': None}, {'id': 81, 'unit_id': 12, 'price': None},
                       {'id': 82, 'unit_id': 12, 'price': None}, {'id': 83, 'unit_id': 12, 'price': None},
                       {'id': 84, 'unit_id': 12, 'price': None}, {'id': 172, 'unit_id': 12, 'price': None},
                       {'id': 117, 'unit_id': 12, 'price': None}, {'id': 467, 'unit_id': 12, 'price': None},
                       {'id': 85, 'unit_id': 12, 'price': None}, {'id': 168, 'unit_id': 12, 'price': Decimal('0')},
                       {'id': 213, 'unit_id': 12, 'price': None}, {'id': 394, 'unit_id': 12, 'price': None},
                       {'id': 470, 'unit_id': 12, 'price': None}, {'id': 88, 'unit_id': 9, 'price': Decimal('395600')},
                       {'id': 89, 'unit_id': 9, 'price': Decimal('192625')},
                       {'id': 90, 'unit_id': 9, 'price': Decimal('253000')},
                       {'id': 91, 'unit_id': 9, 'price': Decimal('391000')},
                       {'id': 92, 'unit_id': 7, 'price': Decimal('270250')},
                       {'id': 95, 'unit_id': 7, 'price': Decimal('885500')},
                       {'id': 96, 'unit_id': 7, 'price': Decimal('874000')},
                       {'id': 97, 'unit_id': 7, 'price': Decimal('839500')},
                       {'id': 98, 'unit_id': 7, 'price': Decimal('1587000')},
                       {'id': 99, 'unit_id': 7, 'price': Decimal('552000')},
                       {'id': 100, 'unit_id': 7, 'price': Decimal('345000')},
                       {'id': 101, 'unit_id': 7, 'price': Decimal('1989500')},
                       {'id': 102, 'unit_id': 7, 'price': Decimal('230000')},
                       {'id': 103, 'unit_id': 7, 'price': Decimal('1000500')},
                       {'id': 115, 'unit_id': 17, 'price': Decimal('6037500')},
                       {'id': 209, 'unit_id': 7, 'price': Decimal('655500')}, {'id': 449, 'unit_id': 7, 'price': None},
                       {'id': 450, 'unit_id': 7, 'price': Decimal('4427500')},
                       {'id': 451, 'unit_id': 7, 'price': Decimal('4025000')},
                       {'id': 452, 'unit_id': 7, 'price': Decimal('2415000')},
                       {'id': 453, 'unit_id': 7, 'price': Decimal('3737500')},
                       {'id': 106, 'unit_id': 10, 'price': Decimal('358513')},
                       {'id': 107, 'unit_id': 10, 'price': Decimal('2300000')},
                       {'id': 110, 'unit_id': 9, 'price': Decimal('310500')},
                       {'id': 111, 'unit_id': 9, 'price': Decimal('258750')},
                       {'id': 114, 'unit_id': 7, 'price': Decimal('146050')}, {'id': 152, 'unit_id': 7, 'price': None},
                       {'id': 155, 'unit_id': 7, 'price': None}, {'id': 158, 'unit_id': 17, 'price': None},
                       {'id': 159, 'unit_id': 17, 'price': None}, {'id': 162, 'unit_id': 7, 'price': None},
                       {'id': 165, 'unit_id': 9, 'price': None}, {'id': 171, 'unit_id': 7, 'price': None},
                       {'id': 189, 'unit_id': 7, 'price': Decimal('1035000')}, {'id': 202, 'unit_id': 7, 'price': None}]

        for ware_unit in wares_units:
            print(ware_unit)
            ware = Ware.objects.get(pk=ware_unit['id'])
            unit = Unit.objects.get(pk=ware_unit['unit_id'])
            FactorItem.objects.filter(ware=ware).update(unit=unit)
