# Generated by Django 2.2 on 2020-06-24 09:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20200618_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('car_number', models.CharField(max_length=150)),
                ('smart_card_number', models.CharField(blank=True, max_length=150, null=True)),
                ('owner', models.CharField(choices=[('c', 'شرکت'), ('o', 'دیگر'), ('rn', 'رحمان'), ('rm', 'رحیم'), ('e', 'ابراهیم')], max_length=2)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.car', 'مشاهده ماشین'), ('create.car', 'تعریف ماشین'), ('update.car', 'ویرایش ماشین'), ('delete.car', 'حذف ماشین')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=150)),
                ('shenasname_number', models.CharField(blank=True, max_length=150, null=True)),
                ('melli_code', models.CharField(blank=True, max_length=10, null=True, validators=[helpers.models.is_valid_melli_code])),
                ('date_of_birth', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('driving_licence_number', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول شماره موبایل باید 11 رقم باشد', regex='^.{11}$')])),
                ('health_card_number', models.CharField(blank=True, max_length=150, null=True)),
                ('landline_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_card_number', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('iban', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.driver', 'مشاهده راننده'), ('create.driver', 'تعریف راننده'), ('update.driver', 'ویرایش راننده'), ('delete.driver', 'حذف راننده')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Driving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_cost', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('fixed_salary', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('commission', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('reward', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('family', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivings', to='accounts.Account')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivings', to='_dashtbashi.Car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivings', to='_dashtbashi.Driver')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.driving', 'مشاهده انتصاب راننده به ماشین'), ('create.driving', 'تعریف انتصاب راننده به ماشین'), ('update.driving', 'ویرایش انتصاب راننده به ماشین'), ('delete.driving', 'حذف انتصاب راننده به ماشین')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
