# Generated by Django 2.2 on 2020-07-19 12:42

import _dashtbashi.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django_jalali.db.models
import helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.association', 'مشاهده کمیسیون انجمن'), ('create.association', 'تعریف کمیسیون انجمن'), ('update.association', 'ویرایش کمیسیون انجمن'), ('delete.association', 'حذف کمیسیون انجمن')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('car_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=4)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_melli_code', models.CharField(blank=True, max_length=10, null=True, validators=[helpers.models.is_valid_melli_code])),
                ('vin', models.CharField(blank=True, max_length=150, null=True)),
                ('smart_card_number', models.CharField(blank=True, max_length=150, null=True)),
                ('owner', models.CharField(choices=[('p', 'شراکتی'), ('o', 'دیگر'), ('rn', 'حاج رحمان'), ('rm', 'حاج رحیم'), ('e', 'حاج ابراهیم')], max_length=2)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.car', 'مشاهده ماشین'), ('create.car', 'تعریف ماشین'), ('update.car', 'ویرایش ماشین'), ('delete.car', 'حذف ماشین')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('shenasname_number', models.CharField(blank=True, max_length=150, null=True)),
                ('melli_code', models.CharField(blank=True, max_length=10, null=True, validators=[helpers.models.is_valid_melli_code])),
                ('date_of_birth', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('driving_licence_number', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='طول شماره موبایل باید 11 رقم باشد', regex='^.{11}$')])),
                ('health_card_number', models.CharField(blank=True, max_length=150, null=True)),
                ('landline_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_card_number', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('iban', models.CharField(blank=True, max_length=150, null=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.driver', 'مشاهده راننده'), ('create.driver', 'تعریف راننده'), ('update.driver', 'ویرایش راننده'), ('delete.driver', 'حذف راننده')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Driving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('mobile_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('fixed_salary', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('commission', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('reward', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('family', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.driving', 'مشاهده انتصاب راننده به ماشین'), ('create.driving', 'تعریف انتصاب راننده به ماشین'), ('update.driving', 'ویرایش انتصاب راننده به ماشین'), ('delete.driving', 'حذف انتصاب راننده به ماشین')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Lading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('driver_tip_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('driver_tip_payer', models.CharField(choices=[('cmp', 'شرکت'), ('cnt', 'پیمانکار')], max_length=3)),
                ('lading_bill_difference', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('remittance_payment_method', models.CharField(choices=[('tc', 'کمیسیون و کرایه به شرکت'), ('tcd', 'کمیسیون به شرکت و کرایه به راننده'), ('cp', 'کمیسیون و کرایه با شرکت')], max_length=3)),
                ('fare_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('lading_number', models.IntegerField()),
                ('lading_date', django_jalali.db.models.jDateField()),
                ('original_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('destination_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('lading_explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('lading_attachment', models.FileField(blank=True, null=True, upload_to=_dashtbashi.models.upload_attachment_to)),
                ('bill_date', django_jalali.db.models.jDateField()),
                ('bill_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('bill_explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_attachment', models.FileField(blank=True, null=True, upload_to=_dashtbashi.models.upload_attachment_to)),
                ('cargo_tip_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('association_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('receive_type', models.CharField(blank=True, choices=[('cr', 'نسیه'), ('cs', 'نقدی'), ('p', 'کارت خوان')], max_length=2, null=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.lading', 'مشاهده بارگیری'), ('create.lading', 'تعریف بارگیری'), ('update.lading', 'ویرایش بارگیری'), ('delete.lading', 'حذف بارگیری')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LadingBillNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('number', models.IntegerField()),
                ('is_revoked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('revoke.ladingBillNumber', 'ابطال شماره بارنامه'),),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LadingBillSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('serial', models.CharField(max_length=100)),
                ('from_bill_number', models.IntegerField()),
                ('to_bill_number', models.IntegerField()),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.ladingBillSeries', 'مشاهده سری بارنامه'), ('create.ladingBillSeries', 'تعریف سری بارنامه'), ('update.ladingBillSeries', 'ویرایش سری بارنامه'), ('delete.ladingBillSeries', 'حذف سری بارنامه')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OilCompanyLading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('export_date', django_jalali.db.models.jDateField()),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.oilCompanyLading', 'مشاهده بارگیری شرکت نفت'), ('create.oilCompanyLading', 'تعریف بارگیری شرکت نفت'), ('update.oilCompanyLading', 'ویرایش بارگیری شرکت نفت'), ('delete.oilCompanyLading', 'حذف بارگیری شرکت نفت')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OilCompanyLadingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('gross_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('insurance_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tax_value', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True)),
                ('tax_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('complication_value', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True)),
                ('complication_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('company_commission', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('car_income', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('driver_tip_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('driver_tip_payer', models.CharField(choices=[('cmp', 'شرکت'), ('cnt', 'پیمانکار')], max_length=3)),
                ('lading_bill_difference', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('remittance_payment_method', models.CharField(choices=[('tc', 'کمیسیون و کرایه به شرکت'), ('tcd', 'کمیسیون به شرکت و کرایه به راننده'), ('cp', 'کمیسیون و کرایه با شرکت')], max_length=3)),
                ('fare_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('code', models.IntegerField(unique=True)),
                ('issue_date', django_jalali.db.models.jDateField()),
                ('loading_date', django_jalali.db.models.jDateField()),
                ('end_date', django_jalali.db.models.jDateField()),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-code'],
                'permissions': (('get.remittance', 'مشاهده حواله'), ('create.remittance', 'تعریف حواله'), ('update.remittance', 'ویرایش حواله'), ('delete.remittance', 'حذف حواله')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
