# Generated by Django 2.2 on 2020-06-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200614_1141'),
        ('_dashtbashi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='companies.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driving',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drivings', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
