# Generated by Django 2.2 on 2020-07-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('_dashtbashi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
    ]
