# Generated by Django 2.2 on 2020-07-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0001_initial'),
        ('wares', '0001_initial'),
        ('companies', '0001_initial'),
        ('_dashtbashi', '0002_remittance_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittance',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittanceDestinations', to='users.City'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittanceOrigins', to='users.City'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wares.Ware'),
        ),
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='oilCompanyLading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='_dashtbashi.OilCompanyLading'),
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oilCompanyLadings', to='_dashtbashi.Car'),
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilCompanyLadings', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='ladingbillseries',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ladingbillnumber',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ladingbillnumber',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='_dashtbashi.LadingBillSeries'),
        ),
        migrations.AddField(
            model_name='lading',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='_dashtbashi.Association'),
        ),
        migrations.AddField(
            model_name='lading',
            name='billNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='_dashtbashi.LadingBillNumber'),
        ),
        migrations.AddField(
            model_name='lading',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='lading',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lading',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ladingDestinations', to='users.City'),
        ),
        migrations.AddField(
            model_name='lading',
            name='driving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='_dashtbashi.Driving'),
        ),
        migrations.AddField(
            model_name='lading',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladings', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='lading',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ladingOrigins', to='users.City'),
        ),
        migrations.AddField(
            model_name='lading',
            name='remittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='_dashtbashi.Remittance'),
        ),
        migrations.AddField(
            model_name='lading',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wares.Ware'),
        ),
        migrations.AddField(
            model_name='driving',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivings', to='_dashtbashi.Car'),
        ),
        migrations.AddField(
            model_name='driving',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driving',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivings', to='_dashtbashi.Driver'),
        ),
        migrations.AddField(
            model_name='driving',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivings', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='driving',
            name='floatAccountRelation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driving', to='accounts.FloatAccountRelation'),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='driver',
            name='floatAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='car',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='expenseAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carExpense', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='car',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='companies.FinancialYear'),
        ),
        migrations.AddField(
            model_name='car',
            name='incomeAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carIncome', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='car',
            name='payableAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carPayable', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='car',
            name='receivableAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carReceivable', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='association',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='association',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='companies.FinancialYear'),
        ),
    ]
