# Generated by Django 2.2 on 2020-06-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200614_1141'),
        ('_dashtbashi', '0002_auto_20200624_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associationCommissions', to='companies.FinancialYear')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.associationCommission', 'مشاهده کمیسیون انجمن'), ('create.associationCommission', 'تعریف کمیسیون انجمن'), ('update.associationCommission', 'ویرایش کمیسیون انجمن'), ('delete.associationCommission', 'حذف کمیسیون انجمن')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
