# Generated by Django 2.2 on 2020-06-24 12:34

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200618_1600'),
        ('users', '0005_city'),
        ('wares', '0012_auto_20200624_1518'),
        ('_dashtbashi', '0003_associationcommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.IntegerField()),
                ('issue_date', django_jalali.db.models.jDateField()),
                ('loading_date', django_jalali.db.models.jDateField()),
                ('end_date', django_jalali.db.models.jDateField()),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('contractor_price', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('fare_price', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('tip_price', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('tip_payer', models.CharField(choices=[('cmp', 'شرکت'), ('cnt', 'پیمانکار')], max_length=3)),
                ('lading_bill_difference', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('remittance_payment_method', models.CharField(choices=[('tc', 'کمیسیون و کرایه به شرکت'), ('tcd', 'کمیسیون به شرکت و کرایه به راننده'), ('cp', 'کمیسیون و کرایه با شرکت')], max_length=3)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='accounts.Account')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittanceDestinations', to='users.City')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittanceOrigins', to='users.City')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='wares.Ware')),
            ],
            options={
                'ordering': ['-code'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
