# Generated by Django 2.2 on 2020-06-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200614_1141'),
        ('_dashtbashi', '0004_remittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
