# Generated by Django 2.2 on 2020-07-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0004_auto_20200719_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.association', 'مشاهده کمیسیون انجمن'), ('create.association', 'تعریف کمیسیون انجمن'), ('update.association', 'ویرایش کمیسیون انجمن'), ('delete.association', 'حذف کمیسیون انجمن'), ('getOwn.association', 'مشاهده کمیسیون انجمن های خود'), ('updateOwn.association', 'ویرایش کمیسیون انجمن های خود'), ('deleteOwn.association', 'حذف کمیسیون انجمن های خود'))},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.car', 'مشاهده ماشین'), ('create.car', 'تعریف ماشین'), ('update.car', 'ویرایش ماشین'), ('delete.car', 'حذف ماشین'), ('getOwn.car', 'مشاهده ماشین های خود'), ('updateOwn.car', 'ویرایش ماشین های خود'), ('deleteOwn.car', 'حذف ماشین های خود'))},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.driver', 'مشاهده راننده'), ('create.driver', 'تعریف راننده'), ('update.driver', 'ویرایش راننده'), ('delete.driver', 'حذف راننده'), ('getOwn.driver', 'مشاهده راننده های خود'), ('updateOwn.driver', 'ویرایش راننده های خود'), ('deleteOwn.driver', 'حذف راننده های خود'))},
        ),
        migrations.AlterModelOptions(
            name='driving',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.driving', 'مشاهده انتصاب راننده به ماشین'), ('create.driving', 'تعریف انتصاب راننده به ماشین'), ('update.driving', 'ویرایش انتصاب راننده به ماشین'), ('delete.driving', 'حذف انتصاب راننده به ماشین'), ('getOwn.driving', 'مشاهده انتصاب راننده به ماشین خود'), ('updateOwn.driving', 'ویرایش انتصاب راننده به ماشین خود'), ('deleteOwn.driving', 'حذف انتصاب راننده به ماشین خود'))},
        ),
        migrations.AlterModelOptions(
            name='ladingbillnumber',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('revoke.ladingBillNumber', 'ابطال شماره بارنامه'), ('revokeOwn.ladingBillNumber', 'ابطال شماره بارنامه خود'))},
        ),
        migrations.AlterModelOptions(
            name='ladingbillseries',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.ladingBillSeries', 'مشاهده سری بارنامه'), ('create.ladingBillSeries', 'تعریف سری بارنامه'), ('update.ladingBillSeries', 'ویرایش سری بارنامه'), ('delete.ladingBillSeries', 'حذف سری بارنامه'), ('getOwn.ladingBillSeries', 'مشاهده سری بارنامه های خود'), ('updateOwn.ladingBillSeries', 'ویرایش سری بارنامه های خود'), ('deleteOwn.ladingBillSeries', 'حذف سری بارنامه های خود'))},
        ),
        migrations.AlterModelOptions(
            name='remittance',
            options={'default_permissions': (), 'ordering': ['-code'], 'permissions': (('get.remittance', 'مشاهده حواله'), ('create.remittance', 'تعریف حواله'), ('update.remittance', 'ویرایش حواله'), ('delete.remittance', 'حذف حواله'), ('getOwn.remittance', 'مشاهده حواله های خود'), ('updateOwn.remittance', 'ویرایش حواله های خود'), ('deleteOwn.remittance', 'حذف حواله های خود'))},
        ),
    ]
