# Generated by Django 2.2 on 2020-06-25 06:33

import _dashtbashi.models
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200618_1600'),
        ('_dashtbashi', '0005_remittance_financial_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remittance',
            options={'default_permissions': (), 'ordering': ['-code'], 'permissions': (('get.remittance', 'مشاهده حواله'), ('create.remittance', 'تعریف حواله'), ('update.remittance', 'ویرایش حواله'), ('delete.remittance', 'حذف حواله'))},
        ),
        migrations.CreateModel(
            name='Lading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('lading_number', models.IntegerField()),
                ('lading_date', django_jalali.db.models.jDateField()),
                ('lading_original_amount', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('lading_destination_amount', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('lading_explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('lading_attachment', models.FileField(blank=True, null=True, upload_to=_dashtbashi.models.upload_attachment_to)),
                ('bill_number', models.IntegerField()),
                ('bill_date', django_jalali.db.models.jDateField()),
                ('bill_price', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('bill_attachment', models.FileField(blank=True, null=True, upload_to=_dashtbashi.models.upload_attachment_to)),
                ('receive_type', models.CharField(blank=True, choices=[('cr', 'نسیه'), ('cs', 'نقدی'), ('p', 'کارت خوان')], max_length=2, null=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('associationCommission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='_dashtbashi.AssociationCommission')),
                ('driving', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='_dashtbashi.Driving')),
                ('lading_contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='accounts.Account')),
                ('remittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='_dashtbashi.Remittance')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.lading', 'مشاهده بارگیری'), ('create.lading', 'تعریف بارگیری'), ('update.lading', 'ویرایش بارگیری'), ('delete.lading', 'حذف بارگیری')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
