# Generated by Django 2.2 on 2020-06-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0006_auto_20200625_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lading',
            old_name='explanation',
            new_name='bill_explanation',
        ),
    ]
