# Generated by Django 2.2 on 2020-07-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0006_auto_20200726_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driving',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lading',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ladingbillnumber',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ladingbillseries',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oilcompanylading',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oilcompanyladingitem',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
