# Generated by Django 2.2 on 2020-06-25 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0012_auto_20200624_1518'),
        ('_dashtbashi', '0007_auto_20200625_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lading',
            name='lading_contractor_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='lading',
            name='lading_ware',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ladings', to='wares.Ware'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remittance',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
