# Generated by Django 2.2 on 2020-07-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0008_otherdriverpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdriverpayment',
            name='driving',
        ),
        migrations.AddField(
            model_name='otherdriverpayment',
            name='driving',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='otherDriverPayments', to='_dashtbashi.Driving'),
            preserve_default=False,
        ),
    ]
