# Generated by Django 2.2 on 2020-06-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200614_1141'),
        ('_dashtbashi', '0008_auto_20200625_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='lading',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laydings', to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
