# Generated by Django 2.2 on 2020-07-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20200726_0940'),
        ('_dashtbashi', '0009_auto_20200726_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdriverpayment',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear'),
            preserve_default=False,
        ),
    ]
