# Generated by Django 2.2 on 2020-06-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0009_lading_financial_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lading',
            old_name='lading_contractor',
            new_name='contractor',
        ),
        migrations.RenameField(
            model_name='lading',
            old_name='lading_contractor_price',
            new_name='contractor_price',
        ),
        migrations.RenameField(
            model_name='lading',
            old_name='lading_destination_amount',
            new_name='destination_amount',
        ),
        migrations.RenameField(
            model_name='lading',
            old_name='lading_original_amount',
            new_name='lading_bill_difference',
        ),
        migrations.RenameField(
            model_name='lading',
            old_name='lading_ware',
            new_name='ware',
        ),
        migrations.AddField(
            model_name='lading',
            name='original_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='lading',
            name='tip_payer',
            field=models.CharField(choices=[('cmp', 'شرکت'), ('cnt', 'پیمانکار')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lading',
            name='tip_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='lading',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladings', to='companies.FinancialYear'),
        ),
    ]
