# Generated by Django 2.2 on 2020-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0010_otherdriverpayment_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lading',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
