# Generated by Django 2.2 on 2020-06-26 08:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0011_auto_20200626_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_number_city_code',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=4),
        ),
    ]
