# Generated by Django 2.2 on 2020-06-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0012_auto_20200626_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_number',
        ),
    ]
