# Generated by Django 2.2 on 2020-06-26 08:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0013_remove_car_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=['19', 'ی', '332', '93'], size=4),
            preserve_default=False,
        ),
    ]
