# Generated by Django 2.2 on 2020-06-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0014_car_car_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='melli_code',
            new_name='owner_melli_code',
        ),
    ]
