# Generated by Django 2.2 on 2020-08-02 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0015_auto_20200802_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lading',
            name='billNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lading', to='_dashtbashi.LadingBillNumber'),
        ),
    ]
