# Generated by Django 2.2 on 2020-06-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_city'),
        ('_dashtbashi', '0015_auto_20200626_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='lading',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ladingDestinations', to='users.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lading',
            name='fare_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='lading',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ladingOrigins', to='users.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lading',
            name='remittance_payment_method',
            field=models.CharField(choices=[('tc', 'کمیسیون و کرایه به شرکت'), ('tcd', 'کمیسیون به شرکت و کرایه به راننده'), ('cp', 'کمیسیون و کرایه با شرکت')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lading',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='lading',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wares.Ware'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wares.Ware'),
        ),
    ]
