# Generated by Django 2.2 on 2020-08-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0016_auto_20200802_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='receivableAccount',
        ),
        migrations.AlterField(
            model_name='car',
            name='expenseAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carExpense', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='car',
            name='incomeAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carIncome', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='car',
            name='payableAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carPayable', to='accounts.Account'),
        ),
    ]
