# Generated by Django 2.2 on 2020-06-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0016_auto_20200628_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationcommission',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='companies.FinancialYear'),
        ),
    ]
