# Generated by Django 2.2 on 2020-06-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200614_1141'),
        ('_dashtbashi', '0017_auto_20200629_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssociationCommission',
            new_name='Association',
        ),
    ]
