# Generated by Django 2.2 on 2020-06-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0018_auto_20200629_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('get.association', 'مشاهده کمیسیون انجمن'), ('create.association', 'تعریف کمیسیون انجمن'), ('update.association', 'ویرایش کمیسیون انجمن'), ('delete.association', 'حذف کمیسیون انجمن'))},
        ),
        migrations.RenameField(
            model_name='lading',
            old_name='associationCommission',
            new_name='association',
        ),
    ]
