# Generated by Django 2.2 on 2020-08-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0018_auto_20200809_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='lading',
            name='car_income',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='lading',
            name='company_commission_income',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='lading',
            name='lading_bill_total_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='lading',
            name='lading_total_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
