# Generated by Django 2.2 on 2020-08-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0019_auto_20200809_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lading',
            name='receive_type',
            field=models.CharField(choices=[('cr', 'نسیه'), ('cs', 'نقدی'), ('p', 'کارت خوان')], default='p', max_length=2),
            preserve_default=False,
        ),
    ]
