# Generated by Django 2.2 on 2020-08-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0021_auto_20200816_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lading',
            name='bill_explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lading',
            name='lading_explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oilcompanylading',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdriverpayment',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
