# Generated by Django 2.2 on 2020-07-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0022_auto_20200630_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ladingbillnumber',
            options={'default_permissions': (), 'ordering': ['pk'], 'permissions': (('revoke.ladingBillNumber', 'ابطال شماره بارنامه'),)},
        ),
    ]
