# Generated by Django 2.2 on 2020-08-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0022_auto_20200816_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='floatAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='accounts.FloatAccount'),
        ),
    ]
