# Generated by Django 2.2 on 2020-08-19 07:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0023_auto_20200819_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
