# Generated by Django 2.2 on 2020-07-01 10:12

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200614_1141'),
        ('_dashtbashi', '0023_auto_20200701_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilCompanyLading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('export_date', django_jalali.db.models.jDateField()),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False)),
                ('driving', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oilCompanyLadings', to='_dashtbashi.Driving')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilCompanyLadings', to='companies.FinancialYear')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('get.oilCompanyLading', 'مشاهده بارگیری شرکت نفت'), ('create.oilCompanyLading', 'تعریف بارگیری شرکت نفت'), ('update.oilCompanyLading', 'ویرایش بارگیری شرکت نفت'), ('delete.oilCompanyLading', 'حذف بارگیری شرکت نفت')),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OilCompanyLadingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pure_price', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('tax_value', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True)),
                ('tax_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('complication_value', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=24, null=True)),
                ('complication_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('company_commission', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('car_income', models.DecimalField(decimal_places=0, default=0, max_digits=24)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.FinancialYear')),
                ('oilCompanyLading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='_dashtbashi.OilCompanyLading')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
