# Generated by Django 2.2 on 2020-07-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0024_oilcompanylading_oilcompanyladingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilcompanylading',
            name='driving',
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='oilCompanyLadings', to='_dashtbashi.Car'),
            preserve_default=False,
        ),
    ]
