# Generated by Django 2.2 on 2020-09-14 10:27

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0024_auto_20200819_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladingbillseries',
            name='date',
            field=django_jalali.db.models.jDateField(default='1399-06-24'),
            preserve_default=False,
        ),
    ]
