# Generated by Django 2.2 on 2020-09-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0025_ladingbillseries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lading',
            name='billNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lading', to='_dashtbashi.LadingBillNumber'),
        ),
    ]
