# Generated by Django 2.2 on 2020-07-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0026_auto_20200701_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lading',
            old_name='tip_price',
            new_name='cargo_tip_price',
        ),
        migrations.RenameField(
            model_name='lading',
            old_name='tip_payer',
            new_name='driver_tip_payer',
        ),
        migrations.RenameField(
            model_name='remittance',
            old_name='tip_payer',
            new_name='driver_tip_payer',
        ),
        migrations.RenameField(
            model_name='remittance',
            old_name='tip_price',
            new_name='driver_tip_price',
        ),
        migrations.AddField(
            model_name='lading',
            name='driver_tip_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
