# Generated by Django 2.2 on 2020-09-16 05:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0027_auto_20200916_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladingbillnumber',
            name='revoked_at',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
