# Generated by Django 2.2 on 2020-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0027_auto_20200702_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.CharField(choices=[('p', 'شراکتی'), ('o', 'دیگر'), ('rn', 'حاج رحمان'), ('rm', 'حاج رحیم'), ('e', 'حاج ابراهیم')], max_length=2),
        ),
    ]
