# Generated by Django 2.2 on 2020-07-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200618_1600'),
        ('_dashtbashi', '0028_auto_20200705_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driving',
            name='account',
        ),
        migrations.AddField(
            model_name='car',
            name='expenseAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carExpense', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='car',
            name='incomeAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carIncome', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='car',
            name='payableAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carPayable', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='driver',
            name='floatAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='accounts.FloatAccount'),
        ),
        migrations.AddField(
            model_name='driver',
            name='payableAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driverPayable', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='driving',
            name='floatAccountRelation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driving', to='accounts.FloatAccountRelation'),
        ),
    ]
