# Generated by Django 2.2 on 2020-09-16 07:25

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0029_auto_20200916_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladingbillnumber',
            name='revoked_at',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
