# Generated by Django 2.2 on 2020-07-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0029_auto_20200708_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oilcompanyladingitem',
            old_name='pure_price',
            new_name='gross_price',
        ),
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='insurance_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
