# Generated by Django 2.2 on 2020-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0030_auto_20200919_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('t', 'حمل و نقل'), ('c', 'رنگی')], default='t', max_length=2),
        ),
    ]
