# Generated by Django 2.2 on 2020-09-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0031_auto_20200919_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='contract_type',
        ),
    ]
