# Generated by Django 2.2 on 2020-09-21 09:54

from django.db import migrations, models
import django.db.models.deletion
import helpers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sanads', '0014_auto_20200921_1324'),
        ('_dashtbashi', '0032_auto_20200920_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilcompanylading',
            name='car',
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='car_income',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='company_commission_income',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='driving',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='oilCompanyLadings', to='_dashtbashi.Driving'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='sanad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oilCompanyLadings', to='sanads.Sanad'),
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='total_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='lading',
            name='bill_attachment',
            field=models.FileField(blank=True, null=True, upload_to=helpers.models.upload_to),
        ),
        migrations.AlterField(
            model_name='lading',
            name='lading_attachment',
            field=models.FileField(blank=True, null=True, upload_to=helpers.models.upload_to),
        ),
    ]
