# Generated by Django 2.2 on 2020-09-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0033_auto_20200921_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oilcompanylading',
            old_name='company_commission_income',
            new_name='company_commission',
        ),
    ]
