# Generated by Django 2.2 on 2020-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0034_auto_20200921_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcompanylading',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
