# Generated by Django 2.2 on 2020-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0035_oilcompanylading_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='company_commission_percent',
            field=models.IntegerField(default=0),
        ),
    ]
