# Generated by Django 2.2 on 2020-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0036_oilcompanyladingitem_company_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcompanylading',
            name='complication_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='oilcompanylading',
            name='tax_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
