# Generated by Django 2.2 on 2020-09-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200920_0943'),
        ('_dashtbashi', '0038_auto_20200921_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilcompanylading',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='oilcompanylading',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='oilcompanylading',
            name='weight',
        ),
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='oilCompanyLadingDestinations', to='users.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='oilCompanyLadingOrigins', to='users.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
