# Generated by Django 2.2 on 2020-09-21 10:52
import jdatetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0039_auto_20200921_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today()),
            preserve_default=False,
        ),
    ]
