# Generated by Django 2.2 on 2020-09-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0040_oilcompanyladingitem_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lading',
            old_name='original_amount',
            new_name='origin_amount',
        ),
        migrations.AlterField(
            model_name='car',
            name='contract_type',
            field=models.CharField(choices=[('t', 'حمل و نقل'), ('o', 'شرکت نفت')], default='t', max_length=2),
        ),
    ]
