# Generated by Django 2.2 on 2020-09-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0041_auto_20200922_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='lading',
            name='type',
            field=models.CharField(choices=[('l', 'بارگیری'), ('lb', 'بارگیری و بارنامه دولتی'), ('b', 'بارنامه دولتی')], default='lb', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lading',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='lading',
            name='driver_tip_payer',
            field=models.CharField(choices=[('cmp', 'شرکت'), ('cnt', 'پیمانکار')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lading',
            name='lading_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lading',
            name='remittance_payment_method',
            field=models.CharField(choices=[('tc', 'کمیسیون و کرایه به شرکت'), ('tcd', 'کمیسیون به شرکت و کرایه به راننده'), ('cp', 'کمیسیون و کرایه با شرکت')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lading',
            name='ware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wares.Ware'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='driver_tip_payer',
            field=models.CharField(choices=[('cmp', 'شرکت'), ('cnt', 'پیمانکار')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='remittance_payment_method',
            field=models.CharField(choices=[('tc', 'کمیسیون و کرایه به شرکت'), ('tcd', 'کمیسیون به شرکت و کرایه به راننده'), ('cp', 'کمیسیون و کرایه با شرکت')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='ware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wares.Ware'),
        ),
    ]
