# Generated by Django 2.2 on 2020-09-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_accounttype_financial_year'),
        ('_dashtbashi', '0042_auto_20200923_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='imprestAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carImprest', to='accounts.Account'),
        ),
    ]
