# Generated by Django 2.2 on 2020-09-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0045_oilcompanylading_insurance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcompanylading',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
