# Generated by Django 2.2 on 2020-10-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20201001_1533'),
        ('_dashtbashi', '0050_auto_20201001_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driving',
            unique_together={('driver', 'car', 'financial_year')},
        ),
    ]
