# Generated by Django 2.2 on 2020-10-17 07:21

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0051_auto_20201004_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcompanylading',
            name='list_date',
            field=django_jalali.db.models.jDateField(default=datetime.datetime(2020, 10, 17, 7, 21, 54, 248382, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
