# Generated by Django 2.2 on 2020-10-22 11:13

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0052_oilcompanylading_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lading',
            name='sanad_date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
