# Generated by Django 2.2 on 2020-10-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0053_lading_sanad_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcompanylading',
            name='net_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
