# Generated by Django 2.2 on 2020-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0055_auto_20201107_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.association', 'مشاهده کمیسیون انجمن'), ('create.association', 'تعریف کمیسیون انجمن'), ('update.association', 'ویرایش کمیسیون انجمن'), ('delete.association', 'حذف کمیسیون انجمن'), ('getOwn.association', 'مشاهده کمیسیون انجمن های خود'), ('updateOwn.association', 'ویرایش کمیسیون انجمن های خود'), ('deleteOwn.association', 'حذف کمیسیون انجمن های خود'))},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.car', 'مشاهده ماشین'), ('create.car', 'تعریف ماشین'), ('update.car', 'ویرایش ماشین'), ('delete.car', 'حذف ماشین'), ('getOwn.car', 'مشاهده ماشین های خود'), ('updateOwn.car', 'ویرایش ماشین های خود'), ('deleteOwn.car', 'حذف ماشین های خود'))},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.driver', 'مشاهده راننده'), ('create.driver', 'تعریف راننده'), ('update.driver', 'ویرایش راننده'), ('delete.driver', 'حذف راننده'), ('getOwn.driver', 'مشاهده راننده های خود'), ('updateOwn.driver', 'ویرایش راننده های خود'), ('deleteOwn.driver', 'حذف راننده های خود'))},
        ),
        migrations.AlterModelOptions(
            name='driving',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.driving', 'مشاهده انتصاب راننده به ماشین'), ('create.driving', 'تعریف انتصاب راننده به ماشین'), ('update.driving', 'ویرایش انتصاب راننده به ماشین'), ('delete.driving', 'حذف انتصاب راننده به ماشین'), ('getOwn.driving', 'مشاهده انتصاب راننده به ماشین خود'), ('updateOwn.driving', 'ویرایش انتصاب راننده به ماشین خود'), ('deleteOwn.driving', 'حذف انتصاب راننده به ماشین خود'))},
        ),
        migrations.AlterModelOptions(
            name='lading',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.lading', 'مشاهده بارگیری'), ('create.lading', 'تعریف بارگیری'), ('update.lading', 'ویرایش بارگیری'), ('delete.lading', 'حذف بارگیری'), ('getOwn.lading', 'مشاهده بارگیری های خود'), ('updateOwn.lading', 'ویرایش بارگیری های خود'), ('deleteOwn.lading', 'حذف بارگیری های خود'), ('firstConfirm.lading', 'تایید اول بارگیری '), ('secondConfirm.lading', 'تایید دوم بارگیری '), ('firstConfirmOwn.lading', 'تایید اول بارگیری های خود'), ('secondConfirmOwn.lading', 'تایید دوم بارگیری های خود'))},
        ),
        migrations.AlterModelOptions(
            name='ladingbillnumber',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('revoke.ladingBillNumber', 'ابطال شماره بارنامه'), ('revokeOwn.ladingBillNumber', 'ابطال شماره بارنامه خود'))},
        ),
        migrations.AlterModelOptions(
            name='ladingbillseries',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.ladingBillSeries', 'مشاهده سری بارنامه'), ('create.ladingBillSeries', 'تعریف سری بارنامه'), ('update.ladingBillSeries', 'ویرایش سری بارنامه'), ('delete.ladingBillSeries', 'حذف سری بارنامه'), ('getOwn.ladingBillSeries', 'مشاهده سری بارنامه های خود'), ('updateOwn.ladingBillSeries', 'ویرایش سری بارنامه های خود'), ('deleteOwn.ladingBillSeries', 'حذف سری بارنامه های خود'))},
        ),
        migrations.AlterModelOptions(
            name='oilcompanylading',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.oilCompanyLading', 'مشاهده بارگیری شرکت نفت'), ('create.oilCompanyLading', 'تعریف بارگیری شرکت نفت'), ('update.oilCompanyLading', 'ویرایش بارگیری شرکت نفت'), ('delete.oilCompanyLading', 'حذف بارگیری شرکت نفت'), ('getOwn.oilCompanyLading', 'مشاهده بارگیری شرکت نفت خود'), ('updateOwn.oilCompanyLading', 'ویرایش بارگیری شرکت نفت خود'), ('deleteOwn.oilCompanyLading', 'حذف بارگیری شرکت نفت خود'), ('firstConfirm.oilCompanyLading', 'تایید اول بارگیری شرکت نفت '), ('secondConfirm.oilCompanyLading', 'تایید دوم بارگیری شرکت نفت '), ('firstConfirmOwn.oilCompanyLading', 'تایید اول بارگیری شرکت نفت خود'), ('secondConfirmOwn.oilCompanyLading', 'تایید دوم بارگیری شرکت نفت خود'))},
        ),
        migrations.AlterModelOptions(
            name='oilcompanyladingitem',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='otherdriverpayment',
            options={'default_permissions': (), 'ordering': ['-pk'], 'permissions': (('get.otherDriverPayment', 'مشاهده پرداخت رانندگان متفرقه '), ('create.otherDriverPayment', 'تعریف پرداخت رانندگان متفرقه'), ('update.otherDriverPayment', 'ویرایش پرداخت رانندگان متفرقه'), ('delete.otherDriverPayment', 'حذف پرداخت رانندگان متفرقه'), ('getOwn.otherDriverPayment', 'مشاهده پرداخت رانندگان متفرقه خود'), ('updateOwn.otherDriverPayment', 'ویرایش پرداخت رانندگان متفرقه خود'), ('deleteOwn.otherDriverPayment', 'حذف پرداخت رانندگان متفرقه خود'), ('firstConfirm.otherDriverPayment', 'تایید اول پرداخت رانندگان متفرقه '), ('secondConfirm.otherDriverPayment', 'تایید دوم پرداخت رانندگان متفرقه '), ('firstConfirmOwn.otherDriverPayment', 'تایید اول پرداخت رانندگان متفرقه خود'), ('secondConfirmOwn.otherDriverPayment', 'تایید دوم پرداخت رانندگان متفرقه خود'))},
        ),
    ]
