# Generated by Django 2.2 on 2020-11-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0057_auto_20201108_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lading',
            name='local_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oilcompanylading',
            name='local_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdriverpayment',
            name='local_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='local_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
