# Generated by Django 2.2 on 2020-11-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0058_auto_20201108_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lading',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lading',
            name='first_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_ladingConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lading',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lading',
            name='second_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_ladingConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oilcompanylading',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oilcompanylading',
            name='first_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_oilcompanyladingConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oilcompanylading',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oilcompanylading',
            name='second_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_oilcompanyladingConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otherdriverpayment',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdriverpayment',
            name='first_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_otherdriverpaymentConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otherdriverpayment',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdriverpayment',
            name='second_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_otherdriverpaymentConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='first_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='first_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_remittanceConfirmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='second_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='second_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_remittanceConfirmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
