# Generated by Django 2.2 on 2020-12-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0060_auto_20201221_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcompanyladingitem',
            name='bill_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
