# Generated by Django 2.2 on 2020-12-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0063_oilcompanyladingitem_net_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lading',
            name='lading_bill_difference_receiver',
            field=models.CharField(choices=[('cmp', 'شرکت'), ('drv', 'راننده')], default='drv', max_length=3),
        ),
    ]
