# Generated by Django 2.2 on 2020-12-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0064_lading_lading_bill_difference_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lading',
            name='lading_bill_difference_receiver',
            field=models.CharField(choices=[('cmp', 'شرکت'), ('drvr', 'راننده')], default='drvr', max_length=4),
        ),
    ]
