# Generated by Django 2.2 on 2021-03-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0066_auto_20210227_1110'),
        ('_dashtbashi', '0066_auto_20210227_1102'),
    ]

    operations = [
    ]
