# Generated by Django 2.2 on 2021-04-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20210414_1349'),
        ('_dashtbashi', '0068_auto_20210301_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lading',
            unique_together={('financial_year', 'lading_number')},
        ),
    ]
