# Generated by Django 2.2 on 2021-05-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_companyuser_financialyears'),
        ('_dashtbashi', '0068_auto_20210301_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lading',
            unique_together={('financial_year', 'lading_number')},
        ),
    ]
