# Generated by Django 2.2 on 2021-05-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashtbashi', '0069_auto_20210511_1250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lading',
            unique_together=set(),
        ),
    ]
