# Generated by Django 2.2 on 2021-05-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_auto_20210516_1349'),
        ('_dashtbashi', '0071_auto_20210519_1035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lading',
            unique_together={('financial_year', 'lading_number')},
        ),
    ]
